### ISSUE TITLE
Allow empty values in patch and put requests.

### ISSUE THREAD

**Issue by ran81** [RESTful-Drupal/restful#101]
When using the patch() or put() methods to update an entity there's no way to empty a field's value in case of a field with cardinality of 1. In the function `setProperyValues()` we check:
`if (!isset($request[$public_property]))`
And if we send a value of NULL we skip this property and we get an exception later on.

Note that for fields that are multiple this works fine by sending `array(NULL)` in the request for that property.

**Comment by amitaibu** [comment]
Thanks, can you provide a PR?

**Comment by shushu** [comment]
Update: restful can empty values when set to `$null_missing_fields=TRUE`.
I tested on clean D7 with restful installed and with Postman client. When sending an entity without one of the public fields, it will put null into it, and I was able to empty a list<text> field this way.
Note: I was using `restful example` module, which uses the `RestfulEntityBase::putEntity()` that set `null_missing_fields` to TRUE as needed.
Looking into the implementation of `OsProfilesResource` (from OpenScholar) it seems it do the same, so all you need is to send the entity without the key of the empty value, and it should be NULLed.

**Comment by ran81** [comment]
@shushu 

I understand that empty fields should not be sent at all in the request. That is fine for creation of nodes but for update of nodes we should be able to hit an end point with an empty value and clearing the field.

**Comment by amitaibu** [comment]
in that case you can check `$request[$public_property] === NULL`

**Comment by amitaibu** [comment]
Is this still and issue? Please re-open if so.
