### ISSUE TITLE
Clean restful installation on clean D7 creates an irrelevant menu item

### ISSUE THREAD

**Issue by shushu** [RESTful-Drupal/restful#102]
See 
![selection_024](https://cloud.githubusercontent.com/assets/99186/3488461/7da2eb06-04e5-11e4-857b-fcf5ff83290e.png)

**Comment by amitaibu** [comment]
PRs are welcome :) Probably changing the menu type in `hook_menu()`

**Comment by amitaibu** [comment]
@shushu can you please provide a PR on your daily contribution hour.

**Comment by shushu** [comment]
np, tomorrow.
