### ISSUE TITLE
Genreal rate limit

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#105]
Currently our rate limit is per resource.
It would be nicer to be able to say, like Github has, you may access any resource up to 5000 in total.

**Comment by e0ipso** [comment]
I like the idea. I'm wondering where to do this since we don't have a controller for all the handlers.

**Comment by amitaibu** [comment]
maybe a variable?

**Comment by e0ipso** [comment]
Working on this.

**Comment by e0ipso** [comment]
Closed in favor of #121
