### ISSUE TITLE
Affected by SA-CORE-2019-003?

### ISSUE THREAD

**Issue by krisahil** [RESTful-Drupal/restful#1055]
Hello,
Is this project affected by the same vulnerability from https://www.drupal.org/sa-core-2019-003? I noticed that another contrib module is affected (`restws`, see https://www.drupal.org/sa-contrib-2019-018), but I saw nothing about `restful` module.

My hunch is that no news is good news, but just want to double-check.
Thank you!

**Comment by OnGitHubSchatz** [comment]
Here is the relevant fix for Services module's 7.x-3.x branch: https://cgit.drupalcode.org/services/commit/?h=7.x-3.x&id=002f8c87fb40df714681345a4c5589ec0777b11f released today.
I'm looking for similar in Restful code now.

**Comment by OnGitHubSchatz** [comment]
Update given the Services patch: Restful 7.x-2.x already implements an operator allow-list in the [DataProvider](https://github.com/RESTful-Drupal/restful/blob/d996c6ee6043bcc8472be5e857de2234fff66887/src/Plugin/resource/DataProvider/DataProvider.php#L461) and [DataProviderEntity ](https://github.com/RESTful-Drupal/restful/blob/d996c6ee6043bcc8472be5e857de2234fff66887/src/Plugin/resource/DataProvider/DataProviderEntity.php#L838) classes in addition to controlling conjunctions in `isValidConjunctionForFilter` method. 

From this I would say it is clear of specific vector for [SA-CONTRIB-2019-026](https://www.drupal.org/sa-contrib-2019-026)

**Comment by e0ipso** [comment]
We are looking good on this regard. As @gitschatz is pointing out, we already had that protection a while ago.

**Comment by krisahil** [comment]
Great. Thank you for looking into this!
I'll now close this thread.

**Comment by OnGitHubSchatz** [comment]
Heads up @krisahil: 

Module was cleared for SA-CONTRIB-2019-026 but was just patched for SA-CORE-2019-003 (entity field validation) in this commit https://cgit.drupalcode.org/restful/commit/?id=5633f598a05fab6bb74c805b20ea828a1a9ced80 tagged with 7.x-2.17. 

There is a corresponding release for Restful 1.x branch. Many thanks to @ordavidil :clap:
