### ISSUE TITLE
Self Documenting REST API

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#116]
Would be nice to have something as @larowlan did for D8's REST https://www.drupal.org/project/rest_api_doc

**Comment by larowlan** [comment]
Happy to pool notes

**Comment by e0ipso** [comment]
This could be a contrib that depends on `restful` as well.

**Comment by amitaibu** [comment]
And possibly using another library that already does it. An important feature no doubt..

‫ב-15 בספט 2014, בשעה 09:41, ‏Mateu Aguiló Bosch notifications@github.com כתב/ה:‬

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
