### ISSUE TITLE
Port to D8

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#117]
This should be done probably only after we've reached an alpha -- which I feel we're pretty close.

I'm just putting a name here. not implying anything. @fubhy :)

**Comment by RoySegall** [comment]
We already have the branch. I think the porting process won't take long since most of the module is written in OOP

**Comment by RoySegall** [comment]
All the plugins converted to the new plugin system. The next thing to do is porting the hook_menu to the new routing system. I start to work on something: https://github.com/Gizra/restful/blob/8.x-1.x/src/Routing/RouteSubscriber.php#L27

**Comment by RoySegall** [comment]
well.. We got something:
![selection_064](https://cloud.githubusercontent.com/assets/1222368/4114848/faf3374e-326e-11e4-8187-8b75c383f557.png)

**Comment by amitaibu** [comment]
אלוף!

btw, Just from looking at the URL the correct should be v1 (the minor version is passed in the HTTP headers)

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch what do you say that after we get #129 in, we tag an alpha, and then start helping @RoySegall with D8, hopefully getting it ready for DrupalCon?

On cc the rest of the geeks that might help us @fubhy @joshk @c4rl ;)

**Comment by joshk** [comment]
Are you sure you meant to cc me?

**Comment by amitaibu** [comment]
@joshk oops, sorry but, thanks for Travis-CI ;). 
I meant @joshkoenig

**Comment by joshk** [comment]
My pleasure :)

**Comment by amitaibu** [comment]
... and @scottrigby as well :)

**Comment by e0ipso** [comment]
/me :heart: Travis-CI.

@amitaibu I feel that a D8 version for DCon is a great marketing effort. But I also feel that there are several key features yet to be discovered for the D7 version. The first thing that comes to my mind is Mime Type negotiation (now that we support different output formats), but I'm sure there are several more.

With all that I'll say that your plan sounds right, but I'd wait a bit more on that.

**Comment by amitaibu** [comment]
> I feel that a D8 version for DCon is a great marketing effort.

Indeed, marketing is important  - (also, don't tell them, I'm secretly trying to get more contributors to the project :wink: )

> With all that I'll say that your plan sounds right, but I'd wait a bit more on that.

My take is that it's better to start early, and "chase" D7 (along with chasing D8...). As it is RESTful is already pretty big, so there are a lot of parts I think we can already tackle in order to save time for later.

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
