### ISSUE TITLE
Create output plugin for output format flexibility.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#127]
I think RESTful should be opinionated about the output format. A variation of [JSON API](http://jsonapi.org/) is my preferred format and I'd like to see the module following that. The only I'd like to have with it is that I think that when getting a specific single item we should not be returning an array with only one item but an object. I also like having `"data"` as a common object key for … well, data.

Having an output plugin and defining our default one (`json_api_custom`) will allow module integrators to easily have APIs in YML, other JSON structures, or `$deity` forbids… XML.

**Comment by amitaibu** [comment]
>  I think that when getting a specific single item we should not be returning an array with only one item but an object. I also like having "data" as a common object key for … well, data.

Indeed, that's what #126 is doing, and I think it's ok to "force" it. If someone insists on changing them they can override the needed methods.

> Having an output plugin and defining our default one (json_api_custom) will allow module integrators to easily have APIs in YML, other JSON structures, or $deity forbids… XML.

Let's avoid this for now. Or put differently, lets consider this when someone asks for it, for a _real_ use case :)

Please re-open if you feel strongly about it.

**Comment by amitaibu** [comment]
Oh, I saw in your comment you are already working on this, so re-opening. I might be missing your point?

**Comment by amitaibu** [comment]
What's your use case for this?

**Comment by e0ipso** [comment]
@amitaibu imagine an EmberJS that gets you very far in client side if your API is returning JSON in a specific format. Imagine some dev that has to implement an API that has already a test suite built around a specific output format, if we don't allow overriding they may need to look somewhere else for the API.

**Comment by amitaibu** [comment]
I can only imagine AngularJs ;)
Ok, as always, your point is valid! :)

**Comment by e0ipso** [comment]
hahaha. AngularJS is the best.

**Comment by e0ipso** [comment]
Closed in favor of https://github.com/Gizra/restful/pull/129
