### ISSUE TITLE
Provide image style integration for image fields.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#134]
The idea is to have some extra configuration for the image fields (maybe also think of a generic way to have extra config for fields with nice helper methods) that will list an array of image styles.

That way we can output different image urls for different sizes. I think this is important b/c client apps usually are not great at resizing images and also there's bandwidth to consider.

So when we build the return array for an entity that contains an image field we output the url to the original image and all image styles listed for that field instance for that particular endpoint.

**Comment by amitaibu** [comment]
I've done something like this - see [here](https://github.com/Gizra/garmentbox/blob/overhaul-1/garmentbox/modules/custom/gb_restful/plugins/restful/node/item_variants/1.0/GbItemVariantsResource.class.php#L29) and [here](https://github.com/Gizra/garmentbox/blob/overhaul-1/garmentbox/modules/custom/gb_restful/gb_restful.module#L46)

Do you think we should have something similar to `gb_restful_get_images_styles` in restful.module?

**Comment by e0ipso** [comment]
@amitaibu that approach makes a lot of sense. I'm good with closing this issue with a documentation PR or something more baked in.

**Comment by amitaibu** [comment]
Closed in favor of #142
