### ISSUE TITLE
Error due to "rate_limit" entity type does not exist on 8.x-1.x

### ISSUE THREAD

**Issue by shushu** [RESTful-Drupal/restful#136]
1. Installing last D8 alpha.
2. Cloning restful and enabling restful and restful example modules.
   Gives a fatal error:
   ![selection_273](https://cloud.githubusercontent.com/assets/99186/4145706/5a69f25e-33fe-11e4-9995-e0c87586ad6e.png)
   And in the log we get:
   [Thu Sep 04 09:33:28 2014] [error] [client 127.0.0.1] Uncaught PHP Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "rate_limit" entity type does not exist." at /var/www/d8/www/core/lib/Drupal/Core/Entity/EntityManager.php line 207

**Comment by amitaibu** [comment]
Yeah 8.x is wip. Roy can you please rename the branch so it won't be confusing (maybe port-8)

‫ב-4 בספט 2014, בשעה 09:40, ‏Shushu Inbar notifications@github.com כתב/ה:‬
