### ISSUE TITLE
Improve the logic of imageProcess and image_styles

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#148]
@mateu-aguilo-bosch 
Currently the new image_styles will work only if one would implement something similar to `\RestfulExampleArticlesResource__1_5::imageProcess()`.

Maybe we should move `imageProcess()` to the base class as-well?

**Comment by e0ipso** [comment]
I don't think that you **need** the `imageProcess`. As is it will add an array of derivatives to the `$file_array`, what you do with that is up to you. You could want to output it as is.
