### ISSUE TITLE
Return 401 for missing user instead of 403.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#152]

**Comment by amitaibu** [comment]
just for user, or any entity?

**Comment by e0ipso** [comment]
This is not-a-bug.

401 is set via:
https://github.com/Gizra/restful/blob/7.x-1.x/plugins/authentication/RestfulAuthenticationManager.php#L91 and then https://github.com/Gizra/restful/blob/7.x-1.x/exceptions/RestfulUnauthorizedException.php#L15
