### ISSUE TITLE
render taxonomy tree's

### ISSUE THREAD

**Issue by MuschPusch** [RESTful-Drupal/restful#168]
Hey, i'm wondering how to render parts of a taxonomy tree. To give an example:

_Endpoint: api/v1/tree/_
- 1 
- \- 2
- \- 3
- \- - 4
- \- - 5
- \- 6

_Endpoint: api/v1/tree/3_
- \- 3
- \- - 4
- \- - 5
  etc. 

I already found out i can overwrite getQueryForList for fetching all parents with something similar to what taxonomy_get_children does but how do i achieve to get the nested output as return value?

**Comment by d34dman** [comment]
From what i understand endpoint api/v1/tree/3 would fetch the entity with id 3.
you would have to do something like api/v1/tree?parent=3
and override the public function getList()  to recognise your custom filter.

**Comment by e0ipso** [comment]
From what I can see there are 2 different things that you need to accomplish. Your custom restful plugin will need to list the term and its parent id.

``` javascript
{
  'tid': 1,
  'name': 'foo',
  'parent': null
},
{
  'tid': 2,
  'name': 'bar',
  'parent': 1
},
{
  'tid': 3,
  'name': 'baz',
  'parent': 2
},
```

And then the prepare function of your custom formatter should read the values in that and transform them into the appropriate output.

``` javascript
{
  'foo': {
    'bar': [
      'baz'
    ]
  }
}
```

**Comment by amitaibu** [comment]
Seems resolved. Re-open if needed.
