### ISSUE TITLE
Find/ document best practices for RESTful in front of Solr/ Elastic search

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#169]
Maybe this one should be discussed in DrupalCon Amsterdam, but I think it's worth starting in writing.

My use case is a fully decoupled web app, that uses Drupal as the backend.
Drupal has Solr integration + facets, which I'd like to expose to the web app.
Here's a silly example of how a search page will look in Drupal itself:

`foo-search/black?f[0]=title%3Ablack&f[1]=author%3A1`
![item-search___site-install_and_vlad_ _vagrant_vlad___var_www_site_docroot_garmentbox_www_ _ssh_ _80x24](https://cloud.githubusercontent.com/assets/125707/4410177/f38c1016-44e3-11e4-892a-de30383b7256.jpg)

So there are a few questions (which I try to answer) on how to get it "right":

Q. what's the url the web app should call?
A. RESTful is advocating for having the prefix start with `api/` -- as RESTful can hijack any api/\* - to make sure all response is always in json. So my answer would be something like `api/foo-search?f[0]=title%3Ablack&f[1]=author%3A1` -- where the params are passed along to search api.

Q. How/ when do we get the facets?
A. We should have a formatter plugin that adds the facet api, in the `prepare` function, so results would be in

``` php
'data' => array(),
'facets' => array()
```

Q. Who should cache the calls?
A. The web app shouldn't call server on same URL, although the local storage might become pretty big. Also `render cache` on restful should probably be enabled.

a nice task would be creating an example Drupal module + web app that demonstrates that.

@mateu-aguilo-bosch any thoughts?
/cc @Crell as his [post](http://drupalwatchdog.com/volume-4/issue-2/decoupling-drupal) has inspired this issue

**Comment by amitaibu** [comment]
cc @cpliakas as he's around this issue queue from time to time as-well ;)

**Comment by e0ipso** [comment]
I guess that kind of falls outside of the RESTful definition and is more an RPC. That being said I don't see a big problem on declaring searchable resources, just like I don't see big problems on having `views` powered resources or even SQL query driven resources.

We have done pretty cool stuff with **child plugins**, and that would be one way to go (just like the system declares a resource for every role in the example we could declare automatically a resource per facet), but that is always limited to one entity type. If we want to go general (we probably do), and have **cross-entity searches** then we probably need to do the Solr, views, manual SQL query integration.

All the effort I have been doing on moving the non Entity specific code from `RestfulEntityBase` to `RestfulBase` is in that direction, although I'm not sure we're quite there yet.

Maybe this could be the first interesting contrib of a RESTful eco-system: `restful_search_api` or whatever.

> Q. what's the url the web app should call?

I would like to have _verb free_ URL endpoints, but yeah `api/results?f[0]=title%3Ablack&f[1]=author%3A1` works for me too.

> Q. How/ when do we get the facets?

I think this is in the fine grain details area. I am not sure why the client needs to get back the list of facets as a hard requirement. Although it can be nice to have a `hal_json_facet` formatter I am not sure this is a main concern.

> Q. Who should cache the calls?

Regardless of the client tricks, the backend should cache identical calls. Bypassing an HTTP request and a Solr search is a big performance win. The problem, of course, is invalidation. As-is, the module allow you to configure your caching per resource so I guess that having a highly volatile memcache (or whatever) would do for most of cases. If we get crazy we could index the cache searches by the number of searches on particular search conditions.

**Comment by amitaibu** [comment]
> and have cross-entity searches then we probably need to do the Solr, views, manual SQL query integration.

The resource would probably map to the Search API index entity.

> I am not sure why the client needs to get back the list of facets as a hard requirement.

No hard requirements. I'm just thinking of a typical scenario, and try to figure what's the best way to approach it. What I like about the work we've done in RESTful is that it's always accompanied with real cases -- and example modules as solutions.

@mateu-aguilo-bosch are you coming to Amsterdam?

**Comment by e0ipso** [comment]
> are you coming to Amsterdam?

Absolutely. Should we try to recruit some helping hands there?

**Comment by cpliakas** [comment]
This is a great thread, thanks for mentioning me. I do know that @nickveenhof is in Amsterdam, might be worth tracking him down as I am sure he would be interested in this topic.

**Comment by e0ipso** [comment]
I am going to start tacking this in baby steps. Since we're adding a layer of abstraction here, it is very probable that parts of the plugin definition, or even the API shift a bit.

I will probably break this into different issues, some of them will be release blockers.

**Comment by e0ipso** [comment]
Let's not forget about this issue.

**Comment by e0ipso** [comment]
We have now [restful_search_api](https://github.com/RESTful-Drupal/restful_search_api). Fuck yeah!

Includes:
- [x] Support for Search API searches.
- [x] Support for ranges and pagination.
- [x] Support for ordering.
- [x] Support for filtering.
- [x] Facet information on the search callback.

**Comment by e0ipso** [comment]
@amitaibu feel free to treat [restful_search_api](https://github.com/RESTful-Drupal/restful_search_api) as your own.

**Comment by amitaibu** [comment]
Amazing stuff! Thanks! :)

**Comment by amitaibu** [comment]
- Start writing f**king posts about it!! ;)

**Comment by e0ipso** [comment]
> Start writing f**king posts about it!! ;)

Well, then you review them: https://medium.com/@e0ipso/f370050a26bb

**Comment by amitaibu** [comment]
Looks really good. Maybe worth adding an example of a JSON output.

**Comment by amitaibu** [comment]
Oh the image on top is exactly that.

**Comment by e0ipso** [comment]
@amitaibu yeah… maybe not **too** obvious, right?

**Comment by e0ipso** [comment]
Published article: https://medium.com/@e0ipso/restful-drupal-with-search-api-f370050a26bb
