### ISSUE TITLE
Mirror the README in Drupal.org

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#182]
When you hit https://www.drupal.org/project/restful you see nothing. You should see something very similar to what it's on https://github.com/Gizra/restful

**Comment by amitaibu** [comment]
I'm not sure if it's an effort worth taking -- as it's more then copy & paste, since Drupal.org doesn't support markdown.

Also, IMO it's fine just having a link here - so it's clear Github is the place where the things happen.

**Comment by amitaibu** [comment]
Closing. Re-open if you feel strongly about it :)

**Comment by e0ipso** [comment]
It's OK. I feel that we need something more over there to capture the eye's attention, but maybe we don't need a 1:1 copy.
