### ISSUE TITLE
Add helper methods to set request for API

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#185]
Currently we pass the sort, filter and fileds via the $request array e.g. `$handler->get('', $request)`.

It would probably be a better DX to have those as methods.

e.g.

``` php
$result = $handler
  // These we actually already have
  ->setMethod(...)
  ->setPath(...)
  /New ones.
  ->addSort('id', DESC)
  ->addFilter('label', 'foo')
  ->execute()
```

Also, we could implement __toString, to get the http request that should be used. 

@mateu-aguilo-bosch what do you think?

**Comment by e0ipso** [comment]
That's awesome. I'm all in for it. Especially the __toString

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
