### ISSUE TITLE
Implement ng-admin as a (real use case) example

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#191]
Apart of a good example, ng-admin sounds like it's doing a lot of heavy lifting. If we'll put a login in front of it, this is a good step to the holy grail of decoupled admins.

I've already had some [problems](https://github.com/marmelab/ng-admin/issues/75) on installation, but admittedly I didn't invest too much time there yet.

**Comment by amitaibu** [comment]
@davidhwang you don't get to sit this one out :)

**Comment by amitaibu** [comment]
Now that there's a [demo](https://github.com/marmelab/ng-admin-demo) repo for ng-admin, I was able to get the first step

![angular_admin-4](https://cloud.githubusercontent.com/assets/125707/4669286/c7923cf8-556c-11e4-86bd-8db3261e5af0.jpg)

**Comment by e0ipso** [comment]
I think that to make a game-changing & kick-ass AngularJS component we need more automatic discovery tools. I can see how you can make an OPTIONS call to the server for a particular endpoint and you get in return the information about the fields that you can get/set for every method.

This way the client side application can build forms **without knowing anything about the API in advance!**. This component could be distributed as a generic starting point for AngularJS form generators.

I'm going to tag these backend issues as _Discovery effort_.

Strategic thoughts?

**Comment by amitaibu** [comment]
> Strategic thoughts?
1. Take it in steps. ng-admin is already doing a lot of heavy lifting, so I wouldn't want to start from scratch
2. Get Drupal people excited about it
3. Get ng-admin people excited about it
4. Standardize and profit :)

**Comment by e0ipso** [comment]
> ng-admin is already doing a lot of heavy lifting

That's awesome, I need to read more about that.

> Get Drupal people excited about it

Working on it…

> Get ng-admin people excited about it

Not sure how to do that. Maybe you have ideas…

> Standardize and profit :)

I think this is a key (unspoken) point. I tried to find standards to follow after every idea I had so we can get things for free (even if we don't know what are those things). Good profit to come behind this project, let's try to deliver and keep the hype high.

**Comment by amitaibu** [comment]
Profit in point 4 == Getting more people on board. Monetary stuff are a bonus ;)

**Comment by e0ipso** [comment]
> Monetary stuff are a bonus ;)

Yeah, I realized a long time ago that monetary profit is something that doesn't drive motivation. I also meant profit as in rewarding experiences in general.

**Comment by davidhwang** [comment]
Thanks for the ping, amitaibu -- this looks _very_ promising. I'll be sure to give it a spin.

**Comment by mirzu** [comment]
So this might be relvelent to this thread: 
http://mirzu.fourword.webchefs.org/hal-browser/browser.html#/api/v1/blogposts/142

https://github.com/mikekelly/hal-browser is a ng-admin type thing that is specific to HAL. It's a simple html file that is 0 config for a HAL / HATEOAS api. 

The 4K blog needs a bunch of work before it implements everything that this browser is aware of, but here is a full working example:
http://haltalk.herokuapp.com/explorer/browser.html#/

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
