### ISSUE TITLE
Improve variables handling

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#196]
Not to block #189, I've opened a new issue:
1. api/v1/variables/wrong-key -- should throw an exception
2. Add "self" link
3. Add access callback
4. Show the unserialized value

![local_d7_dev_api_v1_variables-3](https://cloud.githubusercontent.com/assets/125707/4690658/4d44fc8c-56f3-11e4-853f-0906f324f356.jpg)

**Comment by e0ipso** [comment]
Closed in favor of https://github.com/Gizra/restful/pull/211
