### ISSUE TITLE
Update the main documentation.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#217]
@amitaibu I propose changing:

> This module follows this post to achieve a practical RESTful for Drupal

by _This module achieves a practical RESTful for Drupal with the best practises_

I really like the _best practises_ and _practical_ mantra. To me these are the core values of this module.

Would you agree?

cc @mirzu

**Comment by amitaibu** [comment]
Funny, I was just thinking about thus yesterday. Yeah, change is needed + we've probably implemented more than that post suggested. Still, it gave a good start :)

‫ב-26 באוק 2014, בשעה 19:31, ‏Mateu Aguiló Bosch notifications@github.com כתב/ה:‬
