### ISSUE TITLE
Move the self property into the _links section.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#219]
See https://github.com/Gizra/restful/issues/186#issuecomment-59830785

**Comment by amitaibu** [comment]
Seems we will need to add some kind of a addHateoas() per entity/ row -- not only for lists; Or do you have another idea?

**Comment by mirzu** [comment]
I made this work with the "reference implementation" AKA giant hack I've been working on. When I got down to it having those addHateoas at the collection level didn't feel right and I see potential issues down the line. I think a better approach would be to process each individual item and then feed those into the collection resource already formatted. Basically make the collections work more like collections. Not sure yet how to facilitate that in the code however. Maybe have a separate format item resource and a separate format collection resource step.

**Comment by amitaibu** [comment]
@mirzu I've added my approach in https://github.com/Gizra/restful/issues/186#issuecomment-61610985

**Comment by e0ipso** [comment]
This is done.
