### ISSUE TITLE
When creating entity using - the self property no longer lead to the created node. Why?

### ISSUE THREAD

**Issue by RoySegall** [RESTful-Drupal/restful#229]
As the title discover after creating an entity, node for example, the JSON that return used to holds the url of that node. That was useful because i was able to redirect the user to the new node. Is there a way to to bring it back or the new [approach](http://www.gizra.com/content/restful-discovery/) with the self property will block the feature request?

**Comment by amitaibu** [comment]
You can add another public field (e.g. url ) that will be like the old self

‫ב-2 בנוב 2014, בשעה 21:23, ‏Roy Segall notifications@github.com כתב/ה:‬
