### ISSUE TITLE
Implement curries as a complement to OPTIONS

### ISSUE THREAD

**Issue by mirzu** [RESTful-Drupal/restful#232]
Sending OPTIONS is great for building clients that automatically get the info, and curies provide a great way to have human readable docs generated in addition to the OPTIONS docs.

I would imagine that this would require a number of tasks, but it looks like the options stuff is most of the info that would be in the curries.

Tasks: 

Make a new menu item api-docs/{rel}?
Add the curies prefix to links and embedded resources. They get added to all documented rel attributes.
Add the curies item to links for each resource. 
Theme a page that is generated from the info we have in Options.
#186

**Comment by amitaibu** [comment]
> Make a new menu item api-docs/{rel}?

That should be optional, as I don't think we need to assume the docs being served from Drupal. I would personally probably build a Jekyll site for docs, so the curies should be able to reference remote URLs.

**Comment by mirzu** [comment]
Then maybe make a documentation formatter so we can support both?

On Tue, Nov 4, 2014 at 7:56 AM, Amitai Burstein notifications@github.com
wrote:

> Make a new menu item api-docs/{rel}?
> 
> That should be optional, as I don't think we need to assume the docs being
> served from Drupal. I would personally probably build a Jekyll site for
> docs, so the curies should be able to reference remote URLs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gizra/restful/issues/232#issuecomment-61642393.

## 

Michal Minecki
DevOps Track Lead | Drupalcon Austin 2014
Director of Technology | Four Kitchens
  | mike@fourkitchens.com
  | +1 512 870 8441 (direct)
  | +1 562 551 8775 (cell)

Four Kitchens:  We make BIG websites
  | http://www.fourkitchens.com
  | +1 512 454 6659

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
