### ISSUE TITLE
New entity reference breaks taxonomy term handling, I think. 

### ISSUE THREAD

**Issue by mirzu** [RESTful-Drupal/restful#233]
500 Error: Unknown data property field_blog_categories_term_tree. 

For a public fields declaration: 

```
    $public_fields['categories'] = array(
      'property' => 'field_blog_categories_term_tree',
      'resource' => array(
        'categories' => 'categories',
      ),
    ); 
```

I think it's because we are sending $item_wrapper which is a wrapper for each taxonomy term to getValueFromResource() but treating like it's the outer entity wrapper when calling getTargetTypeFromEntityReference  $wrapper->{$property}

**Comment by amitaibu** [comment]
closed in favor of #234
