### ISSUE TITLE
If access check fails for one resource in a list the whole list is permission denied.

### ISSUE THREAD

**Issue by mirzu** [RESTful-Drupal/restful#239]
If one user on a site is blocked the whole list of users won't show up.

**Comment by e0ipso** [comment]
My bet is that we should do like we do with properties with access denied, remove them.

**Comment by amitaibu** [comment]
Yes, we should ignore them, unless specifically asked for that idea. 

So if `/api/articles` -- just skip the unaccessible entity (btw, this means that the `count` property would be wrong).

But if `/api/articles?id=1,2,3` un ID 3 is un-acecssible, we should throw an error.

**Comment by amitaibu** [comment]
@mirzu care to create a PR :)

**Comment by e0ipso** [comment]
Closed in favor of https://github.com/Gizra/restful/pull/242
