### ISSUE TITLE
Documentation and admin screen needed for allowing file uploads

### ISSUE THREAD

**Issue by BurningDog** [RESTful-Drupal/restful#248]
File uploads are only allowed if the drupal variable `restful_file_upload` is set to TRUE. While this is documented in the restful_angular_example README it's not mentioned elsewhere. I think there should be an admin screen for setting this variable and perhaps documenting this in the main README.

Yes?

**Comment by amitaibu** [comment]
Yes, we are planning that. Care to create the PR? :)

**Comment by amitaibu** [comment]
Closing n favor of #252. @BurningDog #252 is currently still WIP -- would you like to take it from here?
