### ISSUE TITLE
Ability to declare a default sort

### ISSUE THREAD

**Issue by raphaeltraviss** [RESTful-Drupal/restful#250]
Currently, we can view sorted results via my.restful.tld/endpoint?sort=somefield.

It would be nice if we could declare this in restful endpoint plugin definition, similar to publicFieldsInfo(), something like:

``` php
class MyClass extends \RestfulEntityBase {
  public function publicFieldsInfo() {
  // ...
  }

  public function sortFieldsInfo() {
    return array(
       '-id',
       'label'
    );
  }
// ...
}
```

Then perhaps RestfulDataProviderEFQ->getQueryForList() could check for and apply these values if there is no sort in the requested URL?

**Comment by amitaibu** [comment]
You mean you would like to define a _default_ sort?

**Comment by raphaeltraviss** [comment]
Yeah; for example: if an endpoint /myresource always needs to be sorted by the 'name' property, you would need to append ?sort=name to every GET request.  It would be nice to simply do a GET /myresource, and have the default sort be something of your choosing, rather than the entity id.  You could always override this by passing in ?sort=name in the request.

Maybe we could do something similar for ?field=xyz filters, too?

**Comment by amitaibu** [comment]
> Maybe we could do something similar for ?field=xyz filters, too?

Yes, exactly my thoughts.
I think we can have a `getDefaultSorts()` and `getDefaultsFilters()` that you will be able to override. @rfx1007 sounds like a great thing for you to work on ;)

**Comment by raphaeltraviss** [comment]
ok, let's give this a try: :sparkles: [pull request](https://github.com/Gizra/restful/pull/251) :sparkles:

Also, another thing I noticed is that a 'field filter' is different than a 'field limiter'--it tripped me up at first.  What I actually wanted were field limiters.

**Comment by raphaeltraviss** [comment]
Pull request merged.
