### ISSUE TITLE
Add a recipe book page to the github wiki

### ISSUE THREAD

**Issue by eethann** [RESTful-Drupal/restful#262]
We recently implemented a variation on URL paths using restful and have what could be a useful recipe to share with the community. I've forked the project and created a [recipes wiki page](https://github.com/eethann/restful/wiki/Recipes-for-Using-restful). 

I can't submit a PR for that page, so am using this issue instead. There's some documentation on [merging wiki pages via git](http://roman-ivanov.blogspot.com/2013/11/how-to-merge-github-wiki-changes-from.html) (must be project admin).

Also welcome thoughts on the approach in those docs, of course. :)

**Comment by e0ipso** [comment]
I'd love to see those in a book page in the Drupal.org documentation somewhere.

Thank you for that great recipe!

**Comment by eethann** [comment]
Sure! Is there an existing D.o docs section for restful?

**Comment by e0ipso** [comment]
There is one now! :-D

https://www.drupal.org/node/2380679

Thanks again!

**Comment by amitaibu** [comment]
@eethann thanks! I've updated a bit the code in the doc.

**Comment by e0ipso** [comment]
@eethann feel free to create child pages to that d.o documentation page when you have time to work on this.

Thanks again for your contribution!

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
