### ISSUE TITLE
Performance comparisons

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#272]
I'd like to benchmark the RESTful module and compare it against the popular: _Services_ and _RestWS_. After that I'd like to add in different render cache strategies into RESTful.

@amitaibu would you help me to describe a meaningful scenario?

**Comment by e0ipso** [comment]
# Setup No Auth.

After installing a default drupal installation I generate 500 random articles using devel_generate. I have Dupal's page cache enabled and using `'VarnishCache'` as the cache backend. Every other cache is using `'MemCacheDrupal'`, that includes entity cache. No authentication method is used for any of the modules.

For all testing purposes, cache is considered warm.

## Scenario 1. Index.

This test aims to check the performance of a list of articles. 2 tests are performed:
- Outputting 300 articles.
- Outputting 50 articles.

[Results](https://dl.dropboxusercontent.com/u/1251575/rest-performance/index.log)

## Scenario 2. GET.

This test aims to check the performance of an entity get.

# Setup No Auth. Varnish by-pass

After installing a default drupal installation I generate 500 random articles using devel_generate. I have Dupal's page cache enabled and using `'VarnishCache'` as the cache backend. Every other cache is using `'MemCacheDrupal'`, that includes entity cache. No authentication method is used for any of the modules. Varnish is bypassed by making all the requests to the port 8080.

For all testing purposes, cache is considered warm.

## Scenario 1. Index.

This test aims to check the performance of a list of articles. 2 tests are performed:
- Outputting 300 articles.
- Outputting 50 articles.

## Scenario 2. GET.

This test aims to check the performance of an entity get.

**Comment by e0ipso** [comment]
As you can see with this setup No Auth (pretty reasonable) Services is kicking our ass in performance. I don't even consider analyzing restws since it is not using page cache (and therefore not hitting Varnish in this setup).

In the other setup No Auth with Varnish by-pass, restws is kicking ass. RESTful comes last. I don't know how interesting is this comparison. Thoughts?

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch the `results` links seems to be broken.
Also, would be cool if you could add the script you used to perform the test

**Comment by nkgokul** [comment]
There was a comparison already done here https://docs.google.com/presentation/d/1nlVNMqE14zf9mO-3r_EG5VvHMKtPp8nuSA7vFHKCYSU/edit#slide=id.g4afb83e11_015

The tests might be old but probably we could use them to show the progress restful has made if any :)

**Comment by e0ipso** [comment]
Hi @nkgokul, thanks for bringing that up! I was already aware of that comparison. However I'm not sure how interesting it is in a **real world scenario** where most of the performance is achived via caching techniques.

So my question was more: «if I were to put an API in production for a heavy traffic website, would the RESTful module compare to the existing solutions?»

From my findings, and and after writing [this PR](https://github.com/RESTful-Drupal/restful/pull/274) –which went in for 7.x-1.0-rc2–, RESTful is not the slowest one as that presentation suggests. That being said, if you compare without any caching on the RESTful module is slower because of all the entity checks and field checks. Those checks are necessary for security, reliability and flexibility.

All in all I am confident that there is no real performance disadvantage (in some scenarios RESTful is the fastest one by far) in using the RESTful module.

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
