### ISSUE TITLE
\RestfulAuthenticationManager::getAccount isn't performent

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#276]
I'm also seeing getAccount getting a big hit, on a clean Drupal with 100 articles, and an auth user doing `api/v1.5/articles`

![xhgui__hierarchical_profiler_report_and_message_subscribe_email test_-_vlad_-___applications_mamp_htdocs_vlad_](https://cloud.githubusercontent.com/assets/125707/5231416/a992b5de-7740-11e4-8c22-1aca4c1ae03d.jpg)

`\RestfulAuthenticationManager::getAccount` us supposed to return the account from $this->account, but I think it doesn't.

![xhgui__hierarchical_profiler_report-2](https://cloud.githubusercontent.com/assets/125707/5231459/4d4e52e6-7741-11e4-9264-532e7d712c0e.jpg)

**Comment by e0ipso** [comment]
BTW I'm working on the cache ID generation performance.

**Comment by amitaibu** [comment]
Closing, as indeed getAccount() isn't very slow -- unsurprisingly it's the 50 entities loading that takes time.
