### ISSUE TITLE
Notice on \RestfulFormatterHalJson::moveReferencesToEmbeds

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#282]
I've seen a notice when I have my reference as an ID only:

``` php
  if (field_info_instance($this->getEntityType(), OG_AUDIENCE_FIELD, $this->getBundle())) {
      $public_fields['company'] = array(
        'property' => OG_AUDIENCE_FIELD,
        'resource' => array(
          'company' => array(
            'name' => 'companies',
            'full_view' => FALSE,
          )
        ),
      );
    }
```

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch @mirzu - If the referenced resource is shown only as ID, should we indeed move it to the `_embedded` - or should we keep it in place?

**Comment by e0ipso** [comment]
I would say that an id is just a regular field, that is not the result of calling another resource. Therefore I would leave it in place, out of `_embedded`.

**Comment by amitaibu** [comment]
Yeah, that was my same line of thought. Thanks.

‫ב-1 בדצמ 2014, בשעה 08:37, ‏Mateu Aguiló Bosch notifications@github.com כתב/ה:‬

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
