### ISSUE TITLE
Disable cache by default

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#291]
#285 wasn't such a good idea -- because now all my developers are confused why aren't their changes picked up. So I think we should go ahead an revert that PR.

**Comment by e0ipso** [comment]
Hmm, I wonder if that may be fixed with a documentation patch then.

**Comment by e0ipso** [comment]
Also, that must mean that the invalidation code is not working properly.

**Comment by amitaibu** [comment]
> Hmm, I wonder if that may be fixed with a documentation patch then.

I prefer to do it other way around -- in the docs tell the dev to enable cache. It took me few minutes myself to realize it's a caching "problem". 

> Also, that must mean that the invalidation code is not working properly.

I don't think so, because I don't expect the system to know the anything changed in getPublicFields or in one of the callbacks.

**Comment by e0ipso** [comment]
> I don't think so, because I don't expect the system to know the anything changed in getPublicFields or in one of the callbacks.

Gotcha!

:+1:
