### ISSUE TITLE
Add default field limiters

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#298]
This comes off https://github.com/Gizra/restful/pull/294#issuecomment-65674900.

**Comment by amitaibu** [comment]
We already have something in the system -- you can _limit_ the output fields by setting `?fields` - so I'm not sure we need anything else here.

**Comment by e0ipso** [comment]
So the idea is to be able to specify which fields to show _by default_. Right now the default is showing all fields, and that default is not configurable.

I'm not sure how useful is this feature, though…

**Comment by amitaibu** [comment]
> Right now the default is showing all fields

unless you add `access callback` on each public field - where you can have your own logic. So I think this issue can be closed.
