### ISSUE TITLE
Structure documentation

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#299]
The current docs are a **BIG** single page. Maybe we could have a `/docs` folder with the different sections.

The idea would be simplifying the README.md by moving pieces of documentation to its own file and link to those from the README.md.

**Comment by e0ipso** [comment]
@rfx1007 you can also take this one, if this is something you'd like to work on.

**Comment by raphaeltraviss** [comment]
Sure, I'll take this one.

**Comment by e0ipso** [comment]
@rfx1007 great!

**Comment by raphaeltraviss** [comment]
See what you think of this: https://github.com/RESTful-Drupal/restful/pull/324

**Comment by e0ipso** [comment]
Closed in favor of #324
