### ISSUE TITLE
Use xautoload to use namespaces.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#306]
I know we've talked about this before, but we have **a lot** of classes now. We are already doing namespaces when using names like `RestfulEntityBaseNode`, and I think that for sake of clarity that should be `Drupal\restful\Entity\Node`.

**Comment by amitaibu** [comment]
I'm still feeling pretty strongly against it - and as you have noticed, it's pretty rare for me to "feel strongly" about stuff ;)

Apart of the directory is there a big win here? My biggest concern is that it will keep users from using it. I know that if I would be presented with such a dependency, I would personally hesitate if not completely skip using it.

**Comment by e0ipso** [comment]
It's OK, if you feel strongly about this then let's not do it.
