### ISSUE TITLE
Allow RestfulDataProviderDbQuery to use a table with a multi-column unique key

### ISSUE THREAD

**Issue by rbran100** [RESTful-Drupal/restful#307]
Allow for data tables that do not have a single value key to be used.

Example: 
Table with unique key:  type + id

``` php
$this->idColumn = array('type', 'id');
```

The key for the item becomes the concatenation of the columns.

``` php
$result = $handler->get("type1::55");
```

**Comment by e0ipso** [comment]
Closed in favor of the PR #308
