### ISSUE TITLE
Should Entity Cache Expiration call non-Entity handlers?

### ISSUE THREAD

**Issue by rbran100** [RESTful-Drupal/restful#309]
Looking here: https://github.com/Gizra/restful/blob/7.x-1.x/includes/RestfulManager.php#L288

It seems like it should only be calling invalidate on handlers that extend RestfulEntityBaseNode? 

Maybe I am missing how this works?

**Comment by e0ipso** [comment]
Basically you can call `\RestfulManager::invalidateEntityCache($cid)` and it will load all handlers that implement a `cacheInvalidate` method to execute it on the `$cid`.

This process is data provider agnostic.

The implementation resides in `\Restfulbase#cacheInvalidate($cid)`, and gets inherited by all data providers.
