### ISSUE TITLE
URL Alias 

### ISSUE THREAD

**Issue by t14** [RESTful-Drupal/restful#313]
Is it possible to make a Get request using the URL alias of an article (or other node type)?

**Comment by e0ipso** [comment]
GET requests for entities rely on entity ids.

That being said you can find your node id from the url alias in Drupal by doing something _dirty_ like:

``` php
$source_path = drupal_lookup_path('source', $url_alias);
$nid = substr($source_path, strpos($source_path, 'node/'));
```

**Comment by e0ipso** [comment]
Did that work?

**Comment by t14** [comment]
Thanks for your reply I have not had a chance to try this out yet. But it makes sense in theroy.
Where about (e.g in this modules example module) do you think your example above could be implemented?
What do you think about using a hook_menu_alter to achieve this.

Great module by the way, really like it

**Comment by markdorison** [comment]
@mateu-aguilo-bosch Your code makes sense but how would one integrate this with Restful to allow for filtering via a URL request?

**Comment by e0ipso** [comment]
@markdorison you would certainly need to override some of the resource methods inside the `\RestfulBase` or `\RestfulEntityBase` class.

Essentially if you need to load (or filter) by alias, you override the appropriate method and calculate the entity ID. The you just return a call to the parent.

Maybe something like:

``` php
class MyResource extends \RestfulEntityBase {
  …
  public function viewEntity($alias) {
    $source_path = drupal_lookup_path('source', $url_alias);
    $nid = substr($source_path, strpos($source_path, 'node/'));
    return parent::viewEntity($nid);
  }
  …
}
```

**Comment by e0ipso** [comment]
@markdorison I would appreciate, if you succeed at this, that you took the time to post a more detailed example/recipe in the recipes section: https://www.drupal.org/node/2380679

**Comment by iStryker** [comment]
I had to do this for one project I worked on.   

``` php
class RestfulPublicationArticlesResource extends RestfulEntityBaseNode {
 /**
   * Overrides RestfulEntityBaseNode::publicFieldsInfo().
   */
  public function publicFieldsInfo() {
    $public_fields = parent::publicFieldsInfo();
    $public_fields['alias'] = array(
      'callback' => array($this, 'getEntityAlias'),
    );
  }
  /**
   * Get entity's alias.
   *
   * @param \EntityDrupalWrapper $wrapper
   *   The wrapped entity.
   *
   * @return string
   *   The alias URL.
   */
  protected function getEntityAlias(\EntityDrupalWrapper $wrapper) {
    $values = $wrapper->value();
    return $values->path['alias'];
  }

  /**
   * Overrides parent filter the query for list.
   *
   * @param \entityfieldquery $query
   *   the query object.
   *
   * @throws \restfulbadrequestexception
   *
   * @see \restfulentitybase::getqueryforlist
   */
  protected function queryforlistfilter(\entityfieldquery $query) {
    foreach ($this->parserequestforlistfilter() as $filter) {
      // Map alias to the node id.
      if ($filter['public_field'] == 'alias') {
        $node_path = explode('/', drupal_get_normal_path($filter['value'][0]));
        $nid = $node_path[1];
        $query->entityCondition('entity_id', $nid, $filter['operator'][0]);
        // Unset the alias filter to prevent problems when we call parent function.
        unset($this->request['filter']['alias']);
      }
    }
    parent::queryforlistfilter($query);
  }
}
```

**Comment by iStryker** [comment]
This is a little off topic, but probably relate (and maybe if you create example recipe you will include this as well).

Since the 'self' links points to api self link, and not the node inself,  on the same project we added the follow.

``` php
  /**
   * Overrides RestfulEntityBaseNode::publicFieldsInfo().
   */
  public function publicFieldsInfo() {
    $public_fields = parent::publicFieldsInfo();
    $public_fields['source'] = array(
      'callback' => array($this, 'getEntitySource'),
    );

  /**
   * Get entity's source.
   *
   * @param \EntityDrupalWrapper $wrapper
   *   The wrapped entity.
   *
   * @return string
   *   The source URL.
   */
  protected function getEntitySource(\EntityDrupalWrapper $wrapper) {
    $values = $wrapper->value();
    return $values->path['source'];
  }
```

We did not need a filter on the source.  I do not think many would either.  Just the alias.

**Our reason for having a filter on the alias:**
Your app has the current alias path, and wants to get all of the information about that node.  It does not know the id of the node, so it must query the api using the full alias.

**Comment by e0ipso** [comment]
Thanks again @iStryker!

**Comment by ness-EE** [comment]
In RESTful 2.x @iStryker 's solution doesn't seem to work: I get:

> Argument 1 passed to...  must be an instance of EntityDrupalWrapper, instance of Drupal\restful\Plugin\resource\DataInterpreter\DataInterpreterEMW given

**Comment by e0ipso** [comment]
@ness-EE I'm not sure if you are asking a question, reporting a bug, …

Please see [How to Ask Useful Questions](https://joshkaufman.net/how-to-ask-useful-questions/). Also, there's a lot of documentation about the module to check.

**Comment by ness-EE** [comment]
Sure, adding to the original question:

> Is it possible to make a Get request using the URL alias of an article (or other node type)?

I used the method 'getEntityAlias' from the post by @iStryker to good effect whilst using RESTful 1.x

Whilst using version 2.x of RESTful this method no longer works. I receive the error:

> Argument 1 passed to Drupal\fp_headless\Plugin\resource\node\pages\v1\Pages__1_0::getEntityAlias() must be an instance of EntityDrupalWrapper, instance of Drupal\restful\Plugin\resource\DataInterpreter\DataInterpreterEMW given in Drupal\fp_headless\Plugin\resource\node\pages\v1\Pages__1_0->getEntityAlias()

... so the original question stands for version 2.x - Is it possible to make a Get request using the URL alias of an article (or other node type)?

_EDIT_
Wow I'm really impressed with the documentation for version 2.x - everything I need to know about this topic was found here - https://github.com/RESTful-Drupal/restful/wiki/Look-up-a-URL-alias-mapping-with-DataProviderDbQuery

**Comment by GaxZE** [comment]
Going to resurrect this one slightly. I have a similar requirement to @iStryker with regard to querying a resource purely on a url without knowing the nid.

I'm using 2.5(can't upgrade further as PHP version is 5.4) and I'm looking to query a resource on a path url. 

My resource currently outputs the nodes full path via the [url](https://api.drupal.org/api/function/url/7) function;

``` php
$public_fields['path'] = array(
  'property' => 'nid',
  'process_callbacks' => array('\Drupal\api\Plugin\resource\test\v1\test__1_0::getPathAlias'),
);
```

Sadly though I'm unable to work out how/why I can't simply use a `filter[path]=http://www.website.com/alias/of/node.` - I feel this would be the simpler solution than below;

I did try https://github.com/RESTful-Drupal/restful/wiki/Look-up-a-URL-alias-mapping-with-DataProviderDbQuery and it's worked for the large part but there are issues when the node in question has the url path containing the language example: `http://www.website.com/fr/alias/of/node.` 

Any tips or pointers to something I'm missing would be great.
