### ISSUE TITLE
Inject language to \RestfulEntityBase

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#320]
See https://github.com/RESTful-Drupal/restful/pull/318/files#r21825629

**Comment by alexweber** [comment]
Taking a stab...

What kind of parameter did you have in mind for the injected language argument/property?  Simple string or the full language object?

**Comment by alexweber** [comment]
oops, didn't realize #321 already has this issue covered! :)

**Comment by e0ipso** [comment]
Ahhh, sorry @alexweber we didn't close this one first.
