### ISSUE TITLE
\RestfulAuthenticationBasic::authenticate shouldn't always trigger flood_register_event

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#327]
This was triggered when we called multiple times resources via API.

Basically, the solution should probably be that if called via API, we shouldn't try to authenticate using the plugins, and just use the global $user (as we already do, but probably to late in the process)

**Comment by amitaibu** [comment]
or a better approach would be to check if indeed some info was sent to base auth, and flood_register_event() only then.

I'll be working on a PR.

**Comment by e0ipso** [comment]
Closed in an issue purge. Please, feel free to reopen if necessary.
