### ISSUE TITLE
Wrong count with custom filter.

### ISSUE THREAD

**Issue by nedSaf** [RESTful-Drupal/restful#339]
I added a custom field filter to a resource with `getQueryForList`,
The count of the resource is not changing even when applying the filter (which is filtering correctly):

![localhost_capacity4more_www_api_activity_stream](https://cloud.githubusercontent.com/assets/7369740/5539138/771dc366-8ac6-11e4-8e10-16e2ae3ad9d3.png)

![localhost_capacity4more_www_api_activity_stream_group_24](https://cloud.githubusercontent.com/assets/7369740/5539151/94b454bc-8ac6-11e4-9c55-b0075c7ef5c4.png)

**Comment by amitaibu** [comment]
@nader77 can you look at it in your contribution hour please

**Comment by e0ipso** [comment]
@nader77 if you override `getQueryForList` you should also override `getTotalCount`.

Maybe a better idea would be to provide a filter query param? https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/docs/api_drupal.md#filter

**Comment by amitaibu** [comment]
@nader77 The problem seems to be somewhere in `\RestfulDataProviderEFQ::getQueryCount`. We try to filter the values (`$this->queryForListFilter($query);`) but apparently it isn't working as expected.

**Comment by nedSaf** [comment]
Using a filter query param.
