### ISSUE TITLE
Add support for commerce_product_reference field

### ISSUE THREAD

**Issue by xuxucode** [RESTful-Drupal/restful#347]
I am using Drupal Commerce module, when expose field_product property on Product display node type, an exception found: **Field field_product is not an entity reference or taxonomy reference field**, is there a better way to handle commerce_product_reference field?

**Comment by amitaibu** [comment]
We can probably add integration with commerce. Care to create a PR to extend [getTargetTypeFromEntityReference](https://github.com/RESTful-Drupal/restful/blob/ce9e0300c17b0aae7ee0e005ab44f829bc0667c2/plugins/restful/RestfulEntityBase.php#L441)

**Comment by xuxucode** [comment]
PR https://github.com/RESTful-Drupal/restful/pull/449
