### ISSUE TITLE
Is RESTful a good choice for native mobile apps?

### ISSUE THREAD

**Issue by xuxucode** [RESTful-Drupal/restful#348]
Many places mentioned "AngularJs", “web application”,  I am curious 
1. Whether RESTful  right choice for creating native mobile app compared to restws? 
2. if HAL+JSON suitable for native app client

**Comment by e0ipso** [comment]
> Whether RESTful right choice for creating native mobile app

It's the best choice, because of it's flexibility.

> if HAL+JSON suitable for native app client

Not sure I understand the question. The RESTful module **can** output your data using HAL+JSON, but that is only one of the supported output formats.

**Comment by xuxucode** [comment]
Got it, thank your very much.
