### ISSUE TITLE
Can't autocomplete users due to a missing bundle key in the user schema

### ISSUE THREAD

**Issue by RoySegall** [RESTful-Drupal/restful#351]
I have user named john. When i try to get results for users using the autocomplete in the get request i'm not getting any results. The path is: `api/v1.0/users?autocomplete[string]=joh`. I also have blog that contains the word john and when i try to autocomplete blog through `api/v1.0/blog?autocomplete[string]=joh` i get results.

The problem come from [here](https://github.com/RESTful-Drupal/restful/blob/ce9e0300c17b0aae7ee0e005ab44f829bc0667c2/plugins/restful/RestfulEntityBase.php#L223-L225). The user entity don't have a key for bundle in the users schema.

**Comment by amitaibu** [comment]
@mateu-aguilo-bosch I think you had some plans for decoupling auto-complete from the RestfulEntityBase, maybe it's a good time to tackle this as-well? Can you share what you had in mind?

**Comment by e0ipso** [comment]
It is possible that the autocomplete functionality can be decoupled. I don't have anything done yet, but I can look at it.

I am thinking about using a strategy pattern when interacting with different behaviours and a decorator pattern to extrapolate functionalities like render caching, rate limits, …

I think that we should contain the different URL modifiers under an interface and find a common way to interact with those too.

As you can see there are many changes. I would rather see this version fly for a while and then start to think about a version 7.x-2.x and _rewrite_ the code when the requirements have stabilized.

@amitaibu what do you think?
