### ISSUE TITLE
Returning specific fields for a Quiz node

### ISSUE THREAD

**Issue by BurningDog** [RESTful-Drupal/restful#353]
I'm working with [Quiz](http://drupal.org/project/quiz) module nodes which are a little...different. Each Quiz can have an availability time period set (i.e. "Allow users to take this quiz between the 1st and 31st of January 2015"). There are 3 places in the node object where this data is stored: 
- `$node->quiz_always`, a boolean, which stores if the quiz is always available or not.
- `$node->quiz_open` is the timestamp of the date the quiz become available.
- `$node->quiz_close` is the timestamp of the date the quiz stops being available. 

I want to expose these fields via restful. However, these are not content fields in the sense of a field which shows on the "Manage Fields" page of the Quiz content type, and so the following code gives the error "Unknown data property quiz_open.":

``` php
    $public_fields['quiz_open'] = array(
      'property' => 'quiz_open',
    );
```

All 3 fields are inserted into the node object by `quiz_load()` and so I'd expect to have access to them in `$this` in the `publicFieldsInfo()` function, but I don't.

Is there a way I can get access to these fields in `publicFieldsInfo()` or do I have to do a process callback, and inside the callback function do a full node_load() and then return what I need?

**Comment by amitaibu** [comment]
You need the EntityMetadataWrapper to know the properties. For that you can use `hook_entity_property_info`

**Comment by BurningDog** [comment]
I can only use `hook_entity_property_info` if the Quiz module implements `hook_entity_info` - which it doesn't. The properties are accessible through a `node_load` so I ended up with this workaround:

``` php
    // What dates is it available?
    $public_fields['available'] = array(
      'property' => 'title',
      'process_callbacks' => array(
        array($this, 'quizAvailability'),
      ),
    );
```

``` php
  protected function quizAvailability() {
    $node = node_load($this->path);
    $return = array(
      'quiz_always' => $node->quiz_always,
      'quiz_open' => format_date($node->quiz_open, 'custom', 'd F Y'),
      'quiz_close' => format_date($node->quiz_open, 'custom', 'd F Y')
    );
    return $return;
  }
}
```

This gives me the data I need but feels hacky - is there a better way?

**Comment by amitaibu** [comment]
> I can only use hook_entity_property_info if the Quiz module implements hook_entity_info

I'm not sure. If a quiz is a node, you should be able to attach EMW properties to it. Those properties can be "computed" (i.e. have no column in the DB)

**Comment by e0ipso** [comment]
@BurningDog you probably want to use a `callback` instead of a `property`.

``` php
// What dates is it available?
    $public_fields['available'] = array(
      'callback' => array($this, 'quizAvailability'),
    );
```

**Comment by BurningDog** [comment]
@mateu-aguilo-bosch thanks, that callback is much cleaner :)

@amitaibu yes, Quiz is a node.

> you should be able to attach EMW properties to it. Those properties can be "computed" (i.e. have no column in the DB)

How/where would I attach EMW properties to the node?

The properties _do_ have columns in the DB already. I expected that `$this` in the context of the class I'm working in (`RestfulQuizzesResource`) would include everything which `node_load()` gives, but it doesn't.

**Comment by BurningDog** [comment]
Ok wait - I've come across exactly the same question but in a different context. I want to return the picture associate with a user, so I've enabled my own user resource and can return a user at `api/v1.0/users/1`

The picture property isn't returned by default. Since it's listed as a property at `admin/config/people/accounts/fields` I expected I could do the following:

``` php
    $public_fields['picture'] = array(
      'property' => 'picture',
    );
```

However, this gives the error "Unknown data property picture."

So I've worked around that by doing:

``` php
    $public_fields['picture'] = array(
      'callback' => array($this, 'userPicture')
    );

...

  /**
   * Process callback, returns a user's picture
   *
   * @return array
   *   A file array
   */
  protected function userPicture() {
    $account = $this->getAuthenticationManager()->getAccount();
    $picture = $account->picture;
    $picture->uri = file_create_url($picture->uri);
    return $picture;
  }
```

Is this correct/the best way of doing this?

**Comment by BurningDog** [comment]
So `$this->getAuthenticationManager()->getAccount();` gets the currently logged in user, not the specific user we want. So I ended up with this hack:

``` php
  protected function userPicture() {
    if (empty($this->path)) {
      return;
    }
    $uid = $this->path;
    $user = user_load($uid);
    if (empty($user->picture)) {
      return;
    }
    $picture = $user->picture;
    $picture->uri = file_create_url($picture->uri);
    return $picture;
  }
```

**Comment by amitaibu** [comment]
`However, this gives the error "Unknown data property picture."`

Indeed, because EntityMetadataWrapper doesn't know `$wrapper->picture->value()`, for that you could use the `hook_entity_property_info`, in order to allow `set` as-well. I would argue that this is the proper way, as it gives this option not only to RESTful, but for your entire app.

> So $this->getAuthenticationManager()->getAccount(); gets the currently logged in user, not the specific user we want. So I ended up with this hack:

You could probably override `entityView()`, no?

**Comment by bryangruneberg** [comment]
@BurningDog and I came right using hook_entity_property_info_alter, and added the fields that the quiz module itself didn't originally expose.

``` php
/**
 * Implementation of hook_entity_property_info_alter()
 *
 * Adds the quiz_properties to the entity framework, mainly so the API works
 */
function oup_entity_property_info_alter(&$info) {

  $properties = &$info['node']['bundles']['quiz']['properties'];

  $properties['quiz_open'] = array(
    'label' => t("Quiz Open"), 
    'description' => t("When the quiz opens"), 
    'type' => 'integer', 
    'schema field' => 'quiz_open',
  );

  $properties['quiz_close'] = array(
    'label' => t("Quiz Close"), 
    'description' => t("When the quiz closes"), 
    'type' => 'integer', 
    'schema field' => 'quiz_close',
  );

  $properties['quiz_always'] = array(
    'label' => t("Quiz Always"), 
    'description' => t("Quiz always open"), 
    'type' => 'integer', 
    'schema field' => 'quiz_always',
  );

}

```

**Comment by amitaibu** [comment]
This looks like the right solution.

**Comment by xuxucode** [comment]
@BurningDog 
To return picture, see [EntityMetadataWrapper is missing user properties for pictures, passwords, timezones and signatures](https://www.drupal.org/node/2224645) and apply the latest patch. However, you need to convert the picture file object to an array:

``` php
  /**
   * Overrides RestfulEntityBaseNode::publicFieldsInfo().
   */
  public function publicFieldsInfo() {
    $public_fields = parent::publicFieldsInfo();

    $public_fields['picture'] = array(
      'property' => 'picture',
      'process_callbacks' => array(
        array(array($this, 'getImageUris'), array(array('thumbnail', 'medium', 'large'))),
        array($this, 'imageProcess'),
      ),
      'image_styles' => array('thumbnail', 'medium', 'large'),
    );

    return $public_fields;
  }

  /**
   * Overrides RestfulEntityBase::getValueFromProperty().
   * Convert picture File object to Array.
   */
  public function getValueFromProperty(\EntityMetadataWrapper $wrapper, \EntityMetadataWrapper $sub_wrapper, array $info, $public_field_name) {
    $value = parent::getValueFromProperty($wrapper, $sub_wrapper, $info, $public_field_name);
    if (strpos($info['property'], 'picture') !== FALSE) {
      return (array)$value;
    }
    return $value;
  }
```
