### ISSUE TITLE
User resource not appearing in node JSON

### ISSUE THREAD

**Issue by adaddinsane** [RESTful-Drupal/restful#355]
I am getting no data returned when using this code, even from `restful_example`:

``` php
      'user' => array(
        'property' => 'author',
        'resource' => array(
          // The bundle of the entity.
          'user' => array(
            // The name of the resource to map to.
            'name' => 'users',
            // Determines if the entire resource should appear, or only the ID.
            'full_view' => TRUE,
          ),
        ),
```

Switching to `'full_view' => FALSE` makes no difference.

Similarly I'm not getting anything with an `entityreference` field where I've defined a resource for the referenced entity (the resource works on its own). Accessing the user resource directly also works.

I've tried lots of different approaches and read the documentation every which way.  I've tried creating content with other users (just in case).

If I remove the 'resource' part I get the entire user (or other entity) returned as expected.

If I use:

``` php
        'resource' => array(
          'users' => 'users',
        ),
```

I get `user: null` (no other variant of this generates anything).

There are no errors or other messages in the error log.

I was originally using the standard release but then switched to the dev release but it made no difference.

I'm feeling pretty stupid (even though I've been a pro Drupal dev for 8 years) so any guidance would be appreciated. (I could use a callback but that would be defeating the object.)

**Comment by BurningDog** [comment]
Have you made sure that the drupal variable `restful_enable_users_resource` is set to `TRUE`? This can also be done in drupal at `admin/config/services/restful` and checking the "User resource" checkbox in the Advanced section.

**Comment by adaddinsane** [comment]
Hi Roger,

Thanks for that. Yes, it's enabled.

I'm only using the 'user' resource as an example. I can't get results with
any 'embedded' resource using this technique.

On 8 January 2015 at 12:34, Roger Saner notifications@github.com wrote:

> Have you made sure that the drupal variable restful_enable_users_resource
> is set to TRUE? This can also be done in drupal at
> admin/config/services/restful and checking the "User resource" checkbox
> in the Advanced section.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RESTful-Drupal/restful/issues/355#issuecomment-69173607
> .

## 

Steve Turnbull

**Comment by adaddinsane** [comment]
Okay I've tracked it down to HAL:JSON.

If I use only JSON the user resource appears (in fact I have several sub-resources, and a sub-sub-resource, which all appear correctly).

The problem is happening in `RestfulFormatterHalJson::moveReferencesToEmbeds()`. I'm not entirely sure what's going on here (because I've only skimmed the HAL documentation, and the code) but it's failing to embed the "other resources" and still deleting them.

**Comment by adaddinsane** [comment]
As I don't understand the ins-and-outs of this, I don't really know exactly what it does what it does (I do understand that embedded resources have to go to the '_embedded' section of a HAL:JSON resource) but this is the problem:

``` php
  protected function moveReferencesToEmbeds(array &$output, array &$row, $public_field, $public_field_name) {
    $value_metadata = $this->handler->getValueMetadata($row['id'], $public_field_name);
    foreach ($row[$public_field_name] as $index => $resource_row) {
      if (empty($value_metadata[$index])) {
        // No metadata.
        continue;
      }
      $metadata = $value_metadata[$index];
```

The `(empty($value_metadata[$index]))` condition always fails.

What comes back from `$this->handler->getValueMetadata()` is a two-level array with numeric top-level keys. But `$index` is always a string, so it'll never work.

I don't know what the fix is because, as I say, I'm not sure what it's trying to do in here.

**Comment by adaddinsane** [comment]
I've forked the repo and I'm investigating. I did a temp fix which established that I was right about the location of the problem but a proper resolution looks more complex. I've also studied the HAL:JSON documentation.

**Comment by e0ipso** [comment]
Quick question. Are your embedded entities present in the _embed key? Thats
the normal behavior

**Comment by adaddinsane** [comment]
No, they are completely missing using the original code.

Further investigation revealed the process works fine for HAL:XML, so the problem is tied to the existence of curies in the plugin, which causes the `RestfulFormatterHalJson::moveReferencesToEmbeds()` method to be called.

That method is broken (as described), when my temp fix is put in I can get the resources but they are all at the top-level of `_embedded`, with no nesting. Here's the hacky fix:

``` php
      if (empty($value_metadata[0][$index])) {
        // No metadata.
        continue;
      }
      $metadata = $value_metadata[0][$index];
```

and

``` php
      $curies_resource = $this->withCurie($resource_name);
      $preparedRow = $this->prepareRow($row[$public_field_name], $output);
      $output['_embedded'][$curies_resource][] = $preparedRow;
```

The problem is that the `$output` variable is "flat" and not treated as nested even though the array structure is nested, the fix may be pretty easy (passing `$output['resourcename']` or something like that).

EDIT: Not that simple unfortunately.

**Comment by adaddinsane** [comment]
Ha! Got it. It was relatively easy.

**Comment by adaddinsane** [comment]
Here's the patch for the hal_json class...

``` patch
diff --git a/plugins/formatter/hal_json/RestfulFormatterHalJson.class.php b/plugins/formatter/hal_json/RestfulFormatterHalJson.class.php
index c7ee8cc..c6f66f8 100644
--- a/plugins/formatter/hal_json/RestfulFormatterHalJson.class.php
+++ b/plugins/formatter/hal_json/RestfulFormatterHalJson.class.php
@@ -25,14 +25,12 @@
     }
     // Here we get the data after calling the backend storage for the resources.

-    $curies_resource = $this->withCurie($this->handler->getResourceName());
-    $output = array();
-
     foreach ($data as &$row) {
-      $row = $this->prepareRow($row, $output);
+      $row = $this->prepareRow($row);
     }

-    $output[$curies_resource] = $data;
+    $curies_resource = $this->withCurie($this->handler->getResourceName());
+    $output = array($curies_resource => $data);

     if (!empty($this->handler)) {
       if (
@@ -126,19 +124,19 @@
    *
    * @param array $row
    *   A single row array.
-   * @param array $output
-   *   The output array, passed by reference.
    *
    * @return array
    *   The massaged data of a single row.
    */
-  public function prepareRow(array $row, array &$output) {
+  public function prepareRow(array $row) {
     $this->addHateoasRow($row);

     if (!$curie = $this->getCurie()) {
       // Skip if there is no curie defined.
       return $row;
     }
+
+    $embedded = array();

     foreach ($this->handler->getPublicFields() as $public_field_name => $public_field) {
       if (empty($public_field['resource'])) {
@@ -151,9 +149,11 @@
         continue;
       }

-      $output += array('_embedded' => array());
+      $this->moveReferencesToEmbeds($embedded, $row, $public_field, $public_field_name);
+    }

-      $this->moveReferencesToEmbeds($output, $row, $public_field, $public_field_name);
+    if (!empty($embedded)) {
+      $row['_embedded'] = $embedded;
     }

     return $row;
@@ -226,8 +226,7 @@
    * @param $public_field_name
    *   The name of the public field.
    */
-  protected function moveReferencesToEmbeds(array &$output, array &$row, $public_field, $public_field_name) {
+  protected function moveReferencesToEmbeds(array &$embedded, array &$row, $public_field, $public_field_name) {
     $value_metadata = $this->handler->getValueMetadata($row['id'], $public_field_name);
     foreach ($row[$public_field_name] as $index => $resource_row) {
       if (empty($value_metadata[0][$index])) {
@@ -256,8 +255,8 @@
       }

       $curies_resource = $this->withCurie($resource_name);
-      $preparedRow = $this->prepareRow($row[$public_field_name], $output);
-      $output['_embedded'][$curies_resource][] = $preparedRow;
+      $preparedRow = $this->prepareRow($row[$public_field_name]);
+      $embedded[$curies_resource][] = $preparedRow;
     }

     // Remove the original reference.
```

**Comment by e0ipso** [comment]
@adaddinsane maybe you can make a PR. That way CI will kick in. :)

**Comment by adaddinsane** [comment]
I tried but it didn't like it (something about passwords). And I was too
rushed to mess about.

On 9 January 2015 at 20:15, Mateu Aguiló Bosch notifications@github.com
wrote:

> @adaddinsane https://github.com/adaddinsane maybe you can make a PR.
> That way CI will kick in. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RESTful-Drupal/restful/issues/355#issuecomment-69392122
> .

## 

Steve Turnbull

**Comment by adaddinsane** [comment]
This solution is incomplete and still fails for entity references that have multiple values.

However I have solved that. I will try to do a PR but I'm not promising anything.

**Comment by e0ipso** [comment]
> I will try to do a PR but I'm not promising anything.

No need to make promises. Contributing is hard.

If you find the time to send a PR that'll be awesome. If not, then there's no problem. :blush:

**Comment by e0ipso** [comment]
Let's move the convesation to #422.
