### ISSUE TITLE
What is the current user?

### ISSUE THREAD

**Issue by BurningDog** [RESTful-Drupal/restful#357]
This seems like a silly question to me, but I can't figure out how to ask the API what uid I have.

`/api/v1.0/users` gives me a list of all users but doesn't show which one is me. I've read all of the documentation I can find and there's not more information about how to do this.

All I need to do is something which runs (and returns) the following somewhere:

``` php
$this->getAuthenticationManager()->getAccount();
```

I've looked at the `restful_example` module, specifically the 'get children' and 'get child' callback functions in `per_role_content__1_0.inc` which could probably be implemented in `users__1_0.inc` but I don't know how to do that or how that would be called.

I'm thinking of using a similar approach to `access_token__1_0.inc` and define something like `'menu_item' => variable_get('restful_hook_menu_base_path', 'api') . '/user',` which will just return the current user.

Or is there a really simple way to do this?

**Comment by BurningDog** [comment]
I'm now returning the current uid and user name at `/api/uid` by adding 2 files to the `plugins/restful/uid/1.0` folder. 

`uid__1_0.inc` contains:

``` php
<?php

$plugin = array(
  'label' => t('Current user id'),
  'resource' => 'uid',
  'name' => 'uid__1_0',
  'entity_type' => 'user',
  'bundle' => 'uid',
  'description' => t('Get the currently logged in user id.'),
  'class' => 'RestfulUid',
  'authentication_types' => array(
    'cookie',
    'basic_auth',
  ),
  // We will implement hook_menu() with custom settings.
  'menu_item' => variable_get('restful_hook_menu_base_path', 'api') . '/uid',
);
```

`RestfulUid.class.php` contains

``` php
<?php

/**
 * @file
 * Contains RestfulUid.
 */

class RestfulUid extends \RestfulEntityBase {
  /**
   * Overrides \RestfulBase::controllersInfo().
   */
  public static function controllersInfo() {
    return array(
      '' => array(
        // Get or create a new token.
        \RestfulInterface::GET => 'returnUid',
      ),
    );
  }

  public function returnUid() {
    $account = $this->getAuthenticationManager()->getAccount();
    return array(
      'uid' => $account->uid,
      'name' => $account->name,
    );
  }
}
```

I'm sure there's a better way of doing this...

**Comment by amitaibu** [comment]
Hedley has such an example for `/api/me` - https://github.com/Gizra/generator-hedley/blob/master/app/templates/skeleton/modules/custom/skeleton_restful/plugins/restful/user/me/1.0/SkeletonMeResource.class.php
