### ISSUE TITLE
Have to do individual API calls per node because restful doesn't provide enough data

### ISSUE THREAD

**Issue by BurningDog** [RESTful-Drupal/restful#366]
As mentioned in https://github.com/RESTful-Drupal/restful/issues/353 I have multiple places where restful doesn't provide enough data in a "show all [x] entity nodes" API call. I can only find this data by doing a `node_load()` in a callback in `publicFieldsInfo()` inside my class which extends `RestfulEntityBaseNode`

To do the `node_load()` I need to know the node id. I can only get the node id from a specific call, like `api/v1.0/courses/123` where 123 is the node id. The only way I can see to get the node id is by using `$this->path` since I can't see anywhere else to get the node id. This means that I need to perform multiple API calls to get the data I need, first to `api/v1.0/courses` and then one API call per node. This can't be right!

What is the way to get the node id inside my class, which doesn't use `$this->path`?

I'm not getting any further replies to a similar question at https://github.com/RESTful-Drupal/restful/issues/353 so I've opened a new issue. The suggested use of `hook_entity_property_info` doesn't apply in my case.

**Comment by amitaibu** [comment]
Sorry, I missed the new questions in #353 -- those are answered now there. I think this can be closed?

**Comment by BurningDog** [comment]
Thanks for the answers - those did help :) I still do have the following question:

> What is the way to get the node id inside my class, which doesn't use $this->path?

...but have workable workarounds for my other 2 cases, so if my question doesn't make sense, please go ahead and close this issue.

**Comment by amitaibu** [comment]
>  so if my question doesn't make sense, please go ahead and close this issue.

It doesn't ;) The answer is to override the `entityView()` method
