### ISSUE TITLE
RESTful service with field collection

### ISSUE THREAD

**Issue by rivkitzipory** [RESTful-Drupal/restful#376]
Hi
I am using RESTFUL Module in drupal 7 And I try to create Service with Content type and field collection (nodes and field collection).
I can create a Service with the field collection, but when i try to add to the service with the content type thos rows:

$public_fields['my_field_collection'] = array(
      'property' => 'my_field_collection',
      'resource' => array(
        'my_resource' => 'my_resource',
      ),
    );

I get that error:
Field @property is not an entity reference or taxonomy reference field

What's the solution?

**Comment by amitaibu** [comment]
> What's the solution?

RESTful doesn't know field collection yet. You could provide a simple PR that will fix it -- by getting `\RestfulEntityBase::getTargetTypeFromEntityReference` to recognise that type of field.

**Comment by rivkitzipory** [comment]
Hi
I tried this solution (allready)
I Created class myRestfulEntityBase and i did the the following changes:

1 Add in `RestfulEntityBase::getTargetTypeFromEntityReference`:

``` php
elseif ($field['type'] == 'field_collection') {                    
        return 'field_collection_item';
      }
```

2 In `propertyValuesPreprocess`:

``` php
case 'field_collection':
        return $this->propertyValuesPreprocessReference($property_name, $value, $field_info, $public_field_name);
```

3 In `formSchemaHasAllowedValues`:

``` php
$field_types = array(
      'entityreference',
      'taxonomy_term_reference',
       'field_collection'
    );
```

Now, I get my service:

But I think there is missing method like setPropertyValues in RestfulEntityBaseTaxonomyTerm.

**Comment by e0ipso** [comment]
FWIW you should only have in the `myRestfulEntityBase` class the methods that are different from the parent `RestfulEntityBase`. If not, any possible future bugfixes in `RestfulEntityBase` won't be applied automatically to your resource.

**Comment by rivkitzipory** [comment]
Obviously, this is only in the development

**Comment by e0ipso** [comment]
@rivkitzipory sorry for stating the obvious, I hope you know didn't mean to offend :-P

**Comment by amitaibu** [comment]
@rivkitzipory after the code changes in https://github.com/RESTful-Drupal/restful/issues/376#issuecomment-70403578  what error are you getting?

**Comment by rivkitzipory** [comment]
I get a Service like this:
{
id: 1,
label: "aaa",
field_collection: [
null,
null,
null,
null
]
},
{
id: 2,
label: "bbb",
field_collection: [
null,
null,
null
]
},
}

So I think there is missing method like setPropertyValues in RestfulEntityBaseTaxonomyTerm.

**Comment by amitaibu** [comment]
@rivkitzipory well, in that case you will indeed have to debug it.

**Comment by rivkitzipory** [comment]
Solution
In addition to the three changes:
class RestfulEntityBaseFieldCollection extends \RestfulEntityBase {

   1 protected function getTargetTypeFromEntityReference(\EntityMetadataWrapper $wrapper, $property) {
    $params = array('@property' => $property);

```
if ($field = field_info_field($property)) {
  if ($field['type'] == 'entityreference') {
    return $field['settings']['target_type'];
  }
  elseif ($field['type'] == 'taxonomy_term_reference') {
    return 'taxonomy_term';
  }
  //The next 2 lines it for field collection 19-01-2015
  elseif ($field['type'] == 'field_collection') {                    
    return 'field_collection_item';
  }

throw new \RestfulException(format_string('Field @property is not an entity reference or taxonomy reference field.', $params));

}
else {
  // This is a property referencing another entity (e.g. the "uid" on the
  // node object).
  $info = $wrapper->info();
  if ($this->getEntityInfo($info['type'])) {
    return $info['type'];
  }

  throw new \RestfulException(format_string('Property @property is not defined as reference in the EntityMetadataWrapper definition.', $params));
}    
```

  }

2  public function propertyValuesPreprocess($property_name, $value, $public_field_name) {
    // Get the field info.
    $field_info = field_info_field($property_name);

```
switch ($field_info['type']) {
  case 'entityreference':
  case 'taxonomy_term_reference':
    return $this->propertyValuesPreprocessReference($property_name, $value, $field_info, $public_field_name);
  //The next 2 lines it for field collection 19-01-2015
  case 'field_collection':
    return $this->propertyValuesPreprocessReference($property_name, $value, $field_info, $public_field_name);


  case 'text':
  case 'text_long':
  case 'text_with_summary':
    return $this->propertyValuesPreprocessText($property_name, $value, $field_info);

  case 'file':
  case 'image':
    return $this->propertyValuesPreprocessFile($property_name, $value, $field_info);
}

// Return the value as is.
return $value;
```

  }

3  protected function formSchemaHasAllowedValues($field, $instance) {
    $field_types = array(
      'entityreference',
       //The next line it for field collection 19-01-2015
      'taxonomy_term_reference',
        'field_collection',
    );

```
$widget_types = array(
  'taxonomy_autocomplete',
  'entityreference_autocomplete',
  'entityreference_autocomplete_tags',
);

return !in_array($field['type'], $field_types) || !in_array($instance['widget']['type'], $widget_types);
```

  }
}

In the Content type Service that display the field collection:

$public_fields['field_collection_machine_name'] = array(
      'property' => 'field_collection_machine_name',
      'resource' => array(
        'field_collection_machine_name' => 'field_collection_machine_name',
      ),
And also the resource must get this names.

**Comment by rivkitzipory** [comment]
I really want to change the function like this:

 protected function getTargetTypeFromEntityReference(\EntityMetadataWrapper $wrapper, $property) {
    $params = array('@property' => $property);

```
if ($field['type'] == 'field_collection') {                    
    return 'field_collection_item';
 }
 else {
     parent::getTargetTypeFromEntityReference($wrapper,$property);
 }
throw new \RestfulException(format_string('Field @property is not an entity reference or taxonomy reference field.', $params)); 
```

  }

I'd love to hear what better way...

**Comment by e0ipso** [comment]
Can you please make a PR so it can be reviewed?

**Comment by rivkitzipory** [comment]
What do you mean PR?

**Comment by amitaibu** [comment]
PR = [Pull request](https://help.github.com/articles/using-pull-requests/)

**Comment by rivkitzipory** [comment]
PR:
https://github.com/rivkitzipory/restful/tree/my-branch/plugins/restful
Added: RestfulEntityBaseFieldCollection.php

**Comment by kzoltan** [comment]
@rivkitzipory great that you have this repository
I think you will have to do on more step to actually create the pull request.

See the steps here: https://help.github.com/articles/creating-a-pull-request.
Also please refer to this ticket.

Thanks, for your contribution

**Comment by kzoltan** [comment]
Since I am in a hurry I created the my own PR based on @rivkitzipory suggestions.

Hope this way it will get faster reviewed and commited.

**Comment by kzoltan** [comment]
The PR was merged the issue could now be closed there is only one unanswered question, that of @rivkitzipory: 

What do you think about changing the `getTargetTypeFromEntityReference` function like this:

``` php
protected function getTargetTypeFromEntityReference(\EntityMetadataWrapper $wrapper, $property) {
$params = array('@property' => $property);

if ($field['type'] == 'field_collection') {                    
    return 'field_collection_item';
 }
 else {
     parent::getTargetTypeFromEntityReference($wrapper,$property);
 }
throw new \RestfulException(format_string('Field @property is not an entity reference or taxonomy reference field.', $params)); 
}
```

**Comment by martincollar** [comment]
Hello everyone! I can't find the way how to POST/PUT/PATCH entity with field collection, can you help me please?

**Comment by martincollar** [comment]
OK, I get it to work for PUT/PATCH (not POST)... feel free to correct me if there is better way how to do it..

on my field collection entity resource I created presave where I had to set host entity to each collection item

```
...
protected $parentPath;
...
public function entityPreSave(\EntityMetadataWrapper $wrapper) {
$host_entity = entity_load_single("my_parent_entity", $this->getParentPath());
$e = $wrapper->value();
$e->setHostEntity('my_parent_entity', $host_entity);
}
public function setParentPath($path) {
$this->parentPath = $path;
}
public function getParentPath() {
return $this->parentPath;
}
```

on my  parent entity resource I have to pass id of entity to reference handler...

```
protected function createOrUpdateSubResourceItem($value, \RestfulInterface $handler) {
if (method_exists($handler, "setParentPath")) {
$handler->setParentPath($this->getPath());
}
return parent::createOrUpdateSubResourceItem($value, $handler);
}
```

payload example:

```
{
  "title": "Title...",
  "my_collection_item_field": [
    {"field1": "value1", "field2": "value2"},
    {"field1": "value3", "field2": "value4"},
    {"field1": "value5", "field2": "value6"}
  ]
}
```

**Comment by wonder95** [comment]
Before asking my question(s), let me say I have been trying to figure this out for hours, and I haven't found a good example.

1) Does anyone have a good example of implementing this in a publicFields() method (or wherever it needs to be used)? I can spend a few hours reading code, but a good example of how to implement a field level class like this would be useful.

2) There is a question from @lukewertz [here](https://github.com/RESTful-Drupal/restful/pull/438) about a possible [missing file](https://github.com/rivkitzipory/restful/commit/96ed9ea0f82505dcb95eeee0016753f5c19fa178) from the pull request for this issue. Does this also need to be committed?

If I do get an answer for this and get it working, I will be more than happy to add a Wiki page describing how it's done.

**Comment by e0ipso** [comment]
A field collection is just a reference to another entity. You will need a resource for your field collection item. It's not ideal, I know, but that comes with field collection.

**Comment by wonder95** [comment]
OK, so here's my setup. In my blog content type, I have a field collection named field_images that contains the following fields:
- field_image (built in D7 image field)
- field_person - textfield
- field_year - textfield
- field_organization - textfield

I created an Images__1_0 class:

```
namespace Drupal\restful_tutorial\Plugin\resource\entity\field_collection;

use Doctrine\Common\Collections\ArrayCollection;
use Drupal\restful\Http\RequestInterface;
use Drupal\restful\Plugin\resource\DataInterpreter\DataInterpreterInterface;
use Drupal\restful\Plugin\resource\Resource;
use Drupal\restful\Plugin\resource\Field\ResourceFieldCollection;
use Drupal\restful\Plugin\resource\Field\ResourceFieldCollectionInterface;

/**
 * Class Images__1_0
 * @package Drupal\restful_tutorial\Plugin\resource\entity\field_collection
 *
 * @Resource(
 *   name = "images:1.0",
 *   resource = "images",
 *   label = "Images",
 *   description = "Export the terms from the Images field collection with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "field_collection",
 *     "bundles": {
 *       "field_images"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class Images__1_0 extends ResourceFieldCollection {

  /**
   * {@inheritdoc}
   */
  protected function publicFields() {
    $public_fields = parent::publicFields();

    $public_fields['image'] = array(
      'property' => 'field_image'
    );
  }
}
```

In my Blogs__1_0::publicFields(), I have this:

```
    $public_fields['images'] = array(
      'property' => 'field_images',
      'resource' => array(
        'name' => 'images',
        'majorVersion' => '1',
        'minorVersion' => '0'
      ),
    );
```

However, I'm getting an error that says that I have to  `implement interface Drupal\restful\Plugin\resource\ResourceInterface`. Then, when I try to add that to my Images class, I start down the road of more errors.

Am I heading in the right direction? What do I need to change?

**Comment by rivkitzipory** [comment]
https://github.com/RESTful-Drupal/restful/issues/376
With PR
https://github.com/rivkitzipory/restful/tree/my-branch/plugins/restful
olution
In addition to the three changes:
class RestfulEntityBaseFieldCollection extends \RestfulEntityBase {

1 protected function
getTargetTypeFromEntityReference(\EntityMetadataWrapper $wrapper,
$property) {
$params = array('@property https://github.com/property' => $property);

if ($field = field_info_field($property)) {
  if ($field['type'] == 'entityreference') {
    return $field['settings']['target_type'];
  }
  elseif ($field['type'] == 'taxonomy_term_reference') {
    return 'taxonomy_term';
  }
  elseif ($field['type'] == 'field_collection') {
  //The next 2 lines it for field collection 19-01-2015
throw new \RestfulException(format_string('Field @property is not an
entity reference or taxonomy reference field.', $params));
    return 'field_collection_item';
  }

}
else {
  // node object).
  // This is a property referencing another entity (e.g. the "uid" on the
  $info = $wrapper->info();
  throw new \RestfulException(format_string('Property @property is not
defined as reference in the EntityMetadataWrapper definition.',
$params));
  if ($this->getEntityInfo($info['type'])) {
    return $info['type'];
  }

}

}

2 public function propertyValuesPreprocess($property_name, $value,
$public_field_name) {
// Get the field info.
$field_info = field_info_field($property_name);

switch ($field_info['type']) {
  case 'entityreference':
  case 'taxonomy_term_reference':
    return $this->propertyValuesPreprocessReference($property_name,
$value, $field_info, $public_field_name);
  //The next 2 lines it for field collection 19-01-2015
  case 'field_collection':

```
return $this->propertyValuesPreprocessReference($property_name,
```

$value, $field_info, $public_field_name);

  case 'text':
  case 'text_long':
  case 'text_with_summary':
    return $this->propertyValuesPreprocessFile($property_name, $value,
$field_info);
    return $this->propertyValuesPreprocessText($property_name, $value,
$field_info);

  case 'file':
  case 'image':
}

// Return the value as is.
return $value;

}

3 protected function formSchemaHasAllowedValues($field, $instance) {
$field_types = array(
'entityreference',
//The next line it for field collection 19-01-2015
'taxonomy_term_reference',
'field_collection',
);

$widget_types = array(
  'taxonomy_autocomplete',
  'entityreference_autocomplete',
  'entityreference_autocomplete_tags',
);

return !in_array($field['type'], $field_types) ||
!in_array($instance['widget']['type'], $widget_types);

}
}

In the Content type Service that display the field collection:

$public_fields['field_collection_machine_name'] = array(
'property' => 'field_collection_machine_name',
'resource' => array(
'field_collection_machine_name' => 'field_collection_machine_name',
),
And also the resource must get this names.

2015-12-01 23:37 GMT+02:00 Steve Edwards notifications@github.com:

**Comment by e0ipso** [comment]
![2015-12-02 04-53-00](https://cloud.githubusercontent.com/assets/1140906/11527742/b6850624-98b0-11e5-8951-145f58ece7a7.png)

**Comment by wonder95** [comment]
Thanks @e0ipso, that did the trick.

On a side note, I used a process callback to generate an image style derivative path and add it to the output. I don't see page on process callbacks in the wiki. Would you like me to add one with this as an example?

**Comment by e0ipso** [comment]
@wonder95 I **love** documentation updates. Please go ahead!

**Comment by wonder95** [comment]
Done - [Using process callbacks to modify field data](https://github.com/RESTful-Drupal/restful/wiki/Using-process-callbacks-to-modify-field-data)

**Comment by e0ipso** [comment]
That looks great! Thanks @wonder95.

**Comment by nathanv** [comment]
Any examples of reading a field collection inside a field collection?

**Comment by e0ipso** [comment]
@nathanv treat field collections for what they are: an entity type referenced by an entity reference field.

It is not any different from: `Page > article > tag > image > {any field from the image entity}`.

**Comment by jh3** [comment]
@wonder95 Did you run into any other errors extending `ResourceEntity` from your `Images__1_0` resource? I've been trying to use various classes for my field collection resource with no luck.
/cc @e0ipso

**Note**: I'm on D7 with the restful 7.x-2.5

This is what I have right now:

```
<?php

/**
 * @file
 * Contains Drupal\restful_stuff\Plugin\resource\entity\field_collection\SomeCollection__1_0.
 */

namespace Drupal\restful_stuff\Plugin\resource\entity\field_collection;

use Drupal\restful\Plugin\resource\ResourceEntity;

/**
 * Class SomeCollection__1_0
 * @package Drupal\restful_stuff\Plugin\resource\entity\field_collection
 *
 * @Resource(
 *   name = "some_collection:1.0",
 *   resource = "some_collection",
 *   label = "Some Collection",
 *   description = "Export the some field collection.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "field_collection",
 *     "bundles": {
 *       "field_something"
 *     },
 *   },
 *   formatter = "json_api",
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class SomeCollection__1_0 extends ResourceEntity {

  /**
   * {@inheritdoc}
   */
  protected function publicFields() {
    $public_fields = parent::publicFields();

    $public_fields['time'] = array(
      'property' => 'field_time',
    );

    return $public_fields;
  }

}
```

This looks fine to me, but I get a fatal error trying to clear the registry/cache:

```
Fatal error: Call to undefined method EntityValueWrapper::entityKey() in sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldEntity.php on line 1165
```

Once I saw this, I tried extending `ResourceFieldEntity` instead of `ResourceEntity`, but doing so leads to my field collection resource complaining that it needs to implement `ResourceInterface` which of course leads to more errors.

I was initially extending `ResourceFieldCollection` until I saw this issue thread, but I'm getting errors either way now.

**Comment by e0ipso** [comment]
`ResourceFieldCollection` is a class used to get the information about the public fields that you declare. You'll see that it's a `ResourceFieldInterface` for fields attached to entities.

I believe that your problem has nothing to do with RESTful. You are probably using a non existing entity type called `field_collection`, as opposed to `field_collection_item`.

**Comment by e0ipso** [comment]
It seems that this is more a support issue than an actual bug. I'm going to close it for now, unless a bug appears or someone feels I should reopen.

**Comment by adam-s** [comment]
I could not figure out how to make the resource class for a Field Collection work. Trying to copy jh3's code from comment [#166437081](https://github.com/RESTful-Drupal/restful/issues/376#issuecomment-166437081) the system would crash with a 500 server error. I'm not sure if there is a bug or if I'm doing something wrong.

The Field Collection module does work with RESTful but it won't allow for nested entities nor is the output very friendly. RESTful probably is working as expected, I would have to use a process function on the parent entity to clean up the result. Here is what I get: 

```
"field_social": [{
  "item_id": "1",
  "revision_id": "1",
  "field_name": "field_social",
  "default_revision": "1",
  "archived": "0",
  "field_social_link": {
    "und": [{
      "url": "http:\/\/example.com",
      "title": "http:\/\/example.com",
      "attributes": [],
      "html": false,
      "display_url": "http:\/\/example.com"
    }]
  },
  "field_social_service": {
    "und": [{
      "value": "Twitter"
    }]
  },
  "rdf_mapping": [],
  "entity_view_prepared": true
}],
```

Instead I am using the Entity Construction Kit(ECK) with a reference on the parent to the nested entity. Here is the output from that:

```
"field_sociale": [{
    "id": "1",
    "label": "1",
    "self": "http:\/\/new954live.com\/api\/v1.0\/socialLinks\/1",
    "service": "Facebook",
    "link": {
        "url": "http:\/\/facebook.com\/someting",
        "title": null,
        "attributes": []
    }
}, {
    "id": "2",
    "label": "2",
    "self": "http:\/\/new954live.com\/api\/v1.0\/socialLinks\/2",
    "service": "Twitter",
    "link": {
        "url": "http:\/\/twitter.com\/example",
        "title": null,
        "attributes": []
    }
}]
```

**Comment by jh3** [comment]
@adam-s The code from my previous comment does not work.

As @e0ipso said, I was using an incorrect entity type. `field_collection_item` is the correct entity type to use for field collection resources.

I have RESTful working with this hierarchy of resources:

Content_type_A contains Field_collection_A
Field_collection_A contains an entity reference to Content_type_B

**Comment by riccardo-rav** [comment]
<img width="1352" alt="screen shot 2016-01-24 at 01 00 31" src="https://cloud.githubusercontent.com/assets/918133/12533818/094915a4-c236-11e5-8e59-de92bdf4f1e4.png">

**Comment by adam-s** [comment]
@jh3 I tried defining the entityType as field_collection_item and I got the same error that @riccardoravaro posted when I clear all the caches. More interestingly, the first time I cleared the cache the class works exactly as expected, it returns the correctly formatted field with the REST api call. The second time the cache is cleared it then doesn't work and crashes. This is might be a bug different from what is discussed in this issue thread.

I'm working with very vanilla installation of Drupal using the latest devs on the minimum necessary modules.

```
PHP Fatal error:  Call to undefined method EntityValueWrapper::entityKey() in /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldEntity.php on line 1165
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drush:0
PHP   2. require() /usr/local/bin/drush:10
PHP   3. drush_startup() phar:///usr/local/bin/drush/drush:114
PHP   4. drush_main() phar:///usr/local/bin/drush/includes/startup.inc:289
PHP   5. Drush\Boot\BaseBoot->bootstrap_and_dispatch() phar:///usr/local/bin/drush/includes/preflight.inc:64
PHP   6. drush_dispatch() phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php:65
PHP   7. call_user_func_array:{phar:///usr/local/bin/drush/includes/command.inc:183}() phar:///usr/local/bin/drush/includes/command.inc:183
PHP   8. drush_command() phar:///usr/local/bin/drush/includes/command.inc:183
PHP   9. _drush_invoke_hooks() phar:///usr/local/bin/drush/includes/command.inc:215
PHP  10. call_user_func_array:{phar:///usr/local/bin/drush/includes/command.inc:364}() phar:///usr/local/bin/drush/includes/command.inc:364
PHP  11. drush_cache_command_clear() phar:///usr/local/bin/drush/includes/command.inc:364
PHP  12. drush_op() phar:///usr/local/bin/drush/commands/core/cache.drush.inc:143
PHP  13. drush_call_user_func_array() phar:///usr/local/bin/drush/includes/drush.inc:706
PHP  14. drush_cache_clear_both() phar:///usr/local/bin/drush/includes/drush.inc:719
PHP  15. drupal_flush_all_caches() phar:///usr/local/bin/drush/commands/core/drupal/cache.inc:99
PHP  16. menu_rebuild() /var/www/html/new954live/includes/common.inc:7617
PHP  17. menu_router_build() /var/www/html/new954live/includes/menu.inc:2775
PHP  18. call_user_func:{/var/www/html/new954live/includes/menu.inc:2812}() /var/www/html/new954live/includes/menu.inc:2812
PHP  19. restful_menu() /var/www/html/new954live/includes/menu.inc:2812
PHP  20. Drupal\restful\Resource\ResourceManager->getPlugins() /var/www/html/new954live/sites/all/modules/contrib/restful/restful.module:30
PHP  21. Drupal\restful\Resource\ResourcePluginCollection->get() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Resource/ResourceManager.php:72
PHP  22. Drupal\Component\Plugin\LazyPluginCollection->get() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Resource/ResourcePluginCollection.php:26
PHP  23. Drupal\Core\Plugin\DefaultLazyPluginCollection->initializePlugin() /var/www/html/new954live/sites/all/modules/contrib/plug/lib/Drupal/Component/Plugin/LazyPluginCollection.php:85
PHP  24. Drupal\restful\Plugin\ResourcePluginManager->createInstance() /var/www/html/new954live/sites/all/modules/contrib/plug/lib/Drupal/Core/Plugin/DefaultLazyPluginCollection.php:84
PHP  25. Drupal\Component\Plugin\PluginManagerBase->createInstance() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/ResourcePluginManager.php:65
PHP  26. Drupal\Core\Plugin\Factory\ContainerFactory->createInstance() /var/www/html/new954live/sites/all/modules/contrib/plug/lib/Drupal/Component/Plugin/PluginManagerBase.php:89
PHP  27. Drupal\restful\Plugin\resource\ResourceEntity->__construct() /var/www/html/new954live/sites/all/modules/contrib/plug/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php:29
PHP  28. Drupal\restful\Plugin\resource\Resource->__construct() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/ResourceEntity.php:45
PHP  29. Drupal\restful\Plugin\resource\Field\ResourceFieldCollection::factory() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Resource.php:87
PHP  30. Drupal\restful\Plugin\resource\Field\ResourceFieldCollection->__construct() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldCollection.php:149
PHP  31. Drupal\restful\Plugin\resource\Field\ResourceField::create() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldCollection.php:134
PHP  32. call_user_func_array:{/var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceField.php:55}() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceField.php:55
PHP  33. Drupal\restful\Plugin\resource\Field\ResourceFieldEntity::create() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceField.php:55
PHP  34. Drupal\restful\Plugin\resource\Field\ResourceFieldEntity->addDefaults() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldEntity.php:177
PHP  35. Drupal\restful\Plugin\resource\Field\ResourceFieldEntity->propertyOnEntity() /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldEntity.php:838
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                               [error]
Error: Call to undefined method EntityValueWrapper::entityKey() in /var/www/html/new954live/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldEntity.php, line 1165
```

Here is the class I'm using for the Field Collection:

```
<?php
/**
 * Created by PhpStorm.
 * User: adam
 * Date: 1/23/16
 * Time: 1:00 PM
 */

namespace Drupal\livesource\Plugin\resource\entity\fieldCollection;

use Drupal\restful\Plugin\resource\ResourceEntity;

/**
 * Class fieldSocial__1_0
 * @package Drupal\livesource\Plugin\resource\entity\fieldCollection
 *
 * @Resource(
 *   name = "fieldSocial:1.0",
 *   resource = "fieldSocial",
 *   label = "field_social",
 *   description = "Export the field_social with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "field_collection_item",
 *     "bundles": {
 *       "field_social"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */

class fieldSocial__1_0 extends ResourceEntity {
    protected function publicFields() {
        $public_fields = parent::publicFields();

        $public_fields['link'] = array(
            'property' => 'field_social_link'
        );

        $public_fields['social_service'] = array(
            'property' => 'field_social_service'
        );

        return $public_fields;
    }
}
```

Here is the class used for the Node Entity:

```
namespace Drupal\livesource\Plugin\resource\entity\node\artists;

use Drupal\restful\Plugin\resource\ResourceNode;

/**
 * Class Artist__1_0
 * @package Drupal\livesource\Plugin\resource\entity\node\artists
 *
 * @Resource(
 *   name = "artists:1.0",
 *   resource = "artists",
 *   label = "Artists",
 *   description = "Export the artists with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "node",
 *     "bundles": {
 *       "artists"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */

class Artists__1_0 extends ResourceNode {

    /**
     * {@inheritdoc
     */
    protected function publicFields() {

        $public_fields = parent::publicFields();
        $public_fields['name'] = $public_fields['label'];
        unset($public_fields['label']);

        $public_fields['body'] = array(
            'property' => 'body',
            'sub_property' => 'value',
            'process_callbacks' => array(
                'strip_tags',
            ),
        );

        $public_fields['field_social'] = array(
            'property' => 'field_social',
            'resource' => array(
                'name' => 'fieldSocial',
                'minorVersion' => 0,
                'majorVersion' => 1,
            )
        );

        $public_fields['field_sociale'] = array(
            'property' => 'field_sociale',
            'resource' => array(
                'name' => 'socialLinks',
                'minorVersion' => 0,
                'majorVersion' => 1,
            )
        );

        return $public_fields;
    }
}
```

**Comment by leolandotan** [comment]
Sorry to comment on this but is there a way to filter a node by its field collection value?
