### ISSUE TITLE
2.x - Cut the inheritance of the RestfulBase.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#377]
Meta #375 
## Real scenario

We want contributed modules to provide support for their special field types with relationships.

Imagine that we have a content type that has a _field collection_ field (gasp!) and a _multifield_ field. At this moment there is no support for the relationships between the field and the referenced entity (fake entity or not). The only two possible ways are:
1. We add support for them in the RESTful module.
2. We allow contrib _brigde_ modules: `restful_field_collection`, `restful_multifield`, …
## Problem

Depending on the approach from the section above we will encounter several problems.
1. If we add support for them in the RESTful module:
   - There are (potentially) _a lot_ of contrib modules that may need this. We don't want to clutter the codebase.
   - We need to support these field integrations (that we may know nothing about).
   - If a new fancy field appears, we have to write support for it, instead of letting the maintainer of the field provide integration for RESTful.
2. If we use _brigde_ modules, the bridge module needs to create a class that extends `RestfulEntityBase` and call it `RestfulFieldCollectionEntityBase`:
   - The implementor has to change all the resources that use field collections to inherit from `RestfulFieldCollectionEntityBase`.
   - It is impossible to inherit from 2 different classes at the same time. That means that no resource can have support for `RestfulFieldCollectionEntityBase` and `RestfulMultifieldEntityBase` at the same time.
## Proposed solution for 2.x

Do not use inheritance to provide field integration, but decouple the `Resource` and the `DataMapper`. That way _bridge_ module will just need to provide a `DataMapper`.

The `Resource` will have to know that it needs to use `Drupal\restful_field_collection\DataMapper\FieldCollectionMapper` to get the information for that `field_my_field_collection`.

**Comment by e0ipso** [comment]
@amitaibu: impressions?

**Comment by amitaibu** [comment]
You mean `Drupal\restful_field_collection\DataMapper\FieldCollectionMapper` will register itself as a data mapper? This makes sense to me. (Basically, It's a hook like, but with registered classes)

**Comment by m4olivei** [comment]
I'm curious where this issue went?  Mainly I'm interested for the purpose of supporting multifield fields. Is supporting a multifield possible in 7.x-2.x?  Specifically, I have a multifield in which one of the sub fields is an entity reference field, that I'd like to use for a relationship.

**Comment by e0ipso** [comment]
@m4olivei in this case I am using the term _field collection_ as a synonym of _array of fields_. Not the field collection module type of things.

This issue was part of the 2.x re-architecture. So, if you are using 2.x, you are probably already celebrating the success of this issue :-)

**Comment by m4olivei** [comment]
Thanks @e0ipso. I'm not sure I understand everything that's going on, but in my case, I had a multifield with an entity reference field that I was able to support for a relationship by declaring a public field like this:

``` php
$public_fields['cast'] = array(
  'property' => 'field_person_credit',
  'sub_property' => 'field_cast',
  'class' => '\Drupal\my_module\Plugin\resource\Field\ResourceFieldMultifieldEntityReference',
  'resource' => array(
    'name' => 'cast',
    'majorVersion' => '1',
    'minorVersion' => '0',
  ),
);
```

And the class looks like this:

``` php
<?php
/**
 * @file
 * Contains \Drupal\my_module\Plugin\resource\Field
 */
namespace Drupal\my_module\Plugin\resource\Field;

use Drupal\restful\Plugin\resource\Field\ResourceFieldEntityReference;

/**
 * Class \Drupal\my_module\Plugin\resource\Field\ResourceFieldTVRelationshipAdvanced
 */
class ResourceFieldMultifieldEntityReference extends ResourceFieldEntityReference {

  /**
   * {@inheritdoc}
   */
  protected function buildResourceMetadataItem($wrapper) {
    $entity = current($this->fieldValue($wrapper));
    list($id,,$bundle) = entity_extract_ids($this->getEntityType(), $entity);
    $resource = $this->getResource();
    return array(
      'id' => $id,
      'entity_type' => $this->getEntityType(),
      'bundle' => $bundle,
      'resource_name' => $resource['name'],
    );
  }

  /**
   * Helper function to get the identifier from a property wrapper.
   *
   * @param \EntityMetadataWrapper $property_wrapper
   *   The property wrapper to get the ID from.
   *
   * @return string
   *   An identifier.
   */
  protected function propertyIdentifier(\EntityMetadataWrapper $property_wrapper) {
    $entity = current($this->fieldValue($property_wrapper));
    list($id,,) = entity_extract_ids($this->getEntityType(), $entity);
    return $id;
  }
}
```
