### ISSUE TITLE
Enable support for sub-property setter

### ISSUE THREAD

**Issue by bricel** [RESTful-Drupal/restful#378]
In case of fields with sub properties the setter fail on create and update the values:
example:

```
$public_fields['period'] = array(
      'property' => 'field_work_length',
      'sub_property' => 'period',
    );
```

In such case when saving the entity wrapper should use the following format:

```
$wrapper->{$property_name}->{$sub_property_name}->set($field_value);
```

**Comment by e0ipso** [comment]
Closing in favor of #379.
