### ISSUE TITLE
RESTful service with Pager - next link

### ISSUE THREAD

**Issue by rivkitzipory** [RESTful-Drupal/restful#381]
Hi 
I created Service that display large number of records - count: 1000
So I have a next link like : http://my web/api/v1.0/my service/page/2/0,
When I clicked on the link I get this error:
""Page" property should be numeric and equal or higher than 1."

Then I saw in RestfulBase line 937 thos row:
if (!ctype_digit((string) $page) || $page < 1)
When I comment this "if"  everythig worked nice,

But I want check that the page is numeric and greater than 0 
I checked what the $page, and I saw that is a string: "2,0"
Saw I changed this row to:
if(!is_numeric($page[0]) || !is_numeric($page[2]) || $page[0] < 0 || $page[2] < 0)

Summary
For Pager in restful Service
Change this row in RestfulBase line 937:
if (!ctype_digit((string) $page) || $page < 1)
To this row:
if(!is_numeric($page[0]) || !is_numeric($page[2]) || $page[0] < 0 || $page[2] < 0)

**Comment by e0ipso** [comment]
I believe that you should be doing

?page=1

**Comment by rivkitzipory** [comment]
To this row:
if(($page != 1) && (!is_numeric($page[0]) || $page[0] < 0 || (isset($page[2]) && !is_numeric($page[2])) || (isset($page[2]) && $page[2] < 0))){
