### ISSUE TITLE
RESTful service Variable with filter

### ISSUE THREAD

**Issue by rivkitzipory** [RESTful-Drupal/restful#382]
Hi 
I want to create Service for Variable with filter.
I copied variable Service from restful_example.
And I want to add a function like:

 public function getQueryForList() {
        $query = parent::getQueryForList();  
        $query->fieldCondition('name','value','my_value', '=');  
        return $query;
  }
But it's not working, I understand that Variable is not Entity...
What simple solution without going through and understand the Parent class code?

**Comment by e0ipso** [comment]
The variable resource example is going to change significantly in https://github.com/RESTful-Drupal/restful/pull/356

You can use the same filters on it as in any other resource.

**Comment by rivkitzipory** [comment]
Hi
I did all the changes, not working!!
There is no simpler solution?

**Comment by amitaibu** [comment]
you should be using `$query->condition()` (this is a `db_select()` not `entityFieldQurery` object)

**Comment by rivkitzipory** [comment]
Worked thanks.
In My RestfulQueryVariable Class

 public function getQueryForList() {
    $query = parent::getQueryForList();  
    $query->condition('name', 'my_value','=');
    return $query;  
  }

**Comment by rivkitzipory** [comment]
Hi
I try to add this lines to class that extends RestfulEntityBase:
public function getQueryForList() {
    $query = parent::getQueryForList();
    $query->fieldConditions('my_field_name','value','my value','=');
    return $query;
  }
But I get this Error:
Call to undefined method EntityFieldQuery::fieldConditions() .
But $query Is entityFieldQurery ...?!

**Comment by rivkitzipory** [comment]
Sorry
The Error: 
I wrote fieldConditions ןnstead of fieldCondition

**Comment by rivkitzipory** [comment]
Hi
My fieldCondition is not simple fieldCondition.
I have Service for content type and another sevice for field collection resource,
I want add a fieldCondition to the field collection service,
So i added  getQueryForList() function to the field collection service,
Then if I do /api/v1.0/field collection service it's work nice.
But I really need /api/v1.0/content type service ,
And then the service not use in the getQueryForList() in the resource.
If I try to write the getQueryForList() in the content type service-
It seems he does not know exactly this field....

**Comment by rivkitzipory** [comment]
My solution:
In the field collection resource
Add this function
public function viewEntity($id) {
      $value = parent::viewEntity($id);
       if(isset($_GET['some_parameter'])){
          $some_parameter_value = check_plain($_GET['some_parameter']);
          if($value['field_in_field_collection'] !=  $some_parameter_value){
            return;
          }
        return $value;  
      }
      return $value;  
  }

Note:
You cant extends the getList() or getQueryForList() methods and add fieldCondition,
Because you want filter the field in the field_collection service 
and the Service use the subservice by the resource and not by getList() function !!!

**Comment by e0ipso** [comment]
You should avoid accessing `$_GET`. Instead use `$request = $this->getRequest(); $some_parameter_value = $request['some_parameter'];`

**Comment by rivkitzipory** [comment]
I changed thanks
