### ISSUE TITLE
Filter by term parent

### ISSUE THREAD

**Issue by guillaumev** [RESTful-Drupal/restful#389]
Hi,

I have a use case which seems to be tricky with Restful. I have a hierarchical taxonomy of locations and I'd like to be able to filter by parent terms (get all terms which have a specific parent).

After looking into this for a while, I think it will be hard, given that restful uses EntityFieldQuery and the information I'm looking for is in the taxonomy_term_hierarchy table. Any thought of how this could be achieved ?

**Comment by e0ipso** [comment]
You should be able to override the appropriate method in your resource (something along the lines of `addTags`) and add your custom EFQ tag.

Then implement `hook_query_TAG_alter` to add your joins and your custom logic.

**Comment by amitaibu** [comment]
Or maybe you could have a restful resource that extends the DB data provider, and query your table directly.

**Comment by attiks** [comment]
You can have a look at https://www.drupal.org/project/taxonomy_edge and https://www.drupal.org/project/taxonomy_edge_field it adds a transitive closure table for all term levels, hook_query_TAG_alter will work but is not really a generic solution, if you could extend on top of taxonomy edge it will work for all entities.

**Comment by guillaumev** [comment]
Thanks for the help ! Using addExtraInfotoQuery and hook_query_TAG_alter actually worked !
