### ISSUE TITLE
Token auth provider

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#42]
- I think we should add a submodule called `restful_token_auth` that will provide an endpoint to login/ register/ retrieve password via CURL.
- Response will return a token string.
- We can have a fieldable `token_auth` entity that will have the token info, along with the user it's related to, and the created/ expire info.

Once we have this we can create an example repo of a completely decoupled AngularJs webapp talking with a completely RESTful Drupal. Which is pretty awesome ;)

**Comment by e0ipso** [comment]
I believe this is closed now. w00t!
