### ISSUE TITLE
Fix syntax error.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#427]
This seems like an error:

``` php
if (!empty($wrapper->url) && $url = $wrapper->url->value()); {
  $this->setHttpHeaders('Location', $url);
}
```

https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/plugins/restful/RestfulEntityBase.php#L595

**Comment by amitaibu** [comment]
Not en error - we are checking that the wrapper has a `url` property, as some entities don't necessarily have a url(). So if the entity doesn't have a url, we don't bother calling `$wrapper->url->value()`

**Comment by e0ipso** [comment]
I meant the extra semicolon in the `if` clause.

**Comment by amitaibu** [comment]
Oh, sorry ;)

**Comment by e0ipso** [comment]
My bad. There was no mention of semicolon in the original description.
