### ISSUE TITLE
How to get uid on token login?

### ISSUE THREAD

**Issue by uniquename** [RESTful-Drupal/restful#429]
Maybe a stupid question, cause i missed something... 

Getting the access_token with basic auth works just fine, but how can I receive user data or uid to get it from the users resource, after I got the token?

...btw. fantastic module!-)

**Comment by amitaibu** [comment]
You mean `$this->getAccount()` ?

**Comment by uniquename** [comment]
Sorry, maybe I wasn't clear enough... when I send a GET with basic auth credentials to api/login-token I receive the token and infos about it, as defined in RestfulAccessTokenAuthentication.class.php line 61-63.
Lets say, I have an app that logs in a user this way, after a successfulI login I want to get some information about the logged in user, but therefore I would need the uid to query api/user. So I was thinking that api/login-token should also give the uid, or to avoid another request, some more information about the user.

**Comment by amitaibu** [comment]
I see two options:

Add `uid` to login-token, or add a `/api/me` resource

**Comment by uniquename** [comment]
hehe... just thought the same about api/me, but it would be another request. I think I will go for more information on api/login-token. I could make a pull request later, if this is desired for the module design...

**Comment by amitaibu** [comment]
How about providing both options in your PR, and wining some extra Karma :wink:

**Comment by uniquename** [comment]
...k, i'll go for that;-)

**Comment by e0ipso** [comment]
Closed in favor of https://github.com/RESTful-Drupal/restful/pull/430

**Comment by jeff-h** [comment]
For anyone stumbling across this issue, there's now a recipe in the wiki for creating a `user/me` resource.
