### ISSUE TITLE
Set of variable (instead of all)

### ISSUE THREAD

**Issue by iStryker** [RESTful-Drupal/restful#440]
I am following the restful_example for variables.  I see the example sets an endpoint with all of the variables available.   I want to expose only a predefined set of them to the public.  How can I do this?

**Comment by e0ipso** [comment]
You will need to provide the `access callback` for the value field, or override the `->access()` method in the resource.

**Comment by iStryker** [comment]
I will try this.  Is this something that would be good to add to the examples?

**Comment by e0ipso** [comment]
Yes!

If you had the time to create a recipe for this in the recipes section in
d.o it would be _great_!

[image: http://]
Mateu Aguiló Bosch
[image: http://]about.me/e0ipso
http://about.me/e0ipso
