### ISSUE TITLE
Name-spacing and PHP 5.3

### ISSUE THREAD

**Issue by rbran100** [RESTful-Drupal/restful#442]
I know that in php 5.3.2 this format is failing for me:
https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/restful.module#L29

I can't find an example of Namespacing with the preceding slash like that in the docs but I assume it has it's advantages.  I thought all of this was introduced in 5.3 but for some reason this is failing for me, if I remove the preceding slash everything is golden but with it is_callable returns false.

Any ideas? 

Yes, I know my version of php is old.

**Comment by e0ipso** [comment]
I am no sure why that would happen…

**Comment by e0ipso** [comment]
According to http://3v4l.org/g62UF it should work wit no problems for your PHP version.

**Comment by rbran100** [comment]
@mateu-aguilo-bosch thanks for looking. Huh... Maybe the issue is in drupals drupal_autoload_class, I will debug further when back at a computer with 5.3

**Comment by e0ipso** [comment]
@rbran100 please reopen if you feel it needs to be reopened.
