### ISSUE TITLE
How to implement cookie authentication ?

### ISSUE THREAD

**Issue by yann-yinn** [RESTful-Drupal/restful#447]
Hello,
First this is actually a great project and thanks for the lot of work already done, that's impressive.

My question is about how to implements authentication by cookie ? I mean, which is the http request to be made to use a basic cookie implementation ?

**Comment by e0ipso** [comment]
You will need to have Drupal give you an authentication cookie either by manually logging in, or by accessing `https://example.org/api/login` with basic auth.

See https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/docs/api_url.md#working-with-authentication-providers

Please, if you figure this out, create a recipe in the recipe handbook for others to use. It would be a great way of appreciating the work done in the module (https://www.drupal.org/node/2399453)

**Comment by jeff-h** [comment]
I've put some notes in the wiki at https://github.com/RESTful-Drupal/restful/wiki/Authentication

**Comment by e0ipso** [comment]
Thanks again @jeff-h!
