### ISSUE TITLE
Views support?

### ISSUE THREAD

**Issue by krisgraham** [RESTful-Drupal/restful#453]
Is there any plan for views support? I realize it accomplishes a lot of the things that views is traditionally used for (creating lists of nodes), but adding views could still add a lot of power, especially since other modules already tie into it.
I'm already using views datasource but the way it's built can be pretty limiting for anything other than simple views (such as incorporating facets or multifields, field collections, etc.) and I would prefer to use this project, if possible.

**Comment by amitaibu** [comment]
Views support won't be added to core of RESTful, as there's already a Data base provider that allows building your own query. Using Views would probably be an overkill, since you'll be using only it's query builder part - but the output itself is by RESTful.
