### ISSUE TITLE
Equivalent of Targeted Actions?

### ISSUE THREAD

**Issue by edhollinghurst** [RESTful-Drupal/restful#459]
I just wondered whether there is an equivalent way of implementing 'targeted actions' that are provided by the Services module? For example, a password reset request from a user.

Any advice would be much appreciated.

**Comment by amitaibu** [comment]
Every "action" (which is in fact a hook_menu() that returns JSON) can be created with a REStful resource. The advantage of using RESTful would be that it does a lot of the heavy needed:

1) Declare the hook_menu()
2) Authenticate the user if needed
3) Cache the response if applicable
4) Throw clear errors when needed
5) Format the response in JSON, HAL+JSON, or others

Hope it helps :)

**Comment by edhollinghurst** [comment]
Wow.. that's really cool :+1: Never imagined it would be that easy.

**Comment by edhollinghurst** [comment]
Is there any chance you could explain how you would authenticate a user for a custom action?

Thanks!

**Comment by amitaibu** [comment]
Should be as simple as [this](https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/modules/restful_example/plugins/restful/node/articles/1.0/articles__1_0.inc#L11-L12) line(s)

**Comment by edhollinghurst** [comment]
Oh yes... thanks!
