### ISSUE TITLE
Add missing documentation for IETF API-Problem

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#52]
This is a follow up for #49

**Comment by e0ipso** [comment]
This could be a good novice task.

We need to do some Google and copy and paste the appropriate information in the following HTML static pages:
- help/problem-instances-bad-request.html
- help/problem-instances-flood.html
- help/problem-instances-forbidden.html
- help/problem-instances-gone.html
- help/problem-instances-service-unavailable.html
- help/problem-instances-unauthorized.html
- help/problem-instances-unprocessable-entity.html
- help/problem-instances-unsupported-media-type.html
