### ISSUE TITLE
Documentation for cross domain authentication

### ISSUE THREAD

**Issue by doodirock** [RESTful-Drupal/restful#528]
First off, amazing modules.  Building custom APIs has been a joy!  I currently have an app that runs on another domain EG: 

www.drupal-install.com

www.app-here.com

Are there any examples out there on how to have users log-in to drupal via other domains?  I didnt see anything in the readme and cant really find any examples out there.  I know RESTws lets you log in with  the restws user, but this is completely impractical.  Id rather find a method for a user to log in with their own credentials via IONIC or off site angular app.  Thanks again for the amazing work!

**Comment by amitaibu** [comment]
Check the "yo hedley " project,  which scaffolds a fully decoupled Drupal
with an angular client. Login with access token is part of it

**Comment by doodirock** [comment]
Thanks @amitaibu 

This works well cross domain I assume?  I'll give it a whirl today!

**Comment by amitaibu** [comment]
> This works well cross domain I assume?

Yes, because you authenticate using an access token, not cookies. You just need to enable CORS from your server (this is taken care of by hedley)

**Comment by e0ipso** [comment]
Also, your browse will make a pre-flight OPTIONS call before making the actual call. RESTful should respond withe the allowed origins header.

To configure that, use the `allowed_origin` key in the plugin definition.
