### ISSUE TITLE
Allow only specific methods

### ISSUE THREAD

**Issue by badri** [RESTful-Drupal/restful#529]
Hi
Is it possible to create resources which allow only specific methods, like "I can do only GET of these users" for example? How do I impose that constraint?

**Comment by e0ipso** [comment]
Can you elaborate? I am not sure what you are trying to accomplish.

**Comment by amitaibu** [comment]
This is controlled by the $controller - you can see it in action in
different example resources

**Comment by amitaibu** [comment]
See example - https://github.com/RESTful-Drupal/restful/blob/f0f981a8552a8c8b429bce2991d06e551661adff/tests/modules/restful_test/plugins/restful/node/test_articles/1.4/RestfulTestArticlesResource__1_4.class.php#L10-L23
