### ISSUE TITLE
Properties that are Lists of content return null when empty, should return empty array?

### ISSUE THREAD

**Issue by mpetrovic** [RESTful-Drupal/restful#531]
When a property is expected to return multiple items (i.e. taxonomy terms on an entity), restful returns null if a given entity has no items. 

It would be cleaner for consumers if these properties returned an empty array. Consumers would be able to interact with it the same, regardless of whether it has content or not. 

Currently, extra checks are required to make sure it's not NULL, or to initialize it if it is, which is messy.

**Comment by iStryker** [comment]
I think this is correct.  It should return NULL.  From what I understand, this is how APIs work.  It is not much extra work to check if it is NULL or not.

**Comment by e0ipso** [comment]
I agree. We should not be coding the backend based on the awkwardness of javascript with variable polymorphism, since we don't want to favor a single frontend technology. 

Besides, it makes sense to me to have a NULL value if there is nothing to show.

**Comment by amitaibu** [comment]
> Besides, it makes sense to me to have a NULL value if there is nothing to show.

:+1:
