### ISSUE TITLE
Taxonomy term is an object instead of array?

### ISSUE THREAD

**Issue by timwood** [RESTful-Drupal/restful#532]
In a node-based API, I was attempting to customize the field output of a referenced taxonomy term using a function similar to imageProcess from some of the example code that ships with the module. Unfortunately when I try this I get the following error:

> Argument 1 passed to RestfulBase::isArrayNumeric() must be an array, object given

When debugging the variable output seems to be an array of the referenced terms but each term is an object instead of another array. In comparison when debugging the variable output for image (file entity) seems to be an array and each file is another array, not an object (screenshots from Krumo below). Any idea what might be causing this? Should I convert the objects into an array as suggested in https://github.com/RESTful-Drupal/restful/issues/353#issuecomment-80144333 ?

This is the code I'm using:

``` php
    $public_fields['categories'] = array(
      'property' => 'field_categories',
      'process_callbacks' => array(
        array($this, 'termProcess'),
      ),
    );
```

``` php
  protected function termProcess($value) {
    if (static::isArrayNumeric($value)) { 
      $output = array();
      foreach ($value as $item) { 
        $output[] = $this->termProcess($item);
      } 
      return $output;
    } 
    return array(
      'id' => $value['tid'],
      'self' => $value['uri'],
      'label' => $value['name'],
    );
  }
```

Term:
![screen shot 2015-06-12 at 3 21 09 pm](https://cloud.githubusercontent.com/assets/91050/8138223/ee5e21d8-1116-11e5-97b1-67ae1b24403f.png)

File:
![screen shot 2015-06-12 at 3 22 24 pm](https://cloud.githubusercontent.com/assets/91050/8138227/f75ed502-1116-11e5-90e6-2adfe7df328f.png)

I'm using RESTFul module version 1.0 release from Drupal.org. Thanks for any help.

**Comment by timwood** [comment]
Looks like the suggestion in https://github.com/RESTful-Drupal/restful/issues/353#issuecomment-80144333 works! Also, I didn't realized the term doesn't include an uri or url, so obviously that field doesn't work in the second part of my code.

Still curious if anyone knows why the term object is so different.

Also, is there some recommended way to output a link to a corresponding API for referenced objects. Like if I had an API of terms or image file entities?

**Comment by e0ipso** [comment]
@timwood the recommended way is to create an extra resource for taxonomy terms and use it inside your node resource.

In your taxonomy term resource you can define the exact output that you want inside your node.

There is an example exactly about that in https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/modules/restful_example/plugins/restful/node/articles/1.5/RestfulExampleArticlesResource__1_5.class.php#L21-L26

Thanks for contributing to the issue queue!
