### ISSUE TITLE
Fatal error: Call to a member function value() on null in RestfulEntityBase.php on line 393

### ISSUE THREAD

**Issue by wundo** [RESTful-Drupal/restful#533]
This happens when I add non-required text field in my \RestfulEntityBaseNode::publicFieldsInfo() implementation.

It happens on the latest dev from drupal.org (datestamp = "1433146082")

Adding the following to the RestfulEntityBase.php fixed it:

``` php
      if (method_exists($sub_wrapper, $method)) {
        $value = $sub_wrapper->{$method}();
      }
      else {
        return NULL;
      }
```

Am I missing something or should I submit a PR?

**Comment by amitaibu** [comment]
I believe you should actually get a 500 error from entity API `property foo doesn't exist` (or something similar).

**Comment by wundo** [comment]
@amitaibu the property exists and I can see it doing a $node load and them a kpr

**Comment by wundo** [comment]
this is how it shows in dpm: ![screenshot 2015-06-17 16 28 46](https://cloud.githubusercontent.com/assets/113942/8216602/f643e568-150d-11e5-958b-ba9667725e5c.png)

**Comment by amitaibu** [comment]
The property should be defined for the EntityMetadataWrapper (`hook_entity_property_info`)
