### ISSUE TITLE
Documentation: How to handle multiple versions of the same resource

### ISSUE THREAD

**Issue by wundo** [RESTful-Drupal/restful#534]
I remember @mateu-aguilo-bosch mentioning about multiple versions support during Drupal Developer Days in Montpellier but I cannot find any mention about how to handle it in the documentation :(

Can someone help out?

**Comment by amitaibu** [comment]
To create versioned resources see the example module (e.g. the `articles` resource) -- https://github.com/RESTful-Drupal/restful/tree/7.x-1.x/modules/restful_example/plugins/restful/node/articles

To access the resources -- https://github.com/RESTful-Drupal/restful#getting-the-default-restful-handler-for-a-resource

**Comment by wundo** [comment]
I've just figured out how to do it looking at the source code, I will submit a PR (the documentation only mentions the minor_version)

**Comment by wundo** [comment]
Thanks @amitaibu
