### ISSUE TITLE
custom GET parameters

### ISSUE THREAD

**Issue by badri** [RESTful-Drupal/restful#536]
Hi
How do I add custom GET parameters like

`GET /endpoint/123?locale=en` other than the usual ones like "solr" and "filter".

**Comment by amitaibu** [comment]
Not sure what you mean? to access the GET params you can use `$this->getRequest()`

**Comment by jeff-h** [comment]
To be slightly more specific, you can get the URL parameters by the following:

``` php
$this->getRequest()->getParsedInput();
```
