### ISSUE TITLE
Minimum PHP version?

### ISSUE THREAD

**Issue by timwood** [RESTful-Drupal/restful#545]
What is the minimum PHP version for the RESTFul module? I tried using it in a PHP 5.3.2 environment (I know, it's ancient) but it fails to register menu paths and then responds with 404 to everything under /api. Tons of undefined index notices including this one: "Undefined index: hook_menu in restful_menu() (line 141 of ...restful.module).

Everything worked in a 5.3.10 environment.

**Comment by e0ipso** [comment]
Gasp! 5.3.2 Hehe

Are you using 7.x-1.x?

**Comment by timwood** [comment]
Yes, 7.x-1.0 release from D.O.

**Comment by timwood** [comment]
So anyone with experience running this module on PHP 5.3.2?

**Comment by Lowell20** [comment]
php 5.3 has been in end of life for over a year now, and php 5.4 only has one more month of security support. It is time to move to php 5.5, even better to give a little breathing room move to php 5.6.

see http://php.net/supported-versions.php

**Comment by timwood** [comment]
Thanks @Lowell20. I was able to confirm that the RESTFul module doesn't work with PHP 5.3.2.
