### ISSUE TITLE
Documentation - Example of implementation

### ISSUE THREAD

**Issue by heylookalive** [RESTful-Drupal/restful#546]
Hi, in addition to the existing documentation is there anything out there which gives a guide or example as "here's my module with some methods, this is how you use restful to provide an API"?

**Comment by e0ipso** [comment]
Maybe what you are looking for is the `restful_example` submodule inside the `restful` module.

**Comment by heylookalive** [comment]
Thanks, is there anything out there that's more step by step? Failing that in addition to the submodules are there any other contrib modules using restful?

**Comment by heylookalive** [comment]
@edhollinghurst pointed me to a blog post he wrote, exactly what I was after http://www.edhollinghurst.com/blog/getting-started-with-restful.html

**Comment by jeff-h** [comment]
Hey, thanks for putting that link here :)

**Comment by salientknight** [comment]
The above link is dead now.
