### ISSUE TITLE
Some basic (howto) questions.

### ISSUE THREAD

**Issue by theodorosploumis** [RESTful-Drupal/restful#573]
I am investigating the possibility to use this module for an advanced REST api for a Drupal 7.x distribution. It has many chances to be chosen as I can see it really respects the best REST practices out there. I 've already read all the docs here and on D.O.

So, I have some serious questions about its functionality. 

A yes/no is perfect if anyone could answer it (and this could also be written on the README.md too!)
1. ~~Does it support only MySQL databases? If I use **Postgres** or another sql database could I write my own class/method to use the module?~~
2. ~~Does it respect **other modules hooks**? Eg for permissions (eg field_permissions), for fields display, field validation, rdf support etc?~~
3. ~~Is it going to be continued for **8.x also**? I can see the branch but wanted to here about it officially.~~
4. ~~Since the fields are declared in (php) code could someone **combine, reuse etc fields** on the same plugin settings file? Eg use the title field twice but with different label.~~

Thanks!

**Comment by e0ipso** [comment]
> Does it support only MySQL databases? If I use Postgres or another sql database could I write my own class/method to use the module?

It supports any infrastructure supported by Drupal.

> Is it going to be continued for 8.x also? I can see the branch but wanted to here about it officially.

Yes. There will be an 8.x branch.

**Comment by e0ipso** [comment]
I hope that solves your questions.

Thanks for contributing to the issue queue.
