### ISSUE TITLE
Ability to sort by random

### ISSUE THREAD

**Issue by kzoltan** [RESTful-Drupal/restful#576]
Based on this https://www.drupal.org/node/1343708 its possible to have random ordering in EFQ
Now in Resful it isn't 
[my.restful.tld/endpoint?sort=random]()
now this is normal this not to work.

What would it be the best aproach to be able to achieve this?

If I saw right I could alter the `queryForListSort` function but since random isn't a field it looks a bit strange

**Comment by e0ipso** [comment]
Overriding `queryForListSort` in your own resource is the way to go!

If you end up doing this, maybe you can contribute back your experience in the form of a recipe?

https://www.drupal.org/node/2380679
