### ISSUE TITLE
Add a better delivery callback.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#58]
Using `drupal_json_output` as our delivery callback overwrites the `Content-Type` header hardcoding it to `application/json`. We want it to respect our custom `Content-Type` headers as long as it's of type json (`application/hal+json`, `application/problem+json`, …).

**Comment by amitaibu** [comment]
You are right, we need to have our own delivery callback + add a test to prevent regression.

**Comment by amitaibu** [comment]
Done
