### ISSUE TITLE
1.x User entity failing to load picture

### ISSUE THREAD

**Issue by heylookalive** [RESTful-Drupal/restful#591]
Extending out of RestfulEntityBaseUser, I'm attempting to get at the picture property on the user entity, though when I do this (only this, without any process callbacks) I get a 500.

"Unknown data property picture."

If I do a regular user load, entity load or try getPropertyInfo on a wrapper outside of the restful module I can see it. Really not sure what's going on here :/

**Comment by heylookalive** [comment]
Found the problem which is with Entity API not defining all of the properties for the user entity. Issue is not with RESTful.

https://www.drupal.org/node/2224645

**Comment by e0ipso** [comment]
@heylookalive you can expose the user entity properties to RESTful (and Entity API) with something similar to:

``` php
/**
 * Allow modules to alter metadata about entity properties.
 *
 * @see hook_entity_property_info()
 */
function hook_entity_property_info_alter(&$info) {
  $properties = &$info['node']['bundles']['poll']['properties'];

  $properties['picture'] = array(
    'label' => t("Picture"),
    'description' => t("The user's avatar."),
    'type' => 'file',
  );
}
```

If you are able to expose the picture, can you post a recipe in https://www.drupal.org/node/2399453?

**Comment by heylookalive** [comment]
Pretty much what's happened, I grabbed an amount of things from the referenced patch:
https://github.com/lohi-io/comstack_pm/blob/7.x-1.x/modules/comstack_pm_rest_api/comstack_pm_rest_api.module#L20

Might also be worth knowing what it is I'm up to. I'm creating a contributed project which will provide a fairly full API via RESTful:
https://rawgit.com/lohi-io/comstack_pm/7.x-1.x/modules/comstack_pm_rest_api/docs/rest-api.html

Once done I'll write up a series of blog posts on it and using RESTful.
