### ISSUE TITLE
Integrate with "Entity validator"

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#60]
[Entity validator](https://github.com/Gizra/entity_validator) is a new (and still under lots of development) module we work on in Gizra, that I can think compliment RESTful, when it comes to validating a created/ updated entity.

cc @mateu-aguilo-bosch

**Comment by e0ipso** [comment]
Oh! That's in line with the Entity constraints in D8. Are you familiar with them? Are you leveraging those?

The concept in general is very sexy, but it can get hairy.

**Comment by amitaibu** [comment]
> Entity constraints in D8. Are you familiar with them?

Yes, I know it. But no we're not using it, but we're not very far from the idea -- small methods that know how to validate a very tiny task. Still until D8, this can feel the gap.

(as a side note I can definitely see RESTful for D8 as well, since the REST module's concept is more inline with RestWs rather than RESTful).
