### ISSUE TITLE
Pulse the community opinions on decoupling Drupal.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#61]
Maybe this is worth some reading/talks.

https://groups.drupal.org/headless-drupal

**Comment by amitaibu** [comment]
Good idea. I was also advocating RESTful and [Zariz](https://github.com/Gizra/zariz) to anyone willing to hear about it in DrupalCon Austin. Maybe even to ones that didn't want to hear about it ;)

**Comment by amitaibu** [comment]
@c4rl oh, somehow I missed telling _you_ about RESTful. Maybe because we were busy talking about Ubercart for D6?! ;)

**Comment by amitaibu** [comment]
Posted some Headless Drupal posts in that group. I think RESTful is getting some attention now :)
