### ISSUE TITLE
1.x Sub-resources

### ISSUE THREAD

**Issue by heylookalive** [RESTful-Drupal/restful#610]
Sorry, another issue! What would be the best way of creating an endpoint such as:
GET /api/v1/cs-pm/conversations/{conversation_id}

But also have a URL off of it that would get a list of referenced message entities?
GET /api/v1/cs-pm/conversations/{conversation_id}/messages

Thinking about it should I create a new endpoint that lives at that second URL, in the resource plugin .inc have the resource be /api/v1/cs-pm/conversations/%/messages (wildcard there is a guess), and then it's a matter of working out how to pass that ID into the getList query function and alter it?

**Comment by e0ipso** [comment]
To have custom routes you can use `hook_menu => FALSE` in your plugin and wire it manually implementing `mymodule_menu()`. You will need to have the page and delivery callbacks that RESTful uses.

See `restful_menu()` for an example.

**Comment by heylookalive** [comment]
Are there any examples of how to go about this? I can see hook_menu but that doesn't give the best idea on how to mess with the URL structure.

I've tried having an endpoint at:
/api/v1/cs-pm/conversations

And then another at:
 /api/v1/cs-pm/conversations/%/messages

The second has "menu_item" path set to that URL, though when throwing a request at that URL (second one) the first is jumping in and grabbing the request instead of the second.

**Comment by e0ipso** [comment]
The best example that you can look at is `restful_menu()`. I don't think that you'll find anything more specific, since I am not sure if mixing entity types makes sense.

**Comment by heylookalive** [comment]
OK will dig in, I think sub-endpoint is a better way of describing it than what I said previously. It's more about URL structure where you want to get message entities via an entity reference id in the URL. Can we re-open this? I'll figure out something as this is a requirement of the API and I'm not switching to another module :)

**Comment by e0ipso** [comment]
@heylookalive feel free to re-open, but I think that this code should live in the implementator's module.

What's your thought?

**Comment by heylookalive** [comment]
Hmm I'll leave that call up to you. This is something that once it's known it's easier for others to do, that said the one thing that would be good to have in RESTful is the ability to grab an ID from a URL.

I've got two cases for how sub endpoints work.

The first is that you've got an endpoint like:
<code>/conversations</code>

You can GET that URL and get a list of entities, you can add an integer on to the end of the URL to get a specific entity, and then you can perform an operation against that entity via a sub endpoint like...
<code>/conversations/1/publish</code>

At this point I'll refer you to my API documentation which has examples of all this:
https://rawgit.com/lohi-io/comstack_pm/7.x-1.x/modules/comstack_pm_rest_api/docs/rest-api.html

This URL (<code>/conversations/1/publish</code>) will use the same endpoint and have a custom controller path defined which points to a specific function. I've achieved this simply by entering things into the <code>controllersInfo</code>:
https://github.com/lohi-io/comstack_pm/blob/7.x-1.x/modules/comstack_pm_rest_api/plugins/restful/comstack_message_types/conversations/1.0/ComstackPMConversationsResource__1_0.class.php#L30

The second is where you want to have a full endpoint off of another endpoint:
<code>/conversations/1/messages</code>

The purpose of this is to get a list of messages within a conversation, the conversation ID being 1. This was slightly more complicated. This required a custom hook_menu entry to force <code>restful_menu_process_callback</code> to use a particular handler.

https://github.com/lohi-io/comstack_pm/blob/7.x-1.x/modules/comstack_pm_rest_api/comstack_pm_rest_api.module#L33

The resource is defined with a wildcard in the path:
https://github.com/lohi-io/comstack_pm/blob/7.x-1.x/modules/comstack_pm_rest_api/plugins/restful/messages/conversations/1.0/messages__conversations__1_0.inc#L8

That alone lets our sub endpoint kick in.

We're now at the point in the (very long) story where we want to grab the entity ID from the URL. To do this I've created a custom function which will grab it:
https://github.com/lohi-io/comstack_pm/blob/7.x-1.x/modules/comstack_pm_rest_api/plugins/restful/messages/conversations/1.0/ComstackPMConversationsMessagesResource__1_0.class.php#L28

This is what could be good to have in RESTful.

See it in use here:
https://github.com/lohi-io/comstack_pm/blob/7.x-1.x/modules/comstack_pm_rest_api/plugins/restful/messages/conversations/1.0/ComstackPMConversationsMessagesResource__1_0.class.php#L92

**Comment by e0ipso** [comment]
Regarding your first point

> This URL (/conversations/1/publish) will use the same endpoint and have a custom controller path defined which points to a specific function

`/conversations/1/publish` is not a RESTful design. That is RPC (which is fine as well). In REST you don't alter state of `conversation:1` with a `GET` method. If you want to alter `conversation:1` you should issue a `PATCH /conversations/1 { "status": 1 }`.

For the second point, I fail to see the difference between `/conversations/1/messages` and `/messages?filter[conversation]=1` other than the URL structure.

**Comment by heylookalive** [comment]
Yep could do that on both counts. 

The theory results in the same thing, I feel this makes things clearer in terms of interacting with the entity and doesn't require as much knowledge about the data structure (but that's neither here nor there). There's precedence of REST APIs that are designed in this way, GitHub for example.

For the messages within a conversation this is to hammer home that messages belong to conversations though yes could be achieved with a filter. Part of this is being obvious, vanity and the challenge.
