### ISSUE TITLE
"fields" and "properties" terminology

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#624]
This module's usage of the terms "fields" and "properties" doesn't seem to conform to the usual Drupal meaning of these terms.

In the most basic examples in the documentation for overriding `publicFieldsInfo` we're adding as "public_fields" both actual fields (such as `body`) and entity properties (such as `author` and `created`).

Worse still, we're then seeing array keys called `property` and `sub_property`.

I'm confused! If the terminology is in fact carrying different meanings here, could someone explain what they mean in this module?

**Comment by e0ipso** [comment]
I don't think I understand your question. Is there a point in the documentation where to point to? Is this about the code variable names?

**Comment by jeff-h** [comment]
Sorry for the lack of context.

In https://github.com/RESTful-Drupal/restful#restful_custompluginsrestfulrestfulcustomresourceclassphp I see the following:

``` php
    $public_fields['body'] = array(
      'property' => 'body',
      'sub_property' => 'value',
    );
```

In this, we're adding the `body` field to $public_fields... all good :) But the two keys confuse me, as body is not an entity property, it's a field. And I'm not sure what sub_property is.

Then, in the (very helpful) blog post http://www.edhollinghurst.com/blog/getting-started-with-restful.html I see the following:

``` php
    $public_fields['author'] = array(
      'property' => 'author',
      'sub_property' => 'name',
    );
```

An entity's author is not a field, it's a property (in the Drupal sense of the word), but here it's added into $public_fields.

I'm fine if `public_fields` is simply meaning "HTML form input fields that are publicly accessible on the front end", but on the Drupal side, treating both entity fields AND properties as the same thing makes me nervous about things like how `?filter[blah]` would end up filtering this stuff (EFQ needs to know the difference, for example).

I'm very new to RESTful so sorry if none of this makes enough sense. Hugely grateful for your work though!

**Comment by amitaibu** [comment]
Indeed the terminology isn't clear. In fact also in D7 it wasn't. In D8 we now have a field (= property) and a configurable field (= field)

I think we should keep the word property, just because replacing it will cause a bigger break when moving from 1.x to 2.x
