### ISSUE TITLE
Javascript Forms API

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#644]
Would it be feasible to create a separate project which aims to (at least partially) implement Drupal's forms API in one or more of the more popular Javascript frameworks (e.g. Angular, Backbone, Ember)?

Thus, we'd have an out-of-the-box way of turning `$public_fields['x']['discovery']` information into suitable markup without having to reinvent the wheel each time.

**Comment by e0ipso** [comment]
That was one of the original intents after the `'form_element'` in the `discovery` effort.

Would you be able to tackle this?

**Comment by e0ipso** [comment]
That would be fantastic!

**Comment by jeff-h** [comment]
I've just come across [Backform](http://amiliaapp.github.io/backform/index.html) — pretty much exactly what I was thinking of, for Backbone^. As expected, it has its own expectations in terms of form field description metadata, so my current plan is to write a converter from RESTful's (i.e. entity API's) field data to Backform field data.

This could be done either:
- on the client side, in Javascript
- in a tiny module which perhaps subclasses `RestfulEntityBase`? Or some other class? Or a helper function for `publicFieldsInfo`?

My feeling is the second option is best, but I'm a little unsure what method to write and on which class. If you could provide a little architectural guidance on that front it would be very helpful. 

Perhaps over time this module could grow to cater for several front-end frameworks; I'm hoping there might be something analogous to Backform for Angular etc that we can leverage easily for the client side.

^ Of course, not everyone uses Backbone, but I do, so that's what RESTful should cater for lol

**Comment by jeff-h** [comment]
On reflection, I think the server-side is the wrong place to do this. 

a) it means the REST api output is being customised to suit one specific consumer. While in a lot of use cases this might be the case, it's not correct for REST, I imagine.

b) it's pretty easy to do on the client side. In Backbone for example, I'm just writing a conversion function to fire from inside the `parse()` ([see docs](http://backbonejs.org/#Collection-parse)) method of my fields collection (which is populated by asking for RESTful's discovery information i.e. with an `OPTIONS` call)

If we instead wanted RESTful to provide the discovery field info pre-formatted for Backform (for example), could we do it by implementing a new `Accept` header which returns the data formatted for the specified client framework?

**Comment by jeff-h** [comment]
I've implemented this client-side in my current project. If anyone is interested in what I did, feel free to add a comment on this issue.

Closing, since it's a client implementation detail, rather than a RESTful issue.

**Comment by e0ipso** [comment]
@jeff-h would it make sense to create a generic Backbone plugin that does this transformation? That way other people would just:
1. Download & install the plugin.
2. Configure the plugin with their resource info.
3. Profit.

**Comment by jeff-h** [comment]
It's a good idea — I'll refactor my code to be a little more generic. I'll be using it in a second project within the next month, which should drastically expand its scope, so I'll commit something up at that point.
