### ISSUE TITLE
Inject classes from plugin definition

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#65]
https://github.com/Gizra/restful/pull/53/files#r13242933

**Comment by e0ipso** [comment]
On second thought I don't think that we need this. I don't really see a use case where we may want to use a different authentication manager. The manager will just execute the authentication plugins in turns. I feel that if we can come up with something that the current authentication manager cannot do, we should accommodate that into the existing manager.

Feel free to re-open.
