### ISSUE TITLE
2.x: README: module dependencies: patches

### ISSUE THREAD

**Issue by alisonjo315** [RESTful-Drupal/restful#652]
The first Entity API patch under [Module Dependencies](https://github.com/RESTful-Drupal/restful/tree/7.x-2.x#module-dependencies) in the 2.x README was included in [Entity 7.x-1.6 (Feb 2015)](https://www.drupal.org/node/2437885) -- so maybe it doesn't need to be listed here anymore?

(I hit my head against a wall for a little while this afternoon trying to apply the patch -- I figured I was applying it wrong womehow, the first half-dozen times... I should've just looked at the file being patched and read the error messages more closely...)

Anyway, just a thought.  Thanks!

**Comment by kporras07** [comment]
Hi there, I think this commit: https://github.com/RESTful-Drupal/restful/commit/e159358a9d41251bb4e23d50f837bb74588c6d16 closes this issue.

**Comment by alisonjo315** [comment]
Indeed it does!  So prompt, too, only a day after I posted my issue.  Thanks for the update!!

**Comment by e0ipso** [comment]
Ah! Sorry I forgot to update the issue.

Thanks everyone to contribute.

**Comment by alisonjo315** [comment]
No worries, thanks for fixing!
