### ISSUE TITLE
Example of $.post();

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#656]
Apologies if this is so simple it should go without saying, but I'm not finding any docs on how to actually post back to Drupal i.e. to create a new entity.

I can do it using [CocoaRestClient](http://mmattozzi.github.io/cocoa-rest-client/) and hand-building the Request Body parameter key/value pairs, so I know my Drupal side of things is good.

However, I'm now trying out the simplest possible use case using jQuery's `$.post()`. I'd find it really helpful if someone could fill in the blanks for me in the following:

``` js
var data = [
  {fieldOne : "lorem"},
  {fieldTwo : "ipsum"}
];

$.post(
  'localhost/my-drupal-site/api/v1.0/blah'
  ... // What goes here?
);
```

**Comment by jeff-h** [comment]
For the record (thanks [Paw](https://luckymarmot.com/paw)):

``` js
jQuery.ajax({
    url: "http://mydrupalsite.com/api/v1.0/entity-endpoint-name",
    type: "POST",
    headers: {
        "Content-Type": "application/json",
    },
    contentType: "application/json",
    data: JSON.stringify({
        "property_one": "5",
        "property_two": "4",
        "etc": "abc"
    })
})
.done(function(data, textStatus, jqXHR) {
    console.log("HTTP Request Succeeded: " + jqXHR.status);
    console.log(data);
})
.fail(function(jqXHR, textStatus, errorThrown) {
    console.log("HTTP Request Failed");
})
.always(function() {
    /* ... */
});
```

**Comment by e0ipso** [comment]
@jeff-h maybe we can paste this in the recipes? https://www.drupal.org/node/2399453

**Comment by jeff-h** [comment]
There's a broader question about documentation over at https://github.com/RESTful-Drupal/restful/issues/650#issuecomment-144526626 My preference is to centralise it all here on Github, so I've put the above code into a new page under **Common scenarios & recipes** at https://github.com/RESTful-Drupal/restful/wiki

However, the decision really is ultimately up to you and @amitaibu  as the project owners, so let me know.

**Comment by jeff-h** [comment]
I'm really struggling with auth on this. The above code works fine if anon can create the entity, but I cannot seem to get a new entity created and attributed to a non-anon user. I'm using cookie auth, and my other REST calls prove the auth is working, but this just constantly 403's on me :(

Any ideas?

**Comment by e0ipso** [comment]
> However, the decision really is ultimately up to you and @amitaibu as the project owners, so let me know.

I don't have an strong opinion on this, but I lean towards drupal.org. Also, I think that @amitaibu also prefers drupal.org over wiki.

**Comment by e0ipso** [comment]
> Any ideas?

Are you sending the cookie with the request?

**Comment by jeff-h** [comment]
Yeah — I've xdebugged inside `createEntity()` and Drupal itself has authenticated — I can see `$GLOBALS['user']` has been correctly set with my logged-in user object.

**Comment by jeff-h** [comment]
I found the problem; I had not defined

``` php
  'authentication_types' => TRUE,
```

inside my $plugin definition. I had no idea this key even existed. It's rather nicely documented in the code itself, but it took me forever to find it! I've added it to the wiki at https://github.com/RESTful-Drupal/restful/wiki/Defining-your-own-RESTful-plugin
