### ISSUE TITLE
Token Auth: Refresh token unexpected behavior

### ISSUE THREAD

**Issue by lukewertz** [RESTful-Drupal/restful#666]
Please forgive the detailed nature of this bug. I'll include screenshots to try to make it more clear what is happening.

When an access token is generated (by visiting /login-token), the return contains both the `access` and `refresh` tokens.

![screen shot 2015-10-02 at 12 30 47 pm](https://cloud.githubusercontent.com/assets/110637/10251964/85560220-6902-11e5-9020-dbe9abe621c1.png)

If I then use my refresh token to generate a new access token, the refresh token I use is deleted (as expected), but the old access token is not deleted (which is unexpected).

![screen shot 2015-10-02 at 12 32 21 pm](https://cloud.githubusercontent.com/assets/110637/10251983/a3e99846-6902-11e5-9ff3-019e8f1e10ef.png)

When I then try to use my newly-created access token, I get unpredictable results (I get no refresh token and the old access token, even though I have a new access token):

![screen shot 2015-10-02 at 12 32 46 pm](https://cloud.githubusercontent.com/assets/110637/10252009/c193733a-6902-11e5-94c4-65d552587266.png)

The expected functionality would be that after I've used a refresh token, when I then use the new access token, I would get back the paired tokens (access and refresh) and that the DB would be cleaned up appropriately.

**Proposed fix:** I think this can be easily accomplished by deleting the paired access token [when the refresh token is deleted](https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/modules/restful_token_auth/plugins/restful/restful_token_auth/token_auth/refresh_token/1.0/RestfulRefreshTokenAuthentication.class.php#L50).

As an aside, it looks like there is no cleanup at all being done on the [entity reference table](https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/modules/restful_token_auth/includes/RestfulTokenAuthController.php#L31).

**Comment by e0ipso** [comment]
Sorry for not responding in time and manner to this one, I have had it in my bookmarks for a while.

Anyways, I'm glad to see that you are making progress in the right direction. Let's move the conversation to the PR thread.

**Comment by e0ipso** [comment]
https://github.com/RESTful-Drupal/restful/pull/671
