### ISSUE TITLE
2.x Fix JSON API DB Query for a single item.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#675]
We should not have an array of one item when viewing a single item.

`/api/db-resource/1234` should not return:

``` json
{
  "data": [{
    "attributes": {…}
  }]
}
```

But 

``` json
{
  "data": {
    "attributes": {…}
  }
}
```

**Comment by amitaibu** [comment]
Is that part of the spec?

**Comment by e0ipso** [comment]
Yeah

**Comment by e0ipso** [comment]
This is not an issue, it's working just fine.
