### ISSUE TITLE
2.x Token auth: No tokens returned

### ISSUE THREAD

**Issue by rafatwork** [RESTful-Drupal/restful#679]
Trying to get token authentication to work. When requesting an access token (api/login-token), I keep getting an empty result set. I can see that the restful_token_auth entities (access and refresh tokens) are being created however.

![capture](https://cloud.githubusercontent.com/assets/8710999/10425613/3a2ae94e-70d9-11e5-88c0-2bc22661dd90.JPG)

Anyone else experiencing this? Any ideas? Using the latest code.

**Comment by e0ipso** [comment]
Thanks for taking the time to report it. I will look into it as soon as I can. If you end up making any progress in the mean time, please let me know!

**Comment by rafatwork** [comment]
Spent quite some time trying to track it down, but no luck so far.
While doing so, I possibly found another minor bug though. In TokenAuthentication.php:

``` php
 *   options = {
 *     "paramName" = "access_token",
 *   },
```

I think should be

``` php
 *   options = {
 *     "paramName" = "access-token",
 *   },
```

In the param name, the underscore should be a dash. Otherwise, the access token is never found in TokenAuthentication->applies() (somewhere in request, underscores are replaced by dashes).

**Comment by e0ipso** [comment]
This should've been fixed.
