### ISSUE TITLE
access_callbacks polarity

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#691]
It seems the `publicFieldsInfo` key `access_callbacks` expects the callback to return `true` to **deny** access. This seems very counterintuitive to me... I'm not certain if there is a precedent in place in the entity API or something?

If it's not too late for RESTful v2 could you reverse that, so the callback returns `true` to **allow** access?

**Comment by e0ipso** [comment]
This is following node access rules. You have 3 possible values:
- ACCESS_ALLOW
- ACCESS_DENY
- ACCESS_IGNORE

See the actual values of the constants to make sure if that makes sense. Also, please review the wiki.

Thanks again for being all over the place!

**Comment by jeff-h** [comment]
Ah, thanks for the clarification. Makes complete sense, although I'm unsure why my boolean worked when those constants are strings or NULL...

``` php
define('NODE_ACCESS_ALLOW', 'allow')
define('NODE_ACCESS_DENY', 'deny')
define('NODE_ACCESS_IGNORE', NULL)
```

I was guessing they'd have been arbitrarily 0, 1 and 2 (hence boolean "working") but apparently not.

I've updated the wiki too.
