### ISSUE TITLE
Secondary (Non-Drupal) database; PR useful?

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#697]
I needed to define a resource which pulls data from a secondary database (defined in `settings.php`). It was pretty trivial to override `getQuery()` so instead of:

``` php
  /**
   * Get a basic query object.
   *
   * @return SelectQuery
   *   A new SelectQuery object for this connection.
   */
  protected function getQuery() {
    $table = $this->getTableName();
    return db_select($table)->fields($table);
  }
```

I have

``` php
  /**
   * Get a basic query object.
   *
   * @return SelectQuery
   *   A new SelectQuery object for this connection.
   */
  protected function getQuery() {
    $connection = $this->getConnection();
    $table = $this->getTableName();

    return Database::getConnection($connection->target, $connection->key)->select($table)->fields($table);
  }
```

and pull the connection from a new key in the plugin info array.

I was wondering if you'd like this in a PR or whether it's too specialised a case and too easily implemented as a one-off to be bothered. Let me know.

If not a PR, I'll stick it in the wiki recipes.

**Comment by amitaibu** [comment]
I think a wiki should be enough,  thanks

**Comment by jeff-h** [comment]
Cool — https://github.com/RESTful-Drupal/restful/wiki/Creating-a-resource-that-takes-data-from-a-secondary-database
