### ISSUE TITLE
Need 403 if no resource IDs are specified

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#698]
I need to disallow accessing an entire list of resources, but allow access when one or more specific IDs are provided e.g.
- `api/v1.0/myresource/1,5` should be allowed
- `api/v1.0/myresource` should **not** be allowed

What would be the best place in the code to make this happen? I tried overriding `public function access()` but as far as I can see when this is run the request hasn't been processed and I don't have access to the IDs (if any were supplied in the URL).

**Comment by amitaibu** [comment]
You should override the $controller which basically defines the allowed
routes.  So you will remove the empty string route.

**Comment by jeff-h** [comment]
Awesome, thanks! I hadn't had the need to discover any of the routing yet, but that's nicely implemented, like everything else in this module :) (thanks for all your work!)

As usual I've put a page in the docs :p https://github.com/RESTful-Drupal/restful/wiki/Defining-the-endpoint's-available-routes-(URLs)

**Comment by amitaibu** [comment]
:+1:
