### ISSUE TITLE
2.x Error when hitting the '/login' resource

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#701]
```
Fatal error: Maximum function nesting level of '100' reached, aborting! in /var/www/docroot/sites/all/modules/contrib/restful/src/Plugin/resource/Field/ResourceFieldBase.php on line 293
```

Although the cookie is sent back correctly.

**Comment by e0ipso** [comment]
This happens if JSON API is selected as the default formatter.

**Comment by e0ipso** [comment]
This was fixed

**Comment by ovidius72** [comment]
I'm having the same issue trying to get payment transactions from the Drupal commerce module, using a custom resource file. It happens either with JSON API or Simple Json
