### ISSUE TITLE
Proper place to put custom validation in RestfulDataProviderDbQuery-based resource?

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#716]
I have a resource which extends `RestfulDataProviderDbQuery` and need to add some simple (non-entity-field-based) validation on one of the public fields when doing `POST` or `PATCH`. I had kind of expected a forms-api-style `#validate` on RESTful's public fields, but couldn't find anything like that.

I got it working by overriding the `process` method and throwing a `RestfulBadRequestException` if my validation failed, but it felt like I was missing the correct way of doing this.

Could you tell me if there's a better place for this kind of one-off business logic?

**Comment by e0ipso** [comment]
You are probably looking for https://github.com/RESTful-Drupal/restful/blob/4df882832103a653b9a243127e8a2aa2fecb6222/plugins/restful/RestfulEntityBase.php#L18-L27.

I'm pretty sure I don't need to ask you, but please leave a note in the wiki with an example if that fixes your dilema.

**Comment by e0ipso** [comment]
Another candidate for your access callback is the controller itself. See https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/plugins/restful/RestfulBase.php#L868-L873

**Comment by jeff-h** [comment]
Adding a method to the field's `access_callbacks` would have been perfect. I tried for ages to make this work but simply couldn't get the callback to fire. Eventually I stepped back and looked for the obvious and realised that only `RestfulEntityBase` implements this! Since my resource extends `RestfulDataProviderDbQuery` it has no `access_callbacks`.

Is there any reason non-entity resources don't have `access_callbacks`?

A perhaps bigger issue is that I think the docs (as I've written them) are misleading in that they gloss over the fact that the vast bulk of the public field array elements are only available for entity-based resources.

I've just modified it to hopefully clarify that, but it would be great if you could see whether the v2 docs also need similar updating. I haven't played with v2 yet, so I'm not sure of its class hierarchy.

V1 docs page: https://github.com/RESTful-Drupal/restful/wiki/2.-Defining-the-public-fields-(1.x)#available-public-field-properties

v2 docs page: https://github.com/RESTful-Drupal/restful/wiki/2.-Defining-the-public-fields-(2.x)
