### ISSUE TITLE
Token auth question

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#721]
I have Drupal running RESTful on `domain-one.com` and my JS app running on `domain-two.com`. So cookies are out, and I'm implementing token auth.

A call to `api/login-token` returns something like:

``` js
{
  "access_token": "gY6ICdrXP4-SM6Rr8nMwEqvJ6DLvaj4-bVz26V6uYNU",
  "type": "Bearer",
  "expires_in": 86400,
  "refresh_token": "jSNFuCHqHHIavOA3U-jMr9008ca7P0l55LSOePak2wg"
}
```

Are there any security problems with storing the above in localStorage? It's no more dangerous storing the above locally than storing the session cookie, right?

**Comment by doodirock** [comment]
I've been storing mind in local as well.  This is common practice among most modern apis so I wouldnt worry to much about it.

**Comment by jeff-h** [comment]
Thanks for the reassurance! :)
