### ISSUE TITLE
PSR-4 Future support ?

### ISSUE THREAD

**Issue by rroblik** [RESTful-Drupal/restful#722]
Hi Lullabot !

Thanks for all the work done with this module, and all other on your website :).

I have a simple question : I know making a custom `restful` plugin is "supported" through `CTools` (as said in [your doc](https://github.com/RESTful-Drupal/restful#declaring-a-rest-endpoint))

But as `RESTful` Drupal module is OOP, is there any chance to see a _refactoring_ of the module to support PSR4 OOP style and `xautoload` under Drupal 7 ?

Regards

**Comment by e0ipso** [comment]
Have you checked RESTful 2.x? :-)

**Comment by rroblik** [comment]
Wow interesting !

Hum but some more questions :
Why dependency to `autoload` plugin is not in `.info` file? Because of `plug` ?

This version is really Drupal 8 oriented nice to see it but ... Is it because of that we need php 5.4 to use this version ? (I run an old 5.3.3 :( )

**Comment by e0ipso** [comment]
> Why dependency to `autoload` plugin is not in `.info` file? Because of `plug` ?

Yes, `plug` depends on `registry_autoload`.

> I run an old 5.3.3

Any excuse to update your old PHP is a good one.
