### ISSUE TITLE
Filter by sub property

### ISSUE THREAD

**Issue by edhollinghurst** [RESTful-Drupal/restful#724]
Is it possible to filter by a sub property?

For example, if I add the following field to my 'bookings' resource:

$public_fields['venue'] = array(
  'property' => 'field_event',
  'sub_property' => 'field_event_venue',
);

And then then go the the following URL:

http://mysite.com/api/v1.0/bookings/?filter[venue]=123

It applies the filter based on the event ID rather than the venue ID.

**Comment by e0ipso** [comment]
You are having the same issue that was detected here: https://github.com/RESTful-Drupal/restful/pull/720#issuecomment-153320300

`'sub_property'` is not intended for relationship traversing.
