### ISSUE TITLE
Avoid error message on empty property.

### ISSUE THREAD

**Issue by shushu** [RESTful-Drupal/restful#73]
`field_uuid` information taken from `getPublicFields()` does not include `property`.
It includes only `callback`.

```
      // Skip fields that doesn't have property configures, such as UUID field.
      if (!isset($info['property'])) {
        continue;
      }

      $property_name = $info['property'];

```

**Comment by amitaibu** [comment]
What error are you getting? (The `property` is set to `FALSE` by default)

**Comment by shushu** [comment]
![selection_114](https://cloud.githubusercontent.com/assets/99186/3312008/df6f7584-f6cb-11e3-84fd-240555c4eeb2.png)

**Comment by amitaibu** [comment]
> field_uuid information taken from getPublicFields() does not include property.

But I see it does -- https://github.com/openscholar/openscholar/pull/6048/files#diff-07a84f267f9ded25775667f3eeef3ff9R59
