### ISSUE TITLE
How do you manage the D.O. project?

### ISSUE THREAD

**Issue by theodorosploumis** [RESTful-Drupal/restful#733]
@e0ipso how to you push code and issues on D.O. from this repo? I see that the commits are also moving to the D.O. repo and that there is a "continuous sync" from the GitHub to D.O.

Are you using any special script for this?

I am interested on this as I have 2 projects on D.O. that are being developed on GitHub.

**Comment by amitaibu** [comment]
Just a simple push also to the d.o. repo :)

**Comment by theodorosploumis** [comment]
Thanks, we can close the issue if you like.
