### ISSUE TITLE
2.x!

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#750]
Congratulations on releasing v2 as the recommended release on d.o.!

I hope to start tidying up the wiki so it's all 2.x — would you be ok with me overwriting 1.x docs wherever they need to change? I don't see a lot of point maintaining the 1.x docs because if someone wants the legacy docs they can simply download the wiki repo and revert to an appropriate place in the commit history to get the v1 docs back. I'd put a note to that effect in the docs.

**Comment by e0ipso** [comment]
I would duplicate the pages and update the _2.x_ version, and leave the _1.x_ there (probably unmaintained). That way it helps seeing the differences between 1.x and 2.x.

Thank you again for all these efforts!!!

**Comment by jeff-h** [comment]
No problems — the thanks for all this is due your way not mine!
