### ISSUE TITLE
Log exception message in restful_menu_access_callback()

### ISSUE THREAD

**Issue by ademarco** [RESTful-Drupal/restful#751]
### Problem

When checking access to a resource fails due to `Drupal\restful\Exception\RestfulException` being caught in `restful_menu_access_callback()` developer has not information about what actually happened apart from a not-descriptive `403`.
### Solution

Log exception message on:

``` php
  catch (RestfulException $e) {
    // We can get here if the request method is not valid or if no resource can
    // be negotiated.
  }
```

Which would become:

``` php
  catch (RestfulException $e) {
    // We can get here if the request method is not valid or if no resource can
    // be negotiated.
    watchdog('restful', $e->getMessage(), array(), WATCHDOG_WARNING);
  }
```

**Comment by ademarco** [comment]
PR at https://github.com/RESTful-Drupal/restful/pull/752

**Comment by e0ipso** [comment]
I don't think that we should be logging client errors or misuses of the API. 4XX errors are not Drupal errors.

When a 4XX error in the API happens, Drupal is working as expected and delivering the appropriate content. Those are not considered errors from the Drupal point of view, and therefore they were excluded from logging (just as we don't log any other successful request).

Any further thoughts on this?

**Comment by ademarco** [comment]
Yeah, that makes sense actually still, during development, it could be useful to have some more insights on what exactly happened. Is there a "debugging mode" we can hook into in order to log more verbose error messages during development only? Or could that be something interesting to add?

**Comment by e0ipso** [comment]
I guess that the best way to log this is in the client side application. That being said I'd be open to add a debug mode, but I'm still unclear on how that would look like.

**Comment by ademarco** [comment]
Would be an option to just accompany the standard error message with the exception message? Like instead of:

``` json
{
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4",
    "title": "Access denied.",
    "status": 403,
    "detail": "Forbidden"
}
```

Something like:

``` json
{
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4",
    "title": "Access denied.",
    "status": 403,
    "detail": "Forbidden (No CSRF token passed in the HTTP header)."
}
```

Being `No CSRF token passed in the HTTP header` the exception message.

**Comment by ademarco** [comment]
Alternatively the following code:

``` php
  catch (RestfulException $e) {
    // We can get here if the request method is not valid or if no resource can
    // be negotiated.
    $response = restful()->getResponse();
    $output = _restful_build_http_api_error($e, $response);
    $response->setStatusCode($e->getCode());
    $response->setContent(drupal_json_encode($output));
    $response->send();
    exit();
  }
```

Will produce:

``` json
{
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1",
    "title": "No CSRF token passed in the HTTP header.",
    "status": 400,
    "detail": "Bad Request"
}
```

Which actually describes what happened in a more correct way than a `403`.

We could wrap those lines into a reusable method, since I just took it from `restful_menu_access_callback()` for a quick try out, but it could be useful in more than a couple of situations.

**Comment by ademarco** [comment]
I've updated PR #752 with the proposal above.

**Comment by e0ipso** [comment]
This was closed and merged in https://github.com/RESTful-Drupal/restful/commit/3d94c6e463b1fe24f7a1311a216b01967e3ef36d.
