### ISSUE TITLE
Catch UnauthorizedException and return 401 if the user not authenticated in restful_menu_access_callback()

### ISSUE THREAD

**Issue by xuxucode** [RESTful-Drupal/restful#753]
The `403 Forbidden` status is returned if the user not authenticated, there is no way to know whether the user not authenticated or denied.
It's useful if an appropriate `401 Unauthorized` status returned, for example: the mobile apps can refresh access token automatically if a 401 status code returned.

**Comment by ademarco** [comment]
This is being discussed at #751, we can close this issue as duplicate.

**Comment by xuxucode** [comment]
Oh, yes, but leave it open temporarily as a use case :-)

**Comment by ademarco** [comment]
Sure!

**Comment by xuxucode** [comment]
close in favor of #751.
