### ISSUE TITLE
2.x PSR-4 namespaces not found using profiles

### ISSUE THREAD

**Issue by RoySegall** [RESTful-Drupal/restful#755]
I'm working on the midburn project, the local branch in Israel of the Burningman community, and I would like to use the 2.x branch. I'm having an installation profile which in the installation i get errors such as:

```
WD php: Warning: class_implements(): Class                           [warning]
\Drupal\restful\RateLimit\Entity\RateLimitController does not exist
and could not be loaded in entity_entity_info_alter() (line 1474 of
/home/travis/build/Midburn/burning/burning/modules/contrib/entity/entity.module).
WD php: Warning: in_array() expects parameter 2 to be array, boolean [warning]
given in entity_entity_info_alter() (line 1474 of
/home/travis/build/Midburn/burning/burning/modules/contrib/entity/entity.module).
WD php: Warning: class_implements(): Class                           [warning]
\Drupal\restful\RenderCache\Entity\CacheFragmentController does not
exist and could not be loaded in entity_entity_info_alter() (line
1474 of
/home/travis/build/Midburn/burning/burning/modules/contrib/entity/entity.module).
```

And the crème de la crème is:

```
Fatal error: Class 'Drupal\restful\Plugin\resource\Decorators\CacheDecoratedResource' not found in /home/travis/build/Midburn/burning/burning/modules/contrib/restful/restful.entity.inc on line 71
```

This is the PR as a reference - https://github.com/Midburn/burning/pull/10.

Am I missing something?

**Comment by e0ipso** [comment]
You need to add PSR-4 to your installation profile with registry autoload.

Additionally you can add global formats as described in: https://www.drupal.org/node/2498195

**Comment by amitaibu** [comment]
@RoySegall Let's add in the README a section with the needed config for installation profiles.

**Comment by RoySegall** [comment]
My mistake. I was missing a dependency which not failed my installation profile. Something else i'm struggling is the api discovery but this could be a setting again. 

10x for the reply. You can close this one.

**Comment by e0ipso** [comment]
>  I was missing a dependency

Which one? Someone may end up in this thread and wonder how you fixed it :-P

**Comment by RoySegall** [comment]
Plug. In a clean 2.x installation, when going to /api do you see all the available plugins?

**Comment by e0ipso** [comment]
> when going to /api do you see all the available plugins?

You should. If it's not working, then we should file a bug :smile:

**Comment by RoySegall** [comment]
Yeah, line 67 in restful.module I did a small hack:

```
$path = empty($plugin_definition['menuItem']) ? $base_path : implode('/', array($base_path, $plugin_definition['menuItem']));
```

which allowed me to access `api` and see all the plugins. I need to see why this happens and what going on in 1.x. But I can confirm we have a bug.
