### ISSUE TITLE
2.x ignoring "Advanced" config options

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#759]
At `admin/config/services/restful` you can turn on or off the following:
- login resource
- user resource
- discover resource

I had a look through the 2.x code and couldn't see these variables being used anywhere other than in the `.install` and the UI form. Is this a simple oversight? I'd add a PR but I'm not actually sure how to conditionally enable a class which is described by annotations.

**Comment by e0ipso** [comment]
Gosh! That is `TRUE`!

We need to do something similar to the upload resource. Thanks for reporting!

**Comment by e0ipso** [comment]
Done. https://github.com/RESTful-Drupal/restful/commit/194ef8ddbae93f325052504b8567cf38772b9e66

Thanks for reporting!
