### ISSUE TITLE
users endpoint returning invalid JSON [2.x]

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#761]
Not sure if this is a problem specific to my site, but when I call the default `users` endpoint, I get an invalid JSON response. The broken JSON response is missing its closing `}`.

It only happens when I have more than 25–30 users in the response, which made me think it was somehow related to a specific username, but again I couldn't see anything unusual in the username that breaks the response.

Gives valid JSON: `api/v1.0/users?range=26&sort=-id`
Gives invalid JSON: `api/v1.0/users?range=27&sort=-id`

Gives valid JSON: `api/v1.0/users?range=28`
Gives invalid JSON: `api/v1.0/users?range=29`

(Site has ~16,000 users)

Could someone have a quick test of this on their site and tell me if it's my problem? :)

**Comment by jeff-h** [comment]
Intriguingly the error seems to be due to the size of the response. On a hunch I went in and maxed out the length of three of the usernames, and now the previously-working URL `api/v1.0/users?range=28` is no longer valid JSON, missing the final `}`.

**Comment by jeff-h** [comment]
It breaks as soon as the response goes over 8,000 characters.

**Comment by doodirock** [comment]
Just ran into this today myself.  Invalid Json for even the smallest requests.  Every single resource is broken without the final `}`.

I'm using the latest version. 

However with me the character limit doesnt seem to matter.  Even if I make a tiny request it breaks.

Below is request on one term

`{"data":{"type":"playing","id":"719","attributes":{"id":"719","label":"Far Cry 4","self":"http:\/\/dev-test.pantheon.io\/api\/v1.0\/playing\/719"},"links":{"self":"http:\/\/dev-test.pantheon.io\/api\/v1.0\/playing\/719"}},"links":{"self":"http:\/\/dev-test.pantheon.io\/api\/v1.0\/playing\/719`

**Comment by doodirock** [comment]
Just  an update @jeff-h.  Ive tried all different type of json, enabled/disabled module, check unchecked all options and still have the problem.  Let me know if you run into any success

**Comment by doodirock** [comment]
Well i finally found the issue.  I started by go through all my modules one by one.  Oddly enough after disabling the Duplicate Role module everything began to work just fine.  I'm not exactly sure why this module is conflicting with RestFul but if I enable again it breaks output.  

Could there be a competing public function?  I'll let the owners of the project decide what to do.  I dont have a huge need for Duplicate Role so im deleting it for now.  Hope this helps @jeff-h

**Comment by jeff-h** [comment]
Wow, very strange. I don't use the Duplicate Role module but I tried enabling it on my site (are you using v1.2?) and it made no difference at all to my RESTful JSON responses. That module is tiny and skimming through its code I can't see anything that could cause a problem with RESTful. It does one thing oddly, in its `duplicate_role.info`:

```
files[] = duplicate_role.module
```

That's pretty weird and should be removed (could you try doing that?) but I really can't see that causing the issue you're experiencing.

I'll probably have to dig into my version of the problem at some point next week and will certainly post here if I find something.

**Comment by RoySegall** [comment]
Didn't follow all the issue but I got the same thing only(!) on travis for another project. Lucky to see that i'm not the only one in this one.

Any way, I moved back to 1.x.

**Comment by e0ipso** [comment]
Could this be related to the PHP version? I cannot seem to be able to reproduce it. Do you guys can provide the steps to reproduce from a clean installation?

> Any way, I moved back to 1.x.

That's so sad!

**Comment by RoySegall** [comment]
I was thinking i'm hallucinating and decided to quit. Any way maybe you can try and look at [this PR](https://github.com/Midburn/burning/pull/10) where there a lot of failing builds. Could not reproduced it on a mac so maybe on ubuntu the problem happens.

**Comment by jeff-h** [comment]
I'm running PHP 5.6.10 (under Mamp) so it's unlikely to be a PHP version issue and it's not an Ubuntu issue either since I have the issue on a Mac. Unfortunately my install is as far from clean as you could imagine... loads of contrib modules and custom code. I wasn't able to get a clean install exhibiting the issue, even with a bunch of other modules progressively turned on.

**Comment by e0ipso** [comment]
Ugh! That's bad luck.

I assume there's no chance I can get with a copy of the code and DB that exhibits the issue, right?

**Comment by RoySegall** [comment]
Hmm... I pushed another try to my project, https://github.com/Midburn/burning/pull/23, with maybe another php version.

The thing is that i get the same error on travis and not on my local machine.

**Comment by e0ipso** [comment]
> The thing is that i get the same error on travis and not on my local machine.

Maybe we could compare the setup in both machines?

**Comment by e0ipso** [comment]
> I assume there's no chance I can get with a copy of the code and DB that exhibits the issue, right?

@jeff-h any chance of that? This may be a content interaction.

**Comment by e0ipso** [comment]
Please check the fix in #777.

**Comment by jeff-h** [comment]
Brilliant, this is fixed! Sorry I didn't get back to you in time re: https://github.com/RESTful-Drupal/restful/issues/761#issuecomment-161635674

**Comment by e0ipso** [comment]
@jeff-h no worries, I could reproduce this locally. If it's reproduceable, it's fixable :-)
