### ISSUE TITLE
publicFields syntax and class to extend for term reference fields

### ISSUE THREAD

**Issue by wonder95** [RESTful-Drupal/restful#763]
I've been going through the great [YouTube video series](https://www.youtube.com/playlist?list=PLZOQ_ZMpYrZv8_c7jd_CkO_93-DnyVFY5) on this module, and I'm getting the hang of this pretty well, but I'm stuck on syntax for term reference fields. I was able to figure out how to get data for an entity reference field that references a User, but that's because there is already a class in place (Users__1_0). According to the videos, I would use a structure like

```
    $public_fields['journalists'] = array(
      'property' => 'field_journalists',
      'resource' => array(
        'name' => 'journalists',
        'majorVersion' => '1',
        'minorVersion' => '0'
      )
    );
```

after creating a class to get my term reference field information, but all the examples there are for other nodes using an entity reference field, not a taxonomy term using a term reference field. It appears that I need to extend the DataProviderTaxonomyTerm class, but then I get an error about needing to implement ResourceInterface, which then requires a getAccount method (since it's part of the interface. which makes sense).

 Here's my attempt at creating my Journalists class:

```
<?php
/**

 */

namespace Drupal\restful_tutorial\Plugin\resource\entity\taxonomy;
use Drupal\restful\Plugin\resource\DataProvider\DataProviderTaxonomyTerm;
use Drupal\restful\Plugin\resource\ResourceInterface;

/**
 * Class Journalists__1_0
 * @package Drupal\restful_tutorial\Plugin\resource\entity\taxonomy
 *
 * @Resource(
 *   name = "journalists:1.0",
 *   resource = "journalists",
 *   label = "Journalists",
 *   description = "Export the terms from the Journalists vocab with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "taxonomy_term",
 *     "bundles": {
 *       "journalists" //'journalists' is the machine name of the vocabulary
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class Journalists__0_1 extends DataProviderTaxonomyTerm {

  /**
   * {@inheritdoc}
   */
  protected function publicFields() {
    $public_fields = parent::publicFields();

    }
}
```

So, while I hunt around, what exactly do I need to do in my Journalists__1_0 class to get the taxonomy term reference data so I can use it in my node class? Do I need to extend a class other than DataProviderTaxonomyTerm?

Thanks.

**Comment by e0ipso** [comment]
Please, check the example module. In there you'll find a resource similar to what you need (https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/modules/restful_example/src/Plugin/resource/Tags__1_0.php) and how to reference it from another resource (https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/modules/restful_example/src/Plugin/resource/node/article/v1/Articles__1_5.php#L49-L56).

Please, report back if this solved your issue :-)

Also, feel free to re-open if this does not fix it.

**Comment by wonder95** [comment]
That did the trick. The part I was missing was extending the ResourcEntity class and implementing ResourceInterface. It's interesting to note that my Journalists class itself is empty (unless I want to add an additional field in publicFields() or anything else new), and most of the work is done in the annotation.
