### ISSUE TITLE
Restful search API

### ISSUE THREAD

**Issue by justme7777** [RESTful-Drupal/restful#764]
Hi, sorry for posting double but the other repo seems a little abandoned. 
I am currently using 2.2 and am very happy with it!
Is Restful search API compatible with this? and if not are there plans to make that so?

**Comment by e0ipso** [comment]
Have you tried the version `7.x-2.x`?

https://github.com/RESTful-Drupal/restful_search_api/tree/7.x-2.x

That should do it. :-)

**Comment by e0ipso** [comment]
> the other repo seems a little abandoned

FYI the other repo is very not abandoned ;-)

**Comment by justme7777** [comment]
Great to know, love your quick feedback, anyway we need the search api
dataprovider to be ported, and I am 100% cool with financing that!
(if you let me know how many hours this would take!)

AGAIN thanks for the quick reply

2015-11-30 3:34 GMT+07:00 Mateu Aguiló Bosch notifications@github.com:

**Comment by justme7777** [comment]
Again, I want to contribute to the community and Restful is the first
module where I think it makes real sense!!!! (sorry but rest in D8 is to
incomplete!

ANYWAYZZZZ

Hope we can have a chat soon! I can cough up some money if needed!

Best,
Ben

2015-11-30 6:40 GMT+07:00 Ben beninspain777@gmail.com:
