### ISSUE TITLE
Sort by Created Date [2.x]

### ISSUE THREAD

**Issue by doodirock** [RESTful-Drupal/restful#766]
Was watching the videos and didnt see how one would sort by the nodes created date.  Do we have access to this or is it something we need to write a custom sort for?

**Comment by e0ipso** [comment]
Any Drupal field or property can be used for sorting.

`/articles?sort=-created` should work normally.

**Comment by e0ipso** [comment]
Please feel free to re-open if this doesn't fix it.

**Comment by doodirock** [comment]
Works great.  Thanks!
