### ISSUE TITLE
Easy way to alter publicFieldsInfo by other modules

### ISSUE THREAD

**Issue by RoySegall** [RESTful-Drupal/restful#772]
Iv'e been working on a [module](https://github.com/RoySegall/apps_entity_restrictions) which define third party apps. When creating an application you can select which properties and which field it can access. I want to create a sub module which take care for the user about restrictions and i'm looking for an easy way to alter the public fields info for each end point.

The module would need to check the access for the for each property/field and set the access property to true or false. The easiest way I came up with was to add `drupal_alter` in [RestfulBase ::getPublicFields()](https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/plugins/restful/RestfulBase.php#L1110).

What do you think?

**Comment by e0ipso** [comment]
You can add access calbacks to each of the public fields. Would that work?

**Comment by RoySegall** [comment]
Sure but then I need to prevent from properties to be presented.

**Comment by e0ipso** [comment]
Not sure what you mean, but you have `access callbacks` in RESTful for the field definitions. At least for 2.x (I don't remember about the old version).

**Comment by RoySegall** [comment]
Sure, but I need the module to iterate over each plugin definition and apply it's logic business.

**Comment by e0ipso** [comment]
Does that mean that you cannot put your `drupal_alter` in the access callbacks?

**Comment by RoySegall** [comment]
I want to apply to `drupal_alter` to any endpoint.

**Comment by RoySegall** [comment]
That mean - any end point defined in the system, entities and non-entities, will be handled by my sub-module.
