### ISSUE TITLE
Create method to get entity from URL alias

### ISSUE THREAD

**Issue by wonder95** [RESTful-Drupal/restful#774]
I'm working on using AngularJS to create a front end for a Drupal site using RESTful as the back end, and one of the things I have not found mentioned anywhere is how to load a node by it's URL alias, and not the entity id. This is the same as it works when using Drupal as the front end: the entity is accessed via it's alias, the entity_id is obtained via lookup in the url_alias table, and the entity is loaded using the id. However, everything I've seen in videos and examples shows the entities being loaded by id, but in reality, the front end needs to get the alias from the front end, get the id, and then get the JSON for the specific node.

My first thought was just to add the alias to the output, but that's too late in the process. In stepping through the initial page callback (restful_menu_process_callback()), I can see how it just takes the first part of the URL after /api/ (e.g. 'blogs' in the case of /api/blogs/$whatever), and then looks for that name as the 'resource' key in the class annotation to load it. So for this to work, I would need a class that would be called from the URL which would first get the entity id using the alias from the url_alias table, and then in turn load the appropriate class to get the entity itself. Or another option would be to have the front end make two calls: the first one to a URL to get the entity id using the alias, and the second to the already defined one to get the specific entity.

So along those lines, and looking at the [existing](https://github.com/RESTful-Drupal/restful/wiki/Creating%20a%20custom%20data%20provider) [1.x docs](https://github.com/RESTful-Drupal/restful/wiki/Creating-a-resource-that-takes-data-from-a-secondary-database) and modifying as best I can for 2.x, I created a class that extends DataProviderDbQuery:

```
<?php
/**
 * Contains \Drupal\restful_tutorial\Plugin\resource\url_alias
 */

namespace Drupal\restful_tutorial\Plugin\resource\url_alias;

use Drupal\restful\Plugin\resource\DataProvider\DataProviderDbQuery;

/**
 * Class URLAlias__1_0
 * @package Drupal\restful_tutorial\Plugin\resource\url_alias
 *
 * @Resource(
 *   name = "url_alias:1.0",
 *   resource = "url-alias",
 *   label = "URL Alias",
 *   description = "Gets the entity id from a URL alias.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "tableName": "url_alias",
*     "idColumn": "pid",
 *   },
*   majorVersion = 1,
 *   minorVersion = 0,
 *   class = "URLAlias__1_0"
 * )
 */

class URLAlias__1_0 extends DataProviderDbQuery {

  /**
   * {@inheritdoc}
   */
  protected function publicFields() {
    $public_fields = parent::publicFields();

    $public_fields['alias_id'] = array(
      'property' => 'pid'
    );

    $public_fields['source'] = array(
      'property' => 'source'
    );

    $public_fields['alias'] = array(
      'property' => 'alias'
    );

    return $public_fields;
  }
}
```

However, just like the last time I created a class, I get the error that I need to implement ResourceInterface, and no menu router item is created. However, since this is a just a straight db query, I can't tell which class I should be extending instead. Is there another class I should be extending?

And on a side note, is there a different way that already exists in RESTful to use an alias to get an entity_id that I'm somehow missing?

Thanks.

**Comment by e0ipso** [comment]
I recommend you to look into the example module and look for something similar to what you are looking for.

The best way to get going is seeing how things are done in the examples **and** the tests.

**Comment by wonder95** [comment]
Well, thanks for the helpful noob [RTFM](https://en.wikipedia.org/wiki/RTFM) comment. After 20 years of working with software, I am well versed in reading and learning from what is already there; it's how I've gotten as far as I have with this module.

I only post a request like this - and take the time to detail what I'm trying to do and why - after looking at the code for multiple hours and getting stuck. I wash hoping a couple minutes of your time might help save me a couple more hours of my time. An important part of the Drupal community is helping each other, and I thought issue queues were the place to get actual help (maybe something like "look at this class" or "check out this test"). After taking a couple hours to do a wiki page for this module yesterday, I would've thought a request like this deserved more than an "RTFM" comment. I was all set to contribute whatever I came up with back to the module and even do another wiki page for it.

And, as I mentioned in my original question, I **was** copying what I could find in the docs and code, but I've obviously missed something.

Sorry to bother you.

**Comment by e0ipso** [comment]
Wow, sorry to hear that got to you in that way. That's definitely not what I meant.

Among all the projects I maintain I get dozens of support requests every day, that's dozens of couples of minutes. I _try_ to get to all of them quickly, even if I have been suggested by some to let the community to handle support requests. So, please don't take it in the wrong way. If anything I try to give love to people contributing (even with helpful questions), not bruise their egos ;-)

That being said, what I meant is: I know that there are tests and examples that show that, but I don't know where those are (since there are _lots_ of them).

**Comment by wonder95** [comment]
Points well taken.

However, my ego has nothing to do with it; it's frustration at the inability to get something to work.

I will document what I get to work (assuming I get it to work :-)).

**Comment by wonder95** [comment]
@e0ipso, can we re-open this so I can document what I'm doing?

As an update, I got my alias lookup to work to the point where I can get all of the table contents (I found what I was missing in [DBQueryTest__1_0)](https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/tests/modules/restful_test/src/Plugin/resource/db_query_test/v1/DbQueryTest__1_0.php).

```
/**
 * Contains \Drupal\restful_tutorial\Plugin\resource\url_alias
 */

namespace Drupal\restful_tutorial\Plugin\resource\url_alias;

use Drupal\restful\Plugin\resource\ResourceDbQuery;
use Drupal\restful\Plugin\resource\ResourceInterface;

/**
 * Class URLAlias__1_0
 * @package Drupal\restful_tutorial\Plugin\resource\url_alias
 *
 * @Resource(
 *   name = "urlalias:1.0",
 *   resource = "urlalias",
 *   label = "URL Alias",
 *   description = "Gets the entity id from a URL alias.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "tableName": "url_alias",
 *     "idColumn": "id",
 *     "primary": "id",
 *     "idField": "id",
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0,
 *   class = "URLAlias__1_0"
 * )
 */

class URLAlias__1_0 extends ResourceDbQuery implements ResourceInterface {

  /**
   * {@inheritdoc}
   */
  protected function publicFields() {
    $public_fields['id'] = array(
      'property' => 'pid'
    );

    $public_fields['source'] = array(
      'property' => 'source'
    );

    $public_fields['alias'] = array(
      'property' => 'alias'
    );

    return $public_fields;
  }
}
```

As @amitaibu [mentioned to me on twitter](https://twitter.com/amitaibu/status/669258032690405380), I can query by arbitrary identifiers, which in this case is the alias field, so once I figure out how to do that in the url, I'll have what I need.

**Comment by e0ipso** [comment]
Yes, of course. Does that mean that GitHub does not show the Reopen button to you?

**Comment by wonder95** [comment]
I don't think so, but I might have missed looking in the one place where it was, too. :-)

**Comment by e0ipso** [comment]
BTW, did you watch this video? https://www.youtube.com/watch?v=KCicpOypFVQ&index=17&list=PLZOQ_ZMpYrZv8_c7jd_CkO_93-DnyVFY5

It can be relevant to what you need.

**Comment by wonder95** [comment]
I was actually about to start that one next, but it looked like it was specifically referring to UUID's which I'm not using. I will watch it next.

**Comment by wonder95** [comment]
OK, I see how that works (using the idField value), and I had actually started playing with that before I watched it based on what I picked up from the test class. However, the problem is that what I need to search for is part of a URL, so if I change my idField to be the alias field:

```
 *   dataProvider = {
 *     "tableName": "url_alias",
 *     "idColumn": "pid",
 *     "primary": "pid",
 *     "idField": "alias",
 *   },
```

then for a URL like `blogs/first-name/last-name/2015/12/04/my-blog-title` my api URL ends up being something like

```
mysite.com/api/urlalias/blogs/first-name/last-name/2015/12/04/my-blog-title
```

So somehow everything after `/urlalias/` needs to be seen as one string to pass, not as part of the api URL (if that makes sense).

Still digging through code, just documenting here for reference.

**Comment by wonder95** [comment]
Woo hoo!! I got it to work. I just had to change the idColumn to be the alias field:

```
 *   dataProvider = {
 *     "tableName": "url_alias",
 *     "idColumn": "alias",
 *     "primary": "pid",
 *     "idField": "alias",
 *   },
```

since that's what it passes the value of the URL. Looks like it already recognizes the rest of the URL as one argument after the base and resource name.

@e0ipso, I can see this as being a valuable part of the module. Do you agree? If so, let me know and I'll do a PR.

Also, any other things I would need to add/change?

**Comment by e0ipso** [comment]
Yes! I think it can be a cool example.

Coincidentally I'm am working on something very similar to this, but with the redirect table :-)

**Comment by e0ipso** [comment]
> Coincidentally I'm am working on something very similar to this, but with the redirect table :-)

I mean for a client project I'm currently working.

**Comment by wonder95** [comment]
Well, I was thinking more about having it as part of the module itself - a built in URL alias lookup.

**Comment by e0ipso** [comment]
We don't provide integrations in RESTful unless they are used by other built-in parts of the code (like the users resource for authentication purposes), but I still think that it's a valuable example.

**Comment by wonder95** [comment]
[Blog post](http://www.smgaweb.com/blog/creating-restful-api-url-alias-lookup-drupal) and [wiki page](https://github.com/RESTful-Drupal/restful/wiki/Look-up-a-URL-alias-mapping-with-DataProviderDbQuery) created.

**Comment by e0ipso** [comment]
That blog post looks wonderful! Thanks for all the effort you put in the documentation.

**Comment by jeff-h** [comment]
This is in the wiki at https://github.com/RESTful-Drupal/restful/wiki/Look-up-a-URL-alias-mapping-with-DataProviderDbQuery right? If so, thanks for your efforts documenting it all up!

This issue can probably be closed now?

**Comment by wonder95** [comment]
Yes, it can be closed.
