### ISSUE TITLE
need anon to create but not read

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#782]
I need a resource to allow entities to be create-able by anon, but the anon user shouldn't be able to access the resultant node, because they'd by implication get access to _all_ nodes of that type (think of it as an online survey). I've got the Drupal user permissions set up this way, so that anon can't view unpublished nodes.

It seems when RESTful 2.x is creating a new entity, it creates it just fine, then it tries to include the resultant entity in the response (using JSON API). This is a reasonable default, but it seems if the client doesn't have permission to view the entity, the entire response 404's.

I recall seeing code (unfortunately can't find it right now) which spun through all the entities to be included in the JSON response, and if any had no access, it didn't throw the 404 immediately but recorded the lack of access. I'm guessing if at the end of that whole process nothing had access, then a 404 is thrown.

Is there something I can do to allow my use-case?

**Comment by jeff-h** [comment]
The code I was looking for is in `DataProviderEntity.php` at https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/src/Plugin/resource/DataProvider/DataProviderEntity.php#L826-L846

**Comment by e0ipso** [comment]
Easy way: implement the `::access()` method in your resource to throw a `ForbiddenException`.
Proper way: override the controllers info to add an access callback for `GET`.

**Comment by jeff-h** [comment]
I'm a bit confused, sorry. A `ForbiddenException` is a 403 right? I want a 200, but I'm getting a 404.

I just attempted to override `controllersInfo()` but it seems only the POST method is used in a POST (even though with JSON API there is a read involved as well, to populate the response with the new object).

``` php
class Barry__1_0 extends ResourceNode implements ResourceInterface {

  public function controllersInfo() {
    $routes = parent::controllersInfo();

    $routes[''][RequestInterface::METHOD_GET] = 'custom_get';
    $routes[''][RequestInterface::METHOD_POST] = 'custom_post';

    return $routes;
  }

  function custom_get($path) {
    xdebug_break();
    return parent::index($path);
  }

  function custom_post($path) {
    xdebug_break();
    return parent::create($path);
  }
}
```

In the above, only the `custom_post()` is run.

It seems to me that 2.x assumes that if you have write access, you must also have read access, and if you don't, write requests return a 404, even if the write succeeded. That's incorrect at a broader level isn't it?

**Comment by jeff-h** [comment]
I've fixed the issue by modifying the `view` method so that when an entity is not valid, it only throws an `InaccessibleRecordException` if it's not part of a create request.

I actually think this issue is a bug in the module but it's entirely possible I have no clue :D I've put it in a PR at https://github.com/RESTful-Drupal/restful/pull/783

**Comment by jeff-h** [comment]
Closing this, as the referenced PR has the conclusive followup to this.
