### ISSUE TITLE
7.x-2.x - Preferred approach to creating a resource for an arbitrary business operation

### ISSUE THREAD

**Issue by ethanhinson** [RESTful-Drupal/restful#791]
I have a use case where I need RESTful to act as an intermediary between a client side user, and a 3rd party API. The API provides real time pricing data that cannot be cached - and for this reason uses a request based temporary database table in my system. The question here is how can I expose this functionality via a RESTful resource? My first assumption was to implement a custom resource for the custom entity, implement hook_entity_property_info_alter() and provide a "pseudo" property on the entity type this call is related too. Then use the "process" key of the publicFields declaration for the "pseudo" property to execute a call to the API and do some processing on the data returned. It seems like this approach could work - but I'm having a hard time understanding whether it is bad practice to attempt to obtain which entities are being returned by the dataProvider and execute my operation on them. Is there a preferred approach for this use case? If so, I can provide some documentation and example(s) once I get it working.

**Comment by jeff-h** [comment]
Bear in mind RESTful provides the ability for resources that aren't fetching entities. I'd recommend having a good poke around the bundled example modules (and tests), especially in your case the example module's `variables` resource.

**Comment by jeff-h** [comment]
If you come up with a nice solution to this, this issue would make an ideal wiki article... just saying :)

**Comment by e0ipso** [comment]
Good data provider examples that are not entities:
- DB Queries.
- Annotation plugins themselves (for the plugin discovery in `/api`).
- Variables.

Drupal is an amazing CMS, but it's not the fastest software no Earth. If the client can make the API directly, or you can build an API aggregator outside of Drupal, that you save you some milliseconds. Of course, everything _depends_ on the situation.

**Comment by e0ipso** [comment]
> If you come up with a nice solution to this, this issue would make an ideal wiki article... just saying :)

:heart: 

Yes! as @jeff-h suggests, please do write an article in your blog or the wiki.

**Comment by ethanhinson** [comment]
So just to be clear - in this example - there is no database table, and Drupal is not aware of the temporary table. It feels like the way to do this is with an Annotation plugin - but I'm still getting my head around the internals of dataProviders and dataInterpreters and how the annotations would provide configurations for this setup.

**Comment by e0ipso** [comment]
I don't think you need to use annotations or database tables. Those are good examples of DataProviders and DataInterpreters, since you will need to implement your own.

**Comment by ethanhinson** [comment]
Thanks for the input guys. I'll spend some more time on it this week!

**Comment by e0ipso** [comment]
It would be awesome if you showed appreciation in the form of documentation  :-)

Closing for now.

**Comment by jeff-h** [comment]
I know it's closed, but do look at the `variables` example I mentioned — it doesn't directly access the drupal `variable` database table, but rather uses drupal core's `variable_get` and `variable_set`. I think it's a really nice example of what I think you're working on.

**Comment by e0ipso** [comment]
Yes! That's exactly my point. Thanks again @jeff-h for being so active and spot-on!!

**Comment by ethanhinson** [comment]
Sorry to re-open such an old issue, however, we have been making heavy use of RESTful again - this time on a wider array of projects. And, I've just remembered that this ticket may help others :)

In the end my solution here is quite simple. I have been overriding the controllersInfo method in my resource classes and adding a new path (and matching instance  method) to the resource. Whether you are extending EntityFieldQuery or simple DBTNG based resources this approach seems to ok for me. 

I can't recall seeing much documentation on the controllersInfo method, but this seems like a really powerful/easy concept that may help a lot of people. Especially if you have data sources outside of the typical Drupal resources (in our case real time 3rd party web services data feeding temporary DB tables). If this approach makes sense, I'd be happy to add a WikiPage.
