### ISSUE TITLE
/admin/index is requiring authentication?

### ISSUE THREAD

**Issue by EvWill** [RESTful-Drupal/restful#795]
I created a class that extends the Authentication class, and now I can't access admin/index unless I provide the key in the URL. I'm not sure if this is a bug or if I have done something horribly wrong. Thanks.

```
class KeyAuthentication extends Authentication {

  public function applies(RequestInterface $request) {
    $input = $request->getParsedInput();

    if($this->requestHasCorrectKey($input)) {
        return true;
    } else {
        throw new ForbiddenException;
    }
  }

  public function authenticate(RequestInterface $request) {}

  private function requestHasCorrectKey($input) {
    return ((isset($input['key']))&&($input['key'] == 'TESTKEY'));
  }
```

**Comment by e0ipso** [comment]
> now I can't access admin/index

Do you mean when going to the admin UI? Are you using 2.x?

**Comment by EvWill** [comment]
Yep, only that specific url. The rest of the admin pages work. Using 2.x

**Comment by e0ipso** [comment]
What's your api prefix?

**Comment by EvWill** [comment]
It's 'api', didn't change it.

**Comment by e0ipso** [comment]
Have you tried the `restful_access_token` submodule? Is that causing the same issue?

**Comment by e0ipso** [comment]
@EvWill I am unable to reproduce this issue. Please use the `restful_access_token` authentication or base your custom implementation on that. If that still does not fix the issue, feel free to re-open (or ask to re-open).
