### ISSUE TITLE
Set up a Gitter room?

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#797]
Just wondering if others think it would be worthwhile setting up a Gitter room, or IRC channel or something for those implementing RESTful in their projects? A very quick "yes it should do that" or "that's in the wiki" could be pretty helpful to me at least.

**Comment by e0ipso** [comment]
I like that support request leave a paper trail. Those can be found and can answer questions to people after months (or years) after they were initially posted.

Giving support in IRC (or other) is a very time consuming time to which I cannot commit at the moment. Although if you end up setting it up, I'll be glad to join from time to time.

**Comment by e0ipso** [comment]
Aaaand, just now I stumble upon the gitter room I set up in the past https://gitter.im/RESTful-Drupal/restful :blush:

**Comment by jeff-h** [comment]
TBH I hadn't even considered the trail; you're right, it's something very worthwhile that would be lost. I will hang out in that room for a while and see if anyone crops up (can't get in right now though), and if anything useful goes down, I'll stick it in the wiki.
