### ISSUE TITLE
DISCOVER data production doesn't work properly?

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#800]
Maybe I'm totally misunderstanding what the OPTIONS call to a resource should return, but RESTful v2 returns something very different than v1.

In v2, the response's `data` is an array containing multiple instances of the same discovery data, over and over, one for each entity of the type in question.

For example, if I turn on the `restful_example.module` and create two "article" nodes, then do an OPTIONS call:

``` sh
curl -X "OPTIONS" "http://myserver.com/api/v1.0/articles" 
```

I get **two** copies of the discovery data:

``` json
{
  "data": [
    {
      "id": {
        "info": {
          "label": "ID",
          "description": "Base ID for the entity."
        },
        "data": {
          "type": "integer",
          "required": true,
          "read_only": true,
          "cardinality": 1
        }
      },
      "label": {
        "info": {
          "label": "Label",
          "description": "The label of the resource."
        },
        "data": {
          "type": "string",
          "required": false,
          "read_only": false,
          "cardinality": 1,
          "size": 255
        },
        "form_element": {
          "type": "textfield",
          "default_value": "",
          "placeholder": "",
          "size": 255,
          "allowed_values": null,
          "title": "label",
          "description": "The label of the resource."
        }
      },
      "self": []
    },
    {
      "id": {
        "info": {
          "label": "ID",
          "description": "Base ID for the entity."
        },
        "data": {
          "type": "integer",
          "required": true,
          "read_only": true,
          "cardinality": 1
        }
      },
      "label": {
        "info": {
          "label": "Label",
          "description": "The label of the resource."
        },
        "data": {
          "type": "string",
          "required": false,
          "read_only": false,
          "cardinality": 1,
          "size": 255
        },
        "form_element": {
          "type": "textfield",
          "default_value": "",
          "placeholder": "",
          "size": 255,
          "allowed_values": null,
          "title": "label",
          "description": "The label of the resource."
        }
      },
      "self": []
    }
  ],
  "self": {
    "title": "Self",
    "href": "http://myserver.com/api/v1.0/articles"
  }
}
```

This is because in `src/Plugin/resource/DataProvider/DataProvider.php` the `discover` method ends with

``` php
    return $path ? $this->viewMultiple(array($path)) : $this->index();
```

I don't understand how it could ever work to send the discovery data through `viewMultiple`:
- if we don't have at least one entity of this type then the OPTIONS request won't return any discovery data — the `data` element is empty
- it returns the OPTIONS data over and over, once for each entity ID it can find (courtesy of the `index()` call)

**Comment by e0ipso** [comment]
I'd recommend using a `?range=1` in your URL to avoid this. I like the consistency.

Look at the OPTIONS request as a way to see the schema info of whatever data a GET would return. Also, bear in mind that every particular instance of an entity could have individual data added through custom discovery sections.

**Comment by jeff-h** [comment]
> Look at the OPTIONS request as a way to see the schema info of whatever data a GET would return.

Ahhhh OK. Thanks for clarifying that.

Unfortunately I'm using this data in order to create the form (in JS) for the user to fill in and create a new entity. I need this to work even if there isn't a pre-existing entity.

Could I ask what you think I should do in this case? I can think of two options:
- extend the `discovery` resource so it adds a `publicFields` array element to the data it spits out for each resource
- create a new resource which serves up just the publicField metadata for the given resource. Something like `api/fields/article` would spit out the discovery data for the `article` node type, regardless of whether a `GET` would return anything

I'm thinking the latter sounds best but would very much value your thoughts.

**Comment by jeff-h** [comment]
(I also just stole some of your words and stuck a page in the wiki at https://github.com/RESTful-Drupal/restful/wiki/OPTIONS-requests Hope that's OK :D )

**Comment by e0ipso** [comment]
> Hope that's OK

It's more that OK, it's great!

**Comment by amitaibu** [comment]
@e0ipso this change from 1.x looks weird to me. I would expect to get the _base_ description of that resource. 

> every particular instance of an entity could have individual data added

In that case I would expect a specific call to OPTIONS call to `resource/1`. 

thoughts?
