### ISSUE TITLE
How to get URL alias for referenced taxonomy term in entity class

### ISSUE THREAD

**Issue by wonder95** [RESTful-Drupal/restful#806]
As I [documented here](https://github.com/RESTful-Drupal/restful/wiki/Look-up-a-URL-alias-mapping-with-DataProviderDbQuery), I have a URL alias lookup class, that allows me to look up a source by the alias. The way I'm using it to get a node id in angular is by making a call to the alias lookup, getting the nid from there, and then using my defined API to get the node  object:

```
      BlogDetail.getNid(url).then(function(data) {
        var nid = data.data.data[0].source.split('/')[1];
        BlogDetail.getBlog(nid).then(function(data) {
          var node = data.data.data[0];
          $scope.node = node;
        })
      });
```

where BlogDetail is a separate Angular service that gets the data. However, taxonomy terms also have aliases, and I would also like to get the aliases from the term path (i.e. taxonomy/term/$term_id).

My node has various term reference fields, and I've created separate classes for each one and defined public fields in my blog class. For example, for a term named Journalists, I have this:

```
/**
 * Class Journalists__1_0
 * @package Drupal\restful_tutorial\Plugin\resource\entity\taxonomy
 *
 * @Resource(
 *   name = "journalists:1.0",
 *   resource = "journalists",
 *   label = "Journalists",
 *   description = "Export the terms from the Journalists vocab with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "taxonomy_term",
 *     "bundles": {
 *       "journalists"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class Journalists__0_1 extends ResourceEntity implements ResourceInterface {
```

and in my Blog class:

```
class Blogs__1_0 extends ResourceNode {

  /**
   * {@inheritdoc}
   */
  protected function publicFields() {
    $public_fields = parent::publicFields();

    unset($public_fields['self']);
    unset($public_fields['label']);
...
    $public_fields['journalists'] = array(
      'property' => 'field_journalists',
      'resource' => array(
        'name' => 'journalists',
        'majorVersion' => '1',
        'minorVersion' => '0'
      ),
    );

...

    return $public_fields;
  }
}
```

When I add `?include=journalists` to my api URL, I get info for the term in the _included_ member:

```
    {
      "type": "journalists",
      "id": "1080",
      "attributes": {
        "id": "1080",
        "label": "Journalist Name",
        "self": "http://nbd7-angular/api/v1.0/journalists/1080"
      },
      "links": {
        "self": "http://nbd7-angular/api/v1.0/journalists/1080"
      }
    },
```

However, it is missing the term alias (e.g. /journalists/journalist-name), and I would like to have that available so I can create my term link at the bottom of my blog page. Is there a way I can include that data in the _included_ member without having to do a separate lookup outside of the Blog class? My initial thought is having to use a process callback, that just queries the alias table directly, but Im wondering if there might be a cleaner way to do it by using another URL alias class similar to the one I already have.

I know you're busy, Mateu, but if you could just give me a point in the right direction, I would appreciate  it.

Thanks.

**Comment by wonder95** [comment]
Well, I was able to answer my own question with some playing around with code and watching a [video](https://www.youtube.com/watch?v=Mpv5OmscTLY&index=5&list=PLZOQ_ZMpYrZv8_c7jd_CkO_93-DnyVFY5).

My solution uses (as suggested above) the `process_callbacks` key in `public_fields`:

```
  protected function publicFields() {
    $public_fields = parent::publicFields();

    $public_fields['alias'] = array(
      'property' => 'tid',
      'process_callbacks' => array(
        array($this, 'getAlias')
      )
    );

    return $public_fields;
  }

  public function getAlias($value) {
    return drupal_get_path_alias('taxonomy/term/' . $value);
  }
}
```

This gives the following JSON output:

```
    {
      "type": "journalists",
      "id": "1080",
      "attributes": {
        "id": "1080",
        "label": "Journalist Name",
        "self": "http://nbd7-angular/api/v1.0/journalists/1080",
        "alias": "journalists/journalist-name"
      },
      "links": {
        "self": "http://nbd7-angular/api/v1.0/journalists/1080"
      }
    },
```

I had to start with a valid value, and since I needed the tid (to go with the base `taxonomy/term/$tid` url), I used that property, and then added a process callback to get the alias.

I'll leave this issue open for @e0ipso (or someone else) to add a comment and let me know if there is a better way to do this.

**Comment by e0ipso** [comment]
This looks correct for this use case. Thanks @wonder95 for taking the time to document this.

**Comment by wonder95** [comment]
I created a [blog post](http://www.smgaweb.com/blog/getting-url-alias-referenced-entity-restful-api-drupal) to document this. There is already a [wiki page](https://github.com/RESTful-Drupal/restful/wiki/Using-process-callbacks-to-modify-field-data) on using process callbacks.
