### ISSUE TITLE
restful_token_auth Articles__1_3 node resource class overrides my custom class

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#808]
I understand the Articles__1_3 class in restful_token_auth is there for testing. 

The problem is that when the module is enabled, requests to /api/articles are handled by this class, rather than my custom Articles__1_0 class.

I know I could specify the version, but the 1.3 class still pollutes my calls, for example GET /api returns 1.3 as the latest version of /articles. 

If I'm right in saying this class is only used for testing, could it be bundled into a submodule that only gets enabled for tests?

**Comment by theodorosploumis** [comment]
I would like to ask for this too. 
I think the **restful_token_auth** module could be shipped without any other resources and examples because in fact it can be used **as it is** to provide an authentication method. If you agree I could provide a pull request to split the module into 2 separate.

**Comment by jeff-h** [comment]
@theodorosploumis You're definitely right, restful_token_auth shouldn't be providing this resource.

I'm not sure if there are any other ways of providing this resource for test purposes though — @amitaibu @e0ipso  ?

**Comment by e0ipso** [comment]
I agree with the general consent. This should not be here. Maybe we need a `restful_token_auth_test` module to include such things…

**Comment by e0ipso** [comment]
Fixed in #839.
