### ISSUE TITLE
Question: How to filter users by role

### ISSUE THREAD

**Issue by pferlito** [RESTful-Drupal/restful#811]
I'm working with 2.x. I subclassed Users__1_0 and exposed 'roles' as a public field, and this works:
http://example.com/api/v1.0/myusers
but this doesn't work:
http://example.com/api/v1.0/myusers?filter[roles]=1
It gives me SQL error. Is this because roles is not a property of the user entity?
I'm trying to filter the users by a role id or role name and I'm not sure how to proceed from here.

Any guidance would be appreciated.

**Comment by jeff-h** [comment]
This will be because the roles data is not actually stored on the `users` table in the db, I think. Is the resulting EFQ generating an error similar to the one mentioned in the following?

http://drupal.stackexchange.com/questions/11175/get-all-users-with-specific-roles-using-entityfieldquery

I think filtering by role would be a very common scenario, albeit one I haven't had to do myself, so as soon as the answer crops up I'll put it in the wiki docs.

**Comment by pferlito** [comment]
Thanks @jeff-h the post was helpful in finding a solution. Here is what I did to get it working:
1. Subclassed [DataProviderEntity](https://github.com/RESTful-Drupal/restful/blob/7.x-3.x/src/Plugin/resource/DataProvider/DataProviderEntity.php)
2. Implemented dataProviderClassName() in my resource entity class and pointed it to the class from step 1 as per [this post](https://github.com/RESTful-Drupal/restful/wiki/Assigning-a-different-data-provider)
3. Overrode method queryForListFilter()
4. In queryforListFilter() I added a special query tag and added the requested roles to the query metadata
5. In my .module file I implemented [hook_query_alter()](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_query_alter/7)
6. In hook_query_alter() I retrieved the roles and used them in a join with the USERS_ROLES table like this:

``` <php>
      $query->leftJoin('users_roles', 'ur', 'users.uid = ur.uid');
      $query->condition('ur.rid', $rids, 'IN');
```

**Comment by jeff-h** [comment]
Wow, nicely done! And nicely written up, thanks.

I'm a little surprised at the steps it took to achieve this. Hopefully one of the project maintainers can throw in a comment here to confirm this is the approach they'd recommend, but in the meantime I'll stick this in the wiki.

**Comment by jeff-h** [comment]
https://github.com/RESTful-Drupal/restful/wiki/Filtering-users-by-role

**Comment by e0ipso** [comment]
Thanks gentlemen!

**Comment by ovidius72** [comment]
@pferlito 

> 1. In queryforListFilter() I added a special query tag and added the requested roles to the query metadata

Could you please be more detailed about this step. I suppose the query tag is what we can hook in the custom module, but it's not clear to me what does it means "added the requested roles to the query metadata"

Thanks.

**Comment by fpalluel** [comment]
Hello,
Here is something that works for me, I couldn't make the above proposed code work without modifying it.

In your custom DataProvider :

```
public function queryForListFilter($query) {
  $query->addTag('role_filter');
  return $query;
}
```

In your module :

```
function mymodule_query_role_filter_alter(QueryAlterableInterface $query) {
  // We get the desired role Id from the url parameters
  $role = $query->getMetaData('restful_data_provider')
                ->getRequest()
                ->getParsedInput()['filter']['roles'];
  $query->leftJoin('users_roles', 'ur', 'users.uid = ur.uid');  
  $query->condition('ur.rid', $role ,'=');  // '=' operator
}
```

I can post the full code if you need it.
Good luck ;-)

**Comment by jeff-h** [comment]
Thanks for posting the above code snippets. Just a comment: I think you most likely should be calling the parent's `queryForListFilter` in your overriding method above? i.e.

``` php
public function queryForListFilter($query) {
  parent::queryForListFilter($query);
  $query->addTag('role_filter');
  return $query;
}
```

Also, nice find that RESTful adds a bunch of query metadata e.g. `restful_data_provider`!

**Comment by v1talii-dev** [comment]
@fpalluel, post full code, please.
