### ISSUE TITLE
Cannot implement my own users:1.0 resource

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#813]
Hi there,

I might be missing something here. I have implemented my own users:1.0 resource class, but the endpoint delivers the default users:1.0 resource packaged with the module.

If I uncheck 'Determines if the default user resource should be enabled.' in the admin settings form, the endpoint is removed entirely.

Is there a way to make my own users:1.0 resource class override the default users resource class?

**Comment by jeff-h** [comment]
You should give your version of the user resource a higher version number than 1,0, even if only slightly. I'd suggest 1.1, or if it's a significant change, 2.0. It's up to you but only a higher version number will automatically take precedence.

Another thing to do is make sure Drupal/plug has discovered your new class. I use Drush to do this:

```
$ drush rr
```

Let us know how you go!

**Comment by tripper54** [comment]
Hi,

Yes, that works, thanks. I was kind of hoping to launch the API at version 1.0 ... not to worry, though, I can work with a higher version number!

**Comment by jeff-h** [comment]
Ah, that's a good point, re launching at 1.0. The only option to stay with 1.0 would be to rename the resource, I think.

**Comment by e0ipso** [comment]
A random thought about version numbers. In general a good rule of thumb is that if you are inheriting from the old resource, you bump up the minor version. If you are not, then bump up the major version.

@jeff-h maybe worth chewing on those words for a bit and adding them to the docs? :-)

**Comment by jeff-h** [comment]
I've split the docs on defining resources into two, and added your note from above:

https://github.com/RESTful-Drupal/restful/wiki/1.-OVERVIEW-Defining-your-own-RESTful-plugin-(2.x)#a-note-about-version-numbers

No chewing needed :)
