### ISSUE TITLE
Creating a node resource only works if the user has permission to 'edit any content'

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#814]
Hi there,

I have a node bundle where users can create, edit and delete their own content.

If I try to POST to the node resource, I get a 400 'Property label cannot be set' error.

If I change the user's permission to 'edit any content' for that bundle, the request returns 200 and the node is created OK.

Looking at ResourceFieldEntity->access(), it seems $property_wrapper->access($op, $account) gets called, with 'edit' as the value for $op. The user fails that check.

The 'edit' op is hard coded in DataProviderEntity->setPropertyValues().

Am I doing something wrong with permissions at my end, or is this a bug?

**Comment by jeff-h** [comment]
There are a lot of factors that could be at play in your site e.g. field-level permissions etc so I'd hesitate to think it's a bug at this point, especially given that it works fine for me :p 

Is your node type created via Drupal config, or is it provided by a custom (or contrib) module?

When you traced it through `ResourceFieldEntity->access()` did `$account` indicate that RESTful had correctly authenticated the request?

If you remove the `label` from your resource does the situation improve? Inside `publicFields()`:

``` php
protected function publicFields() {
    $public_fields = parent::publicFields();

    unset($public_fields['label']);
```

Can you paste your resource class code here?

**Comment by tripper54** [comment]
> Is your node type created via Drupal config, or is it provided by a custom (or contrib) module?

There's no config for this content type in code, so I assume it was created originally via the admin GUI. (I didn't build the site originally. Locally I'm working with a dump of the production DB).

> When you traced it through ResourceFieldEntity->access() did $account indicate that RESTful had correctly authenticated the request?

Yes, it is populated with the correct user.

> If you remove the label from your resource does the situation improve?

No! the only property I set in the POST request is the label (which maps to title). So if i unset label, I get 400 'no values were sent with this request.'

> Can you paste your resource class code here?

Most certainly!

``` php
<?php


namespace Drupal\ii_rest\Plugin\resource\node\new_watchlist;

use Drupal\restful\Http\RequestInterface;
use Drupal\restful\Plugin\resource\ResourceEntity;
use Drupal\restful\Plugin\resource\ResourceInterface;
use Drupal\restful\Plugin\resource\ResourceNode;
use Drupal\restful\Plugin\resource\Field\ResourceFieldBase;

/**
 * Class Watchlists
 * @package Drupal\restful\Plugin\resource
 *
 * @Resource(
 *   name = "watchlists:1.0",
 *   resource = "watchlists",
 *   label = "Watchlists",
 *   description = "Watchlists.",
 *   authenticationTypes = TRUE,
 *   dataProvider = {
 *     "entityType": "node",
 *     "bundles": {
 *       "new_watchlist"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class NewWatchlist__1_0 extends ResourceNode implements ResourceInterface
{

  /**
   * {@inheritdoc}
   */
  protected function publicFields() {
    $public_fields = parent::publicFields();


    $public_fields['company'] = array(
      'property' => 'field_watchlist_company',
      'sub_property' => 'nid',
      'resource' => [
        'name' => 'companies',
        'majorVersion' => 1,
        'minorVersion' => 0,
      ],
    );

    return $public_fields;
  }

  /**
   * {@inheritdoc}
   */
  protected function dataProviderClassName() {
    return '\Drupal\ii_rest\Plugin\resource\DataProvider\DataProviderWatchlist';
  }

}

```

**Comment by jeff-h** [comment]
Great, thanks.

Have you already had a simpler example working? If not, your current case isn't the most straightforward to get going as your first attempt. I haven't personally seen or used the `'resource'` key of the public field, like you're doing in the company field definition. Can I ask what kind of field `field_watchlist_company` is?

Could you also post the code from your custom data provider (`DataProviderWatchlist`)?

Just a heads-up, in Github if you post code, you can format it nicely by wrapping the code with three ``` in a row and then a language identifier e.g. for php

```php
your code
```

**Comment by tripper54** [comment]
Thanks for the markdown tip ;)

I had a chance to play with this a bit last night, and was able to reproduce it on a standard drupal install, using the resources in restful_example. So I guess that makes it a bug!

Steps to reproduce (on a standard install of drupal 7 , that is with the default 'article' content type enabled):
1. enable restful_example, restful_token_auth and dependencies
2. authenticate with restful_token_auth using user 1 credentials:

```

curl -X "GET" "http://d7sand.local/api/login-token" \
    -H "Authorization: Basic dGVzdGFwaToxMjM0"

```
1. POST to articles v1 with a dummy title. This will work fine:

```

curl -X "POST" "http://d7sand.local/api/v1.0/articles" \
    -H "Content-Type: application/json" \
    -H "access-token: QrcbBbVjIDmeMuoUHfHoozS2xgWCLM3P5-oQPT1I8dY" \
    -d "{\"label\":\"test api user\"}"

```
1. Now via the drupal admin GUI, give the 'authenticated' role the ability to create articles, edit their own articles, and delete their own articles. 
2. Create a user of the authenticated role. (via admin GUI)  - Let's say 'testuser'
3. Authenticate via token auth using testuser's credentials (see above for cURL command).
4. Try to POST to articles v1.0 using testuser's access token (see cURL above). It will fail with a 400 error:

```

{"type":"http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html#sec10.4.1","title":"Property label cannot be set.","status":400,"detail":"Bad Request"}

```
1. Via the admin GUI, give authenticated users the permission to edit ANY article.
2. Try step to POST an article as testuser. It will work.

[edit: stoopid markdown is changing my step numbers]

**Comment by tripper54** [comment]
AFAICT the issue is in 
Drupal\restful\Plugin\resource\DataProvider\DataProviderEntity->setPropertyValues().

This method requires you to have 'edit' permissions on the entity you're try to set values on. I'm guessing it probably is trying to set the field values before the entity has had a user assigned to it, so the 'edit' permission check fails if you don't have permission to edit nodes that don't belong to you.

**Comment by jeff-h** [comment]
@tripper54 You really in Springwood? (I've been stalking your profile :) ) If so you make a very early start! I used to live in Warrimoo briefly...

**Comment by tripper54** [comment]
@jeff-h , heh, yes, I'm an early riser. Small world, hey? Are you still in Sydney or thereabouts?

**Comment by jeff-h** [comment]
South Island of NZ. Close relatively speaking, perhaps :)

Strangely enough I can't replicate your very-well-isolated issue. I didn't do a clean D7 install though, just messing in my existing project. I did follow all your steps though.

Any chance you could get me your test site's codebase and database? Maybe Dropbox or something?

**Comment by tripper54** [comment]
Strange you can't reproduce it. It should be very testable, I'll have a crack at writing a test for it when i get some time.

I've worked around the issue for my implementation by adding my own setPropertyValues() method to my dataprovider class. In that class I switched the permission checks - if the entity is new, it uses 'create' as the op, otherwise it uses 'edit':

``` php

$op = $wrapper->is_new ? 'create' : 'edit';
$entity_property_access = $this::checkPropertyAccess($resource_field, $op, $interpreter);

```

**Comment by e0ipso** [comment]
@tripper54 did you apply the required Entity API patch? This may be the issue in this case.

**Comment by tripper54** [comment]
@e0ipso , indeed that patch fixed the problem. Thanks!

**Comment by jeff-h** [comment]
For anyone in future: https://github.com/RESTful-Drupal/restful/wiki/When-things-go-wrong :)

**Comment by tripper54** [comment]
Nice one @jeff-h !

**Comment by e0ipso** [comment]
@jeff-h thank you sir!
