### ISSUE TITLE
Pagination configuration

### ISSUE THREAD

**Issue by neubreed** [RESTful-Drupal/restful#815]
Is it possible to alter the pagination parameters and or turn it off?

**Comment by e0ipso** [comment]
Please, see https://www.youtube.com/watch?v=bPrCOzP2Fjk&list=PLZOQ_ZMpYrZv8_c7jd_CkO_93-DnyVFY5&index=15 and post back if that resolves you questions.

**Comment by neubreed** [comment]
Thanks for coming back so quickly ... Pity searching for this doesn't bring back content within YouTube content!

I understand the range property now .. Is there a way to switch it off altogether other than setting a range over the anticipated number of items?

**Comment by jeff-h** [comment]
@neubreed Don't suppose you could give me a hand by dumping some thoughts into https://github.com/RESTful-Drupal/restful/wiki/Paginating-the-response ?

**Comment by neubreed** [comment]
Will do...

**Comment by e0ipso** [comment]
@neubreed there is no way to turn pagination off, because I don't see an scenario where it's a good idea.

In practice, you can set it to an arbitrarily high number and achieve just that (not recommended).

**Comment by neubreed** [comment]
Yes I agree but my client is insisting (at their peril) .. perhaps a simple 0 = unlimited could be considered.

**Comment by e0ipso** [comment]
@neubreed I would propose them a really high number. There are no plans to allow _unlimited_ pages.

**Comment by e0ipso** [comment]
@neubreed of course, as with all RESTful features, you can override this in your specific resource/data provider. You'll have to dig in the code a bit, but it should not be hard to find.
