### ISSUE TITLE
Custom resources: works on local , not on production

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#817]
Hello,

This is one of those 'why doesn't it work, help!' posts I'm afraid.

My custom resources work correctly on my local dev environment. 

However when I deployed the modules to production, the discover endpoint  - /api  - only shows the default resources, and any calls to my custom resources return 404s.

The default resources work as expected.

I checked the registry table on my production DB and the custom classes seem to have been correctly registered.

If i try to reference the classes from a drush php on the production server they are autoloaded OK eg 

```

$testmyresource = new Drupal\ii_rest\Plugin\resource\entity\RecommendationCollection__1_0;

```

[this throws an error because I'm not providing the correct parameters, but drupal finds and loads the class OK]

I tried flushing caches, registry rebuild, disabling/uninstalling/re-enabling the custom module. All to no avail.

Can anyone offer any clues as to what might be going on here?

**Comment by jeff-h** [comment]
You do seem to have covered all the bases, but there is one more: on production is the plug module turned on?

**Comment by tripper54** [comment]
Yes, it is. I guess if restful hands plugin discovery off to the plugin module, the issue might lie there. I haven't really looked into the plugin discovery mechanism so far, as it 'just worked' on my local machine.

Thanks for the clue, I'll keep investigating.

**Comment by jeff-h** [comment]
Sorry, as soon as I posted that I realised it's a dependency of RESTful so of course must already be on. But yes, plug is what will automatically instantiate your classes, so Drupal finding the classes is only half the battle. Also, Plug needs PHP 5.4.2 — is it possible that you're running something older on production?

**Comment by tripper54** [comment]
Running php 5.5 on production. It's an Acquia Enterprise setup.

**Comment by jeff-h** [comment]
> any calls to my custom resources return 404s

That does really sound like the menu cache needs flushing, but you've done that. I'm out of ideas :( I guess you'll have to get out the sledgehammer next and trace through where RESTful asks Plug which plugins it's finding?

**Comment by tripper54** [comment]
I've been fiddling around a bit more with this:
- I can replicate the problem on our staging server
- I've tried changing php version to 5.6 , and swapping memcache out for database cache. Neither fixed the problem.
- If I enable the plug_example module, the example plugins seem to be detected OK - the plug/test page lists found plugins as expected.
- this code:

``` php

$plugins = restful()
    ->getResourceManager()
    ->getPlugins();

```

Returns only the default plugins. On my local machine it returns the custom plugins.

**Comment by jeff-h** [comment]
That's really nicely isolated.

If you do something like the following at devel/php

``` php
print_r(
  restful()
    ->getResourceManager()
    ->getPlugins()
);
```

is there any interesting differences between the two (perhaps save each to a file and do a diff between them)?

Does:

``` php
$plugins = restful()
    ->getResourceManager();
```

return the same thing on both?

Can you xdebug in your staging server? If you pause inside `getPlugins()` can you compare what you see on your local with staging?

Sorry, I know those are all pretty basic steps, but this is intriguing me (and must be very frustrating to you).

**Comment by tripper54** [comment]
It's amazing what a lunch break will do for your perspective.

My declared namespace:
Drupal\ii_rest\Plugin\resource\entity

My directory structure:
ii_rest/src/plugin/Resource/entity

See what I did with the case?

Thanks so much for your help with this issue @jeff-h . I'm off to wipe some egg off my face now...

**Comment by jeff-h** [comment]
Crazy — it had to be something tiny, the problem being there are about 1,000 tiny things it could have been :) I'm intrigued — does your localhost ignore capitalisation?

**Comment by tripper54** [comment]
It seems it does:

```
diskutil info /
...
File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)

...

```

**Comment by jeff-h** [comment]
Wow, that's a trap :o I'm running Mamp so I'd easily have the exact same scenario.
