### ISSUE TITLE
restful()->something()->getAccount()

### ISSUE THREAD

**Issue by jeff-h** [RESTful-Drupal/restful#818]
I have a fair bit of pre-existing code that assumes the `global $user` is who's asking for things, and unfortunately that doesn't work when the request originates with RESTful, assuming non-cookie auth (right?).

Thus, I need to convert several bits of existing code to call RESTful's `->getAccount()`, outside the RESTful classes. I noticed you've provided `restful()` to handle this, but couldn't identify the pathway from there to  `getAccount()`.

Could someone help me with that? In other words,

`$account = restful()->` then what here? `->getAccount();`

Double-bonus points for showing me how to work this out for myself :D

**Comment by e0ipso** [comment]
You can call `getAccount()` from your resource.

**Comment by e0ipso** [comment]
I believe that there are a couple of tests that can serve as an example.

**Comment by jeff-h** [comment]
I ended up using:

``` php
$restful_account = restful()->getResourceManager()->negotiate()->getAccount();
```

Is that too simplistic? It works in my testing, but I'm a little unsure whether it's universally applicable enough to stick in the docs.

**Comment by e0ipso** [comment]
``` php
$resource = restful()->getResourceManager()->negotiate();
$resource->setRequest(restful()->getRequest());
$resource->getAccount();
```

**Comment by jeff-h** [comment]
Ah, thanks for that, much appreciated.

I've stuck a note in at https://github.com/RESTful-Drupal/restful/wiki/3.-Authentication#obtaining-the-current-user-in-custom-drupal-module-code

One further question — why doesn't RESTful simply authenticate the global Drupal user object? Isn't it likely that at some point some existing Drupal code (either contrib or core) is going to assume the user can be obtained by simply asking Drupal for the `global $user`?

I think it would be most useful for non-RESTful-aware code to be able to access the currently authenticated user transparently, regardless of where the request originated (i.e. whether a standard Drupal page-load, or whether RESTful has authenticated the current request). My legacy code has a bazillion hooks firing like fireworks, lots of them doing user-specific business logic, and none of them aware of RESTful :)

**Comment by e0ipso** [comment]
> why doesn't RESTful simply authenticate the global Drupal user object?

You could do that by implementing your authentication provider (probably inheriting from one in RESTful). The reasoning not to log the user in is for security. This way we execute code as anon user making access checks with the authenticated user. That avoids multiple hassles that we can't really solve.

**Comment by jeff-h** [comment]
I'm surprised there are issues you can't sensibly get around, but I'll have to take your word for that!

Due to that, I think I'll avoid creating a custom auth provider that logs the user in. I don't want a crop of unanticipated issues without clean solutions.

**Comment by e0ipso** [comment]
> I'm surprised there are issues you can't sensibly get around, but I'll have to take your word for that!

Sometimes it's just out of our hands.

**Comment by charlie-rushton** [comment]
@jeff-h I am pretty new to Drupal and PHP so wondering if you could help me with this. Been stuck on it for a few days. I have a Resource which is just getting public fields from a content type from my Drupal installation and returning them. But I need a function / something in my class that will retrieve the id of the current authenticated user. I have tried both the above methods posted by yourself and @e0ipso, but it just returns null. My code (as awful as it is) is below:

```php

/**
 * @file
 * Contains \Drupal\restful\Plugin\resource\Session__1_0.
 */

namespace Drupal\restful\Plugin\resource;

/**
 * Class Articles
 * @package Drupal\restful\Plugin\resource
 *
 * @Resource(
 *   name = "session:1.0",
 *   resource = "session",
 *   label = "Session",
 *   description = "Export the Session entity.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = FALSE,
 *   dataProvider = {
 *     "entityType": "node",
 *     "bundles": {
 *       "session_group",
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class Session__1_0 extends ResourceEntity implements ResourceInterface {

  /**
   * {@inheritdoc}
   */
  protected function publicFields()
  {
      $public_fields = parent::publicFields();

      // The mail will be shown only to the own user or privileged users.
      $public_fields['teacherName'] = array(
          'property' => 'field_teacher',
          'sub_property' => 'name',

      );

      $public_fields['teacherID'] = array(
          'property' => 'field_teacher',
          'sub_property' => 'uid',

      );

      $public_fields['status'] = array(
          'property' => 'field_status',

      );

      $public_fields['day'] = array(
          'property' => 'field_day',

      );

      $public_fields['time'] = array(
          'property' => 'field_time',

      );

      $public_fields['relative_time'] = array(
          'property' => 'field_relative_time',

      );

    $public_fields['uid'] = array(
      'property' => 'field_teacher',
      'sub_property' => 'uid',
      'process_callbacks' => array(
        '\Drupal\restful\Plugin\resource\Session__1_0::getUID',
      ),
    );

    return $public_fields;
  }

  public static function getUID() {
    $resource = restful()->getResourceManager()->negotiate();
    $resource->setRequest(restful()->getRequest());
    $resource->getAccount();

    return $resource->uid;
  }
}
```

**Comment by charlie-rushton** [comment]
@e0ipso can you possibly help me with this? It's for a project for a client and it's pretty time critical.

**Comment by e0ipso** [comment]
@charlie-rushton I am sorry, but I don't have the availability to look into this right now.

**Comment by jeff-h** [comment]
@charlie-rushton It's been so long since I used this code that unfortunately I really have no ideas :( In general terms though I would start by seeing whether any constituent parts of the code are not returning what you'd expect. For example, I would check the following (although in the case of Drupal + RESTful it may not be clear what object/class you're even supposed to be getting):

* `restful()->getResourceManager()`
* `restful()->getResourceManager()->negotiate();`
* especially this: `restful()->getRequest()`

Do you have xdebug set up? If so, the fallback option for me would be to trace line-by-line to see where it's unexpectedly getting a NULL.

Footnote: It's hard to believe this issue is from just ~4 years ago, as so much has changed for me since then. No criticism intended re: @e0ipso's work on this module — it's undoubtedly brilliant — but after 10+ years with Drupal I ended up moving to Laravel. Since then my code (including RESTful code) is infinitely simpler than it ever was with Drupal. In 2019, and especially if you're new to PHP, I'd really suggest you reexamine your choice of framework. The complexity exposed to the developer here is just mind-boggling by comparison to Laravel.  For example, in Laravel `$request->user()` retrieves the user who initiated the request.

**Comment by charlie-rushton** [comment]
@jeff-h Thanks for your reply. Trust me, I am not using Drupal through choice, if it was up to me I'd definitely be using Laravel. Unfortunately, my project is for a client who already has a fully functioning Drupal installation and wants a mobile app to integrate with this system. Thanks for your reply, I will give your suggestions a go. Cheers!
