### ISSUE TITLE
Token authentication in 2.x doesn't recognize http access token headers

### ISSUE THREAD

**Issue by lukewertz** [RESTful-Drupal/restful#819]
It seems that some browsers pass the access token key as a hyphen-separated string rather than an underscore-separated string. The 1.x branch had code to check for this: https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/modules/restful_token_auth/plugins/authentication/RestfulAuthenticationToken.class.php#L22

PR coming momentarily to add similar logic to 2.x.

**Comment by e0ipso** [comment]
Merged.

```
[FEATURE] Give access-token a new chance

Add support to access-token as a header name, instead of
access_token via code. Even if the key name can be changed in the
annotation, this is common enough to deserve some babysitting.
```

**Comment by e0ipso** [comment]
FWIY you can change the name of the header name in the token resource configuration and set it to hyphenated if you need to.

**Comment by lukewertz** [comment]
Thanks so much for your help with!
