### ISSUE TITLE
Call to undefined method EntityValueWrapper::entityKey() 

### ISSUE THREAD

**Issue by otsuarez** [RESTful-Drupal/restful#822]
I'm getting the following error:

```
PHP Fatal error:  Call to undefined method EntityValueWrapper::entityKey() in /home/vostro/drupal-7.41/sit
es/all/modules/restful/src/Plugin/resource/Field/ResourceFieldEntity.php on line 1165
Drush command terminated abnormally due to an unrecoverable error.                             [error]
Error: Call to undefined method EntityValueWrapper::entityKey() in
/home/vostro/drupal-7.41/sites/all/modules/restful/src/Plugin/resource/Field/ResourceFieldEntity.php,
line 1165
```

I tried on CentOS 7 with php 5.4.16 and Ubuntu 14.04 with php 5.5.9. Deployment steps can be found [here](https://gist.github.com/otsuarez/e1235ec082f54bc2215b).

The restful_example module seems to trigger that error.

I tried to follow an example from [fourkitchens blog](http://fourkitchens.com/blog/article/rest-easy-part-1-and-restful-you) but got the following error when trying to access the url for displaying the items. Same thing happened with a similar [tutorial](http://anthonygore.com/exposing-drupal-data-custom-restful-api-restful-module/).

```
{"type":"http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html#sec10.4.5","title":"Invalid URL path.","status":404,"detail":"Not Found"}
```

Any idea what might be happening?

**Comment by jeff-h** [comment]
Both the tutorials you referenced were written for RESTful v1.x, not 2.x, the latter being a significant rewrite. Tutorials for 1.x are probably still useful at a general level, but any code they contain is unlikely to work as-is with 2.x.

There's a _Learning RESTful_ section in the wiki at https://github.com/RESTful-Drupal/restful/wiki#learning-restful — hopefully that will be helpful.

I haven't dug into the error you've encountered; I'm happy to, but could you first see if it's possibly caused by you attempting to use some 1.x code whilst running the 2.x module?

**Comment by otsuarez** [comment]
I just did a fresh drupal 7 (7.41) + restful 2.x module installation. Using the commands on the travis.yml file from this repo. The PHP Fatal error appears as soon as I enable the restful_example module.

**Comment by jeff-h** [comment]
That's really weird. I followed your deployment steps from [your first comment](https://github.com/RESTful-Drupal/restful/issues/822#issue-127032901) (very helpful!) and it worked perfectly for me (MAMP, php 5.6.10).

Do you get the error immediately after your `drush enable` or are you attempting to do something else after that e.g. access an endpoint? I only tried a simple GET to `http://localhost/drupal-7.41/api` and it worked just fine.

**Comment by jeff-h** [comment]
Also tried PHP 5.5.26 (the oldest I have) to attempt to rule out PHP version as a problem, and it still worked fine for me.

**Comment by e0ipso** [comment]
> The PHP Fatal error appears as soon as I enable the restful_example module.

Does it appear in any page? Only RESTful pages?

**Comment by e0ipso** [comment]
Also, since you may have guessed this is not reproducible in Travis' Ubuntu (since Travis uses that script for the builds, and they are passing).

Can you check the related module versions?

**Comment by otsuarez** [comment]
After reinstalling everything from scratch everything now it's working ok. Thanks for the support guys.

**Comment by terryzwt** [comment]
I still have this issue on php 7. after I enable the restful_example module.

**Comment by e0ipso** [comment]
@terryzwt what version are you running?

**Comment by terryzwt** [comment]
@e0ipso the lastest dev. here is the info I get from the restful.info.
I download the module from drupal.org.

```
; Information added by Drupal.org packaging script on 2016-02-25
version = "7.x-2.7+1-dev"

```

**Comment by novartema** [comment]
I also encountered the same problem. After enabling the restful_example module I get this error.
It happened because I deleted default Article node type and/or disabled the Comment module. When I added the content type and enabled the module then the error is disappeared. Now everything it's working ok.
Hope it help you.

**Comment by novartema** [comment]
`{"type":"http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html#sec10.4.5","title":"Invalid URL path.","status":404,"detail":"Not Found"}`

Correct:

```
* @Resource(
 *   name = "test-news:1.0",
 *   resource = "test-news",
```

Wrong:

```
* @Resource(
 *   name = "testnews:1.0",
 *   resource = "test-news",
```

If I understand correctly part of name before the colon and resource should be equal.

**Comment by BevanR** [comment]
I got this too.  I had the comments module disabled.  Deleting `src/Plugin/resource/comment` fixed it for me.  I expect re-enabling the comments module would also have fixed it.  Perhaps the examples module should depend on the `comments` module?

**Comment by laradevitt** [comment]
Also confirming enabling restful_example module while comment module is disabled caused this error when visting /api URL. Agree that comment module should be included as a dependency. Of course this doesn't solve @novartema's other problem of having a nonexistent 'Article' content type.
