### ISSUE TITLE
Can RESTful-Drupal sort and filter datetime data from the Date module?

### ISSUE THREAD

**Issue by adam-s** [RESTful-Drupal/restful#823]
I'm using the [Date module](https://www.drupal.org/project/date) to store event dates. I was curious if I can make API calls with filters and sorts against the date field? I couldn't find anything in the code that handles this, only for timestamp fields.

**Comment by e0ipso** [comment]
RESTful uses EntityFieldQuery to do sorts. That means that an SQL query gets automatically generated. Depending on how you're saving your dates in the database the sort will work as you expect or not.

This is not handled at all in the RESTful module, so you will need to fix this someplace else.

**Comment by adam-s** [comment]
The condition filter for DateTime uses a string. Since the date field value is stored with the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format in the database, the condition value for the filter needs to be in the same format. `example.com/api/v1.1/events?range=10&filter[date][value]=2016-02-08T01:24:03+00:00&filter[date][operator]=>=`

**Comment by e0ipso** [comment]
Additional note: You may want to wrap `>=` in quotes.
