### ISSUE TITLE
Using the json-api formatter with the internale Drupal API, 'include' is not respected.

### ISSUE THREAD

**Issue by adam-s** [RESTful-Drupal/restful#826]
The json-api URL spec works as expected. This works:

```
http://local954live.com/api/event?filter[artists.id]=35&include=artists
```

However, this isn't. The 'include' portion of the return object is not added using the internal API:

```
       $query = array(
            'include' => 'artists',
            'filter' => array(
                'artists.id' => 35
            ),
        );
```

Fortunately, the other formatters work correctly.

**Comment by e0ipso** [comment]
I'm not sure I see what you are trying to accomplish there. Can you post
some more context and code?

**Comment by adam-s** [comment]
Using [api_drupal](https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/docs/api_drupal.md), with the json-api formatter choice, I can not get the returned JSON object to include the referenced resource objects.

Here is the plugin for the Event resource:

```
<?php
/**
 * Created by PhpStorm.
 * User: adam
 * Date: 1/18/16
 * Time: 7:46 AM
 */

namespace Drupal\livesource\Plugin\resource\entity\node\event;

use Drupal\restful\Plugin\resource\ResourceInterface;
use Drupal\restful\Plugin\resource\ResourceNode;

/**
 * Class Event__1_0
 * @package Drupal\livesource\src\Plugin\resource\entity\node\event
 *
 * @Resource(
 *   name = "event:1.0",
 *   resource = "event",
 *   label = "Event",
 *   description = "Export the event with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "node",
 *     "bundles": {
 *       "event"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class Event__1_0 extends ResourceNode implements ResourceInterface{
    /**
     * {@inheritdoc
     */
    protected function publicFields() {
        $public_fields = parent::publicFields();

        $public_fields['id']['methods'] = array();

        // Rename label to name;
        $public_fields['title'] = $public_fields['label'];
        unset($public_fields['label']);
        unset($public_fields['self']);
        unset($public_fields['links']);

        $public_fields['venue'] = array(
            'property' => 'field_venue_reference',
            'resource' => array(
                'name' => 'venue',
                'full_view' => TRUE,
                'majorVersion' => '1',
                'minorVersion' => '0'
            )
        );

        $public_fields['artists'] = array(
            'property' => 'field_artist_reference',
            'resource' => array(
                'name' => 'artist',
                'majorVersion' => '1',
                'minorVersion' => '0'
            )
        );

        return $public_fields;
    }
}
```

Now I call it with the api_drupal code:

```
$handler = restful()
  ->getResourceManager()
  ->getPlugin('event:1.0');

$query = array(
    'include' => 'artists, venue',
    'filter' => array(
        'artists.id' => 35
    ),
);

$result = restful()
  ->getFormatterManager()
  ->format($handler->doGet('', $query));
```

I'm not sure if it is written correctly. It works correctly when used in the URL. Both techniques are processed the same by \Drupa\restful\Http|Request fixQueryFields method. At some point the include property is getting lost.

I'm getting: 

```
{ "data": [ { "type": "event", "id": "38", "attributes": { "title": "Secondhand Serenade at Revolution Live on 03-25-2015" }, "relationships": { "venue": { "data": { "type": "venue", "id": "27" } }, "artists": { "data": [ { "type": "artist", "id": "35" }, { "type": "artist", "id": "36" }, { "type": "artist", "id": "37" }, { "type": "artist", "id": "39" } ] } }, "links": { "self": "http:\/\/local954live.com\/api\/v1.0\/event\/38" } } ] }
```

Instead of:

```

{"data":[{"type":"event","id":"38","attributes":{"title":"Secondhand Serenade at Revolution Live on 03-25-2015"},"relationships":{"venue":{"data":{"type":"venue","id":"27"},"links":{"related":"http:\/\/local954live.com\/api\/v1.0\/event?filter[venue]=27","self":"http:\/\/local954live.com\/api\/v1.0\/venue\/38\/relationships\/venue"}},"artists":{"data":[{"type":"artist","id":"35"},{"type":"artist","id":"36"},{"type":"artist","id":"37"},{"type":"artist","id":"39"}],"links":{"related":"http:\/\/local954live.com\/api\/v1.0\/event?filter[artists]=35","self":"http:\/\/local954live.com\/api\/v1.0\/artist\/38\/relationships\/artists"}}},"links":{"self":"http:\/\/local954live.com\/api\/v1.0\/event\/38"}}],"included":[{"type":"artist","id":"35","attributes":{"id":"35","self":"http:\/\/local954live.com\/api\/v1.0\/artist\/35","name":"Secondhand Serenade","body":null,"genre":["\u003Ca href=\u0022\/genres\/pop\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EPop\u003C\/a\u003E"],"website":{"url":"http:\/\/www.secondhandserenade.com\/","title":null,"attributes":[]}},"links":{"self":"http:\/\/local954live.com\/api\/v1.0\/artist\/35"}},{"type":"artist","id":"36","attributes":{"id":"36","self":"http:\/\/local954live.com\/api\/v1.0\/artist\/36","name":"Ryan Cabrera","body":null,"genre":["\u003Ca href=\u0022\/genres\/acoustic\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EAcoustic\u003C\/a\u003E\u003Ca href=\u0022\/genres\/pop-rock\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EPop Rock\u003C\/a\u003E\u003Ca href=\u0022\/genres\/classical\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EClassical\u003C\/a\u003E\u003Ca href=\u0022\/genres\/death-metal\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EDeath Metal\u003C\/a\u003E","\u003Ca href=\u0022\/genres\/acoustic\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EAcoustic\u003C\/a\u003E\u003Ca href=\u0022\/genres\/pop-rock\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EPop Rock\u003C\/a\u003E\u003Ca href=\u0022\/genres\/classical\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EClassical\u003C\/a\u003E\u003Ca href=\u0022\/genres\/death-metal\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EDeath Metal\u003C\/a\u003E","\u003Ca href=\u0022\/genres\/acoustic\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EAcoustic\u003C\/a\u003E\u003Ca href=\u0022\/genres\/pop-rock\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EPop Rock\u003C\/a\u003E\u003Ca href=\u0022\/genres\/classical\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EClassical\u003C\/a\u003E\u003Ca href=\u0022\/genres\/death-metal\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EDeath Metal\u003C\/a\u003E","\u003Ca href=\u0022\/genres\/acoustic\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EAcoustic\u003C\/a\u003E\u003Ca href=\u0022\/genres\/pop-rock\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EPop Rock\u003C\/a\u003E\u003Ca href=\u0022\/genres\/classical\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EClassical\u003C\/a\u003E\u003Ca href=\u0022\/genres\/death-metal\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EDeath Metal\u003C\/a\u003E"],"website":{"url":"http:\/\/www.ryancabrera.com\/","title":null,"attributes":[]}},"links":{"self":"http:\/\/local954live.com\/api\/v1.0\/artist\/36"}},{"type":"artist","id":"37","attributes":{"id":"37","self":"http:\/\/local954live.com\/api\/v1.0\/artist\/37","name":"Nick Thomas","body":null,"genre":["\u003Ca href=\u0022\/genres\/pop-rock\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EPop Rock\u003C\/a\u003E"],"website":{"url":"http:\/\/nickthomasmusic.com\/","title":null,"attributes":[]}},"links":{"self":"http:\/\/local954live.com\/api\/v1.0\/artist\/37"}},{"type":"artist","id":"39","attributes":{"id":"39","self":"http:\/\/local954live.com\/api\/v1.0\/artist\/39","name":"Wind in Sails","body":null,"genre":["\u003Ca href=\u0022\/genres\/acoustic\u0022 typeof=\u0022skos:Concept\u0022 property=\u0022rdfs:label skos:prefLabel\u0022 datatype=\u0022\u0022\u003EAcoustic\u003C\/a\u003E"],"website":null},"links":{"self":"http:\/\/local954live.com\/api\/v1.0\/artist\/39"}}],"meta":{"count":1},"links":{"self":"http:\/\/local954live.com\/api\/v1.0\/event?filter[artists.id]=35\u0026include=artists"}}
```

**Comment by e0ipso** [comment]
What is your use case for using the API programatically instead of using the URL?

**Comment by adam-s** [comment]
So many awesome bands coming to town. I made a list of upcoming bands with media to listen to them. For example, http://954live.com/artist/bleachers I haven't updated it in a while. It is a prototype. As stupid and simple it is, it is so much better than the Bands in Town, MySpace and Ticketmaster websites for finding upcoming shows. I didn't want to use views. Quickly EntityFieldQuery started to have some problems. It was much slower than views and I would have to manage the cache myself. On top of that I was responsible for formatting every field. So I wound up with a view like this: 

![image](https://cloud.githubusercontent.com/assets/232388/12507225/69cb7df6-c0c2-11e5-8905-538fc79fd926.png)

That view is even worse because there are three or four template and as many preprocess functions.

With another couple hundred lines of code using RESTful I'll have all the same information with the same if not better caching than I get with Views. Unlike hacking Views and Entities, the information is very clean and structured, almost out of the box. Why not just create a single page app and use REST? The site was just supposed to be for my city, but last summer Google sent 10,000s of people to some of the pages. [Google rewards website with structured data](https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252F954live.com%252Fartist%252Fbleachers). This is because Drupal's SEO and metadata is leveraged. Microdata, Pathauto, Metatag, FileField Paths, and Token are all there. That is where the magic is. 

![image](https://cloud.githubusercontent.com/assets/232388/12507446/dd22b07a-c0c3-11e5-8bd7-3aa84472581c.png)

I built a web scraper that is a search engine which populates the fields using Angular, Node, MongoDB, Express. I going to rebuild 954live and wire it up using the RESTapi to the Drupal site. If I can monetize the site by either ads or referral on tickets I'll start adding more features. It won't be hard to switch from Drupal building pages to Angular using JSON api.

The website is only going to have four different view types, a front page with the next weeks upcoming shows, a view for each venue, a view for each band, and a view for each taxonomy term.

It's just fun. A side project to learn these different technologies.

**Comment by e0ipso** [comment]
Sorry I wasn't clear. I mean, why are you using the programatic API instead of hitting the endpoint via AJAX/JS framework?

Are you building the page in the server using RESTful as a query builder?

**Comment by adam-s** [comment]
Yes, I'm using RESTful as a query builder. When I read the documentation about "[Using Your API Within Drupal](https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/docs/api_drupal.md)" I thought that was the correct use case. Is there some reason I shouldn't do this? There is a threshold where Views is far too crufty  to be useful. I have two good reason to use RESTful this way, in my mind.  It simplifies everything on the server, no more bits and pieces all over the place -- theme function here, theme function there, template here, template within another template there. Second, as I start to develop the site more as a single page app, the REST server is already there and defined. I can switch out parts from Drupal to Angular.

I want to show an artist profile with a list of upcoming events. Each event on that list will contain information about about the venue and all the other artist that will be playing that night. Once media management of images, audio, and sound is involved, this becomes too much for Views and on the other hand writing and formatting custom queries is a lot of work. 

This morning I already have the database set up and will be passing information in many of the $public_fields item to a process function to be formatted if I don't want to use the formatted out of the box. Now all my code is consistently structured in one place. That makes sense to me.

**Comment by e0ipso** [comment]
@adam-s using RESTful as a query builder is a very legit thing to do, I was just curious.

This bugs seems to be something to look into.

**Comment by adam-s** [comment]
I'm about to start theming. I can't even begin to describe the good feeling I have right now knowing that I can do anything I want without having to worry about finding theme templates and theme functions in Drupal, without worrying about embedded markup embedded in more embedded markup calling theme functions and preprocess functions all over the place. I feel a huge amount of control and really good about this. I hope it works.

**Comment by e0ipso** [comment]
Everything is working in the tests for JSON API. Did you check how the tests are implementing this?

**Comment by adam-s** [comment]
I quickly walked through all the classes in the test folder that extend `\Resource` class, e.g. `TestArticles__1_0.php` and `Main__1_0.php`, and I couldn't find a case using a field formatter especially a multi value field which seems to be breaking for me. Nor did a text search of the resource directory in the Test folder find any instances. 

I've been using the field formatter to render HTML, for example: 

```
        $public_fields['genres'] = array(
            'property' => 'field_genres',
            'formatter' => 'term_term'
        );
```

I'm not sure how the tests are implementing this. This is breaking on fields that have multi values.

**Comment by e0ipso** [comment]
I invite you to take a closer look. Because there are different examples of this in the tests. In particular there is `RestfulJsonApiTestCase`.

If you do this, you'll have to post less support requests which will take a while to get addressed.

**Comment by e0ipso** [comment]
I'm going to close this, but feel free to request a reopen.
