### ISSUE TITLE
RESTful calls methods that only exist in \EntityDrupalWrapper on entities that are wrapped with \EntityValueWrapper.

### ISSUE THREAD

**Issue by adam-s** [RESTful-Drupal/restful#829]
Reference: #828, #376

A couple Drupal modules have fields that reference other entities, for example, [Field Collection](https://www.drupal.org/project/field_collection) and [Media](https://www.drupal.org/project/media). The referenced entities contained in fields belonging to these modules are wrapped with the \EntityValueWrapper class not the \EntityDrupalWrapper which wraps entities that are attached by the entity reference widget. 

RESTful assumes that certain methods and members exist which don't. RESTful calls method \EntityValueWrapper::getBundle() on the Field Collection field at  \Drupal\restful\Plugin\resource\Field\ResourceFieldEntity line 797, `'bundle' => $this->getBundle()`, and tries to set a non existent property `bundle` on the \EnitityValueWrapper::bundle object with the Media field at  \Drupal\restful\Plugin\resource\Field\ResourceFieldEntity line 81, `$this->bundle = $bundle;`.

What is happening is that RESTful is calling `function entity_metadata_wrapper` in entity_module and expects that the entity will be wrapped with `\EntityDrupalWrapper` which is not always the case. Sometimes fields that reference other entities are wrapped with `\EntityValueWrapper`

```
function entity_metadata_wrapper($type, $data = NULL, array $info = array()) {
  if ($type == 'entity' || (($entity_info = entity_get_info()) && isset($entity_info[$type]))) {
    // If the passed entity is the global $user, we load the user object by only
    // passing on the user id. The global user is not a fully loaded entity.
    if ($type == 'user' && is_object($data) && $data == $GLOBALS['user']) {
      $data = $data->uid;
    }
    return new EntityDrupalWrapper($type, $data, $info);
  }
  elseif ($type == 'list' || entity_property_list_extract_type($type)) {
    return new EntityListWrapper($type, $data, $info);
  }
  elseif (isset($info['property info'])) {
    return new EntityStructureWrapper($type, $data, $info);
  }
  else {
    return new EntityValueWrapper($type, $data, $info);
  }
}
```

I successfully got the Field Collection field to work by adding a condition so the entity is wrapped with `\EntityDrupalWrapper`. I couldn't get the media field to work though.

```
  if ($type == 'entity' || $type=="field_collection_item" || (($entity_info = entity_get_info()) && isset($entity_info[$type]))) {
```

EDIT: My bad, this is not the same problem with the Media module. The reference field for the Media module is wrapped with `EntityDrupalWrapper`. Now the Entity wrapper is \EntityStructureWrapper. Did it somehow inherit the wrapper from it's parent?

**Comment by e0ipso** [comment]
> The referenced entities contained in fields belonging to these modules are wrapped with the \EntityValueWrapper class not the \EntityDrupalWrapper which wraps entities that are attached by the entity reference widget.

I may be wrong, but I don't believe this to be accurate.

If you are wrapping an entity with `entity_metadata_wrapper` and passing the entity type as the first argument you have `\EntityDrupalWrapper`(the EMW of the entities). Variables are even type hinted with that class.

If you end up having RESTful having `\EntityValueWrapper`, then you should take a look to your field definitions and annotations because the problem is probably there.

This line reinforces these suspicions:

> Now the Entity wrapper is \EntityStructureWrapper. Did it somehow inherit the wrapper from it's parent?

**Comment by adam-s** [comment]
As mentioned above in 

`'bundle' => $this->getBundle(),`

$this is an instance \EntityValueWrapper that doesn't have a `getBundle()` method. I used a vanilla installation of Drupal and only had the Field Collection field on a node. I didn't write any code that wraps anything. I just hacked it for a moment to see if passing a Field Collection item to \EntityDrupalWrapper will make the `getBundle()` method available so when it runs through the RESTful code it works. And, it works with that little hack. 

I still can't get the Media video to output. Perhaps, someone could try using [Media YouTube](https://www.drupal.org/project/media_youtube) with RESTful to see what is wrong.

**Comment by e0ipso** [comment]
Just to be clear: "$this is an instance \EntityValueWrapper" that's your problem. You're not loading the fc correctly before passing it to the EMW or the annotation is wrong.

**Comment by adam-s** [comment]
This is what I have

```
/**
 * Class fieldSocial__1_0
 * @package Drupal\livesource\Plugin\resource\entity\fieldCollection
 *
 * @Resource(
 *   name = "fieldSocial:1.0",
 *   resource = "fieldSocial",
 *   label = "field_social",
 *   description = "Export the field_social with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "field_collection_item",
 *     "bundles": {
 *       "field_social"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
```

**Comment by e0ipso** [comment]
Please make sure that `field_collection_item` is a valid entity type. See the code below.

![2016-01-28 11-56-33](https://cloud.githubusercontent.com/assets/1140906/12642439/0658bede-c5b6-11e5-90df-ca925a6d52a1.png)

**Comment by adam-s** [comment]
isset($entity_info[$type]) is false because the type is `list<field_collection_item>` although the key in $entity_info is `field_collection_item`. Therefore it gets the EntityListWrapper which does not have the ::getBundle() method. 

![screenshot from 2016-01-28 06 28 45](https://cloud.githubusercontent.com/assets/232388/12643357/98d01f46-c589-11e5-957b-6f3e5dbcac7e.jpg)

**Comment by e0ipso** [comment]
I assume you already figured this out, but I'm posting for future searches.

Right. `EntityListWrapper` will be unwrapped to each of their elements. Each element in the list **must** be an `EntityDrupalWrapper`.
