### ISSUE TITLE
Use namespaces to simplify class names.

### ISSUE THREAD

**Issue by e0ipso** [RESTful-Drupal/restful#83]
Class names are getting crazy lately. Maybe we should start thinking about adding a root namespace `\Restful` and then `use` it everywhere. Deeper nesting can also provide some clarity.

Maybe we'll need to depend on xhautoload, but I think that would be an overkill at this point.

@amitaibu thoughts?

**Comment by e0ipso** [comment]
@amitaibu do you think this is something worth looking into it?

**Comment by amitaibu** [comment]
> Maybe we'll need to depend on xhautoload, but I think that would be an overkill at this point.

Yeah, lets keep it simple. For now it think this can be postponed.

**Comment by amitaibu** [comment]
Namespaces will be used in the D8 version.
