### ISSUE TITLE
When rendering a field value with the field formatted there isn't a guarantee that the #theme function is 'field'.

### ISSUE THREAD

**Issue by adam-s** [RESTful-Drupal/restful#831]
line 511 of `ResourceFieldEntity.php` unsets the #theme function of the element. This does make a much clearer result except there is no guarantee that contributed modules, for example, the Social Links module, don't directly render items without wrapping the output in the field markup and classes. Perhaps, the responsibility of controlling the wrapping of rendered output should go to the developer either by implementing preprocess functions or overriding themes.

Personally, I like very clean minimal code so removing extra markup and unused css classes is nice. I changed it to this.

```
    // Unset the theme, as we just want to get the value from the formatter,
    // without the wrapping HTML.
    if ($output['#theme'] == 'field') {
      unset($output['#theme']);
    }
```

Perhaps, a better solution is to include configuration in the 'formatter' property. For example:

```
       $public_fields['address'] = array(
            'property' => 'field_address',
            'render' => array(
                'formatter' => 'addressfield_default',
                'clean' => TRUE,
            )
        );
```

EDIT: Not sure what is going on here because the behavior making a URL api call at http://new954live.com/api/events yields a different result than using the internal Drupal API. 

```
{
    data: [{
        title: "Europe",
        venue: {
            id: "3",
            self: "http://new954live.com/api/v1.0/venues/3" 
            name: "Revolution Live",
            address: "<div class="street - block "><div class="thoroughfare ">100 SW 3rd Ave</div></div> <div class="addressfield - container - inline locality - block country - US "><span class="locality ">Fort Lauderdale</span>, <span class="state ">FL</span> <span class="postal - code ">33312</span></div> "
        },
        artists: [{
            id: "2",
            self: "http://new954live.com/api/v1.0/artists/2",
            name: "Europe",
            social: "<div class="field field - name - field - social field - type - social - links - field field - label - above social - links "><div class="field - label ">Social</div><ul class="field - items "><li class="field - item service - twitter "><a href="https: //twitter.com/europetheband" target="_blank"><i class="icon icon-twitter"></i></a></li> <li class="field-item service-facebook"><a href="https://www.facebook.com/europetheband" target="_blank"><i class="icon icon-facebook"></i></a></li> <li class="field-item service-website"><a href="http://www.europetheband.com/" target="_blank"><i class="icon icon-website"></i></a></li> </ul></div>"
        }]
    }],
    count: 1,
    self: {
        title: "Self",
        href: "http://new954live.com/api/v1.0/events"
    }
}
```

Nonetheless, if the #theme property on the render array is unset the social field will not render. It looks like the developer of the Social Links module hacked it. Function [`hook_field_formatter_view`](https://api.drupal.org/api/drupal/modules%21field%21field.api.php/function/hook_field_formatter_view/7) expects a return value that is "a renderable array for the $items, as an array of child elements keyed by numeric indexes starting from 0." [I submitted a patch.](https://www.drupal.org/node/2655818)

**Comment by e0ipso** [comment]
The support for formatters is very limited, since you will typically want to format the content in the front-end app. I don't think I want to support `'clean'  => FALSE`.

Thanks for documenting this! This will clarify things for other people.

**Comment by adam-s** [comment]
RESTful has it correct as is. Other module builders should be expected to adhere to Drupal coding specifications. The field formatter gets passed a render element array starting at 0. The Social Field module didn't do that and broke. It took me a minute to find the bug and it was in the other contributed module.
