### ISSUE TITLE
Critical Bug: Access-Token Header Doesn't Work

### ISSUE THREAD

**Issue by josephdpurcell** [RESTful-Drupal/restful#833]
Using the latest branch `7.x-2.x`, when sending a request with a header like:

```
Access-Token: 123
```

The access token is not read from the headers.

This is because on line 95 of `vendor/drupal/restful/modules/restful_token_auth/src/Plugin/authentication/TokenAuthentication.php` the condition is incorrect. It is currently:

```
if (empty($input[$key_name]) && $request->getHeaders()->get($key_name)->getValueString()) {
```

And it should be something like:

```
if (empty($input[$key_name]) && empty($request->getHeaders()->get($key_name)->getValueString())) {
```

**Comment by josephdpurcell** [comment]
For me, RESTful is broken in a critical way. Here is how:
- Sending `Access-Token: 123` forces RESTful to read `Access_Token`
- Sending `Access_Token: 123` forces RESTful to read `Access-Token`

There is no now way to authenticate the user via headers.

**Comment by josephdpurcell** [comment]
Is there any progress on this issue?

**Comment by fpalluel** [comment]
Hello,
Just a message to thank you ! I spent HOURS trying to debug my app (EmberJs frontend and drupal Restful backend, on different domains), and your fix saved me !
Indeed, the token authentication is broken without your patch...

**Comment by amitaibu** [comment]
Can you please provide this as a pull request?

**Comment by fpalluel** [comment]
I guess this it :
https://github.com/RESTful-Drupal/restful/issues/834

**Comment by e0ipso** [comment]
Fixed!
