### ISSUE TITLE
Broken Upgrade: Author No Longer Set

### ISSUE THREAD

**Issue by josephdpurcell** [RESTful-Drupal/restful#835]
In Restful 1x, the author would get set automatically.

In Restful 2x, the author does not.

See comment https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/src/Plugin/resource/DataProvider/DataProviderEntity.php#L959
and implementation https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/src/Plugin/resource/DataProvider/DataProviderEntity.php#L341

This is a breaking change for existing APIs. It should either be fixed or documented.

**Comment by e0ipso** [comment]
> This is a breaking change for existing APIs. It should either be fixed or documented.

That is not necessarily true. A major version change implies breaking changes.

**Comment by e0ipso** [comment]
Also, entities in general don't have authors. Nodes (among others) do.

https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/src/Plugin/resource/ResourceNode.php#L25

**Comment by josephdpurcell** [comment]
Ah! I see the difference now, my apologies.

The entity base in 1x also does not set the author: https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/plugins/restful/RestfulEntityBase.php#L995

This was an oversight on my part, thank you for helping me understand.
