### ISSUE TITLE
Class 'Drupal\restful\RestfulManager' not found

### ISSUE THREAD

**Issue by Amalanvr** [RESTful-Drupal/restful#836]
Fatal error: Class 'Drupal\restful\RestfulManager' not found in C:\xampp\htdocs\scholar\sites\all\modules\contrib\restful\restful.module on line 159

I got this error during installation of the module.
Even though RestfulManager is present in restful/src/RestfulManager.php

restful Version: 7.x-2.5

**Comment by e0ipso** [comment]
Did you install all the dependencies and clear your caches and registry?

Please, feel free to request a re-open.
