### ISSUE TITLE
Drupal 8

### ISSUE THREAD

**Issue by rroblik** [RESTful-Drupal/restful#846]
Hi,

I recently switched to Drupal 8 for a new project. My question is simple : when will the 8.x release be there ? 

I loved the 7.x.2 structure and the power of this module so ...

I only see short answer here https://github.com/RESTful-Drupal/restful/issues/650#issuecomment-140544640 but maybe you can be more precise !

Regards

**Comment by e0ipso** [comment]
There will be a port to Drupal 8 as soon as I can get funding to invest my time on it, or one of my clients needs it. Otherwise it will have to wait since my free time it pretty much packed right now.

**Comment by rroblik** [comment]
Any news about that ? Thinks we are reaching the limit of "Open Source" here :(

**Comment by jeff-h** [comment]
On the contrary, this is the beauty of open source! If you need faster progress than what you are being given, you have several options available to you. With closed-source you have exactly zero options :)

Some options for you:

a) fund or partially fund one of the maintainers to work on the d8 version
b) fork the repo and create a d8 version of your own
c) fund someone of your own choosing to do b)

Practically, the above require either a lot of $ or a lot of development skill. If you don't have sufficient of either you still have options:

a) take on some clients whose projects could benefit from this module; work into your invoices a line item for d8 RESTful development (enabling a or c above). Pretty easy to justify that kind of line-item in my experience.
b) spread the word on RESTful (blog posts, tutorials, meet-up sessions etc), thereby creating a larger user base around the module. Doing so will likely ultimately increase the demand for a d8 version, and consequently likely also bring on board more developers capable of helping out with the code, and/or companies capable of sponsoring it.

**Comment by e0ipso** [comment]
I love how you put it @jeff-h. Thanks for jumping in.

**Comment by amitaibu** [comment]
@jeff-h :+1:

**Comment by amitaibu** [comment]
@jeff-h btw, your comment could be easily expanded to a great blog post, which I'll always link to on similar situations :)

**Comment by jeff-h** [comment]
Thanks for the encouragement! Sadly I'm not much of a blogger...

**Comment by amitaibu** [comment]
> Sadly I'm not much of a blogger...

Well, I could help you with that and would love to publish it in Gizra's blog as a guest post. We've done it several times before even about [RESTful](http://www.gizra.com/content/restful-backbone-marionette/) with @infiniteluke, and it was much fun :)

**Comment by amitaibu** [comment]
(you can ping me amitai@gizra.com and we can discuss it)
