### ISSUE TITLE
RESTful does not return a value using 'wrapper_method' on 'public_fields' with entity type 'taxonomy_term'.

### ISSUE THREAD

**Issue by adam-s** [RESTful-Drupal/restful#847]
I have set a 'public_fields' value for bundle and use the Entity wrapper method `getBundle()` to acquire the value. The system crashes with a 500 error stating 'Unknown data property vocabulary_machine_name.

```
{
type: "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1",
title: "Unknown data property vocabulary_machine_name.",
status: 500
}
```

I attempted to follow the direction of the test case for saving Taxonomy terms at least and added a `dataProviderClassName()` method to the `ResourceEntity` class. 

```
<?php
/**
 * Created by PhpStorm.
 * User: adam
 * Date: 1/18/16
 * Time: 8:19 PM
 */

namespace Drupal\livesource\Plugin\resource\livesearch;

use Drupal\restful\Plugin\resource\ResourceEntity;

/**
 * Class LivesearchGenres__1_0
 * @package Drupal\livesource\Plugin\resource\livesearch
 *
 * @Resource(
 *   name = "livesearchGenres:1.0",
 *   resource = "livesearchGenres",
 *   label = "Livesearch Genres",
 *   description = "Export the genres with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "taxonomy_term",
 *     "bundles": {
 *       "genres"
 *     },
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */

class LivesearchGenres__1_0 extends ResourceEntity {
    /**
     * {@inheritdoc
     */
    protected function publicFields() {

        $public_fields = parent::publicFields();
        $public_fields['name'] = $public_fields['label'];
        unset($public_fields['label']);

        $public_fields['bundle'] = array(
            'wrapper_method' => 'getBundle',
            'wrapper_method_on_entity' => TRUE,
        );

        $public_fields['url'] = array(
            'wrapper_method' => 'value',
            'wrapper_method_on_entity' => TRUE,
            'process_callbacks' => array(
                array($this, 'uriProcess'),
            ),
        );

        return $public_fields;
    }

    public function uriProcess ($entity) {
        $uri =  entity_uri('taxonomy_term', $entity);
        $path =  drupal_get_path_alias($uri['path']);
        return url($path);
    }

    /**
     * {@inheritdoc}
     */
    public function dataProviderClassName()
    {
        return '\Drupal\restful\Plugin\resource\DataProvider\DataProviderTaxonomyTerm';
    }

}
```

There is some strange behavior happening. First, the `DataProviderTaxonomyTerm` classes is loaded but the `setPropertyValues` method is never called setting the `vocabulary_machine_name` property that is in question here. The second odd behavior is that Drupal bootstraps twice. There might be a redirect sent along with the response cause it to run twice.

**Comment by adam-s** [comment]
I just realized setPropertyValues is not called. The system is just getting property values. I'll look into it.

**Comment by e0ipso** [comment]
@adam-s did you find anything unusual in this one? Can we close it?

**Comment by adam-s** [comment]
I can filter on node type. For example, I can filter all the articles but not any other nodes of type blog or page. This can be useful. However, it is not possible to do the same for taxonomy vocabularies. I don't know if this is a bug or this is how it works by design.

Close it and if someone else has a problem with this edge case which nobody will it probably has something to do with DataProviderEntity::setPropertyValues() method not setting a property `vocabulary_machine_name`.

**Comment by e0ipso** [comment]
Thanks for circling back to this. Closing as per the comment above.

**Comment by raystuart** [comment]
To give a little more information on this in case anyone else encounters this issue...

We are seeing the same with setting `wrapper_method` to `getBundle()` on taxonomy_term resources, with the same error message `Unknown data property vocabulary_machine_name.`

However, if we set `wrapper_method_on_entity` to `FALSE`, then it works as desired! Only for `getBundle()` as far as we can see. Setting `wrapper_method` to `label` or `getIdentifier` (or any other available methods) requires `wrapper_method_on_entity` to be `TRUE` as normal.

This outputs the vocabulary machine name correctly:
```
    $public_fields['test'] = [
      'wrapper_method' => 'getBundle',
      'wrapper_method_on_entity' => FALSE,
    ];
```

This throws the error:
```
    $public_fields['test'] = [
      'wrapper_method' => 'getBundle',
      'wrapper_method_on_entity' => TRUE,
    ];
```
