### ISSUE TITLE
multiple filters: OR instead of AND?

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#848]
Is it possible to have multiple filters in a request combined with OR instead of AND?

For example, when our users search for a company, they might use the company name or the stock code. So can the client submit a single search term and set the filters so a match in EITHER 'name' or 'stock code' returns a response?

Thanks!

**Comment by tripper54** [comment]
Looking into this I have found the isValidConjunctionForFilter() method on DataProvider classes. 

Why does DataProviderEntity only provide AND as an allowed conjunction?

**Comment by adam-s** [comment]
I don't know if the it is the best solution but it works. Extend the DataProviderEntity class and add a tag to the query.

DataProviderArtists.php:

```
<?php

/**
 * @file
 * Contains \Drupal\restful\Plugin\resource\DataProvider\DataProviderNull.
 */

namespace Drupal\livesource\Plugin\resource\entity\node\artists;

use Drupal\restful\Plugin\resource\DataProvider\DataProviderEntity;
use Drupal\restful\Plugin\resource\DataProvider\DataProviderInterface;

class DataProviderArtists extends DataProviderEntity implements DataProviderInterface {

  protected function addExtraInfoToQuery($query) {
    // Add a generic tags to the query.
    parent::addExtraInfoToQuery($query);
    $query->addTag('restful_artists');
  }
}
```

Then with the resource class set the `ResourceNode::dataProviderClassName()` method:

```
<?php
/**
 * Created by PhpStorm.
 * User: adam
 * Date: 1/18/16
 * Time: 8:19 PM
 *
 * Maps to DefaultStyle (aka front page)
 */

namespace Drupal\livesource\Plugin\resource\entity\node\artists;

use Drupal\restful\Plugin\resource\ResourceNode;

/**
 * Class Artist__1_1
 * @package Drupal\livesource\Plugin\resource\entity\node\artists
 *
 * @Resource(
 *   name = "artists:1.1",
 *   resource = "artists",
 *   label = "Artists",
 *   description = "Export the artists with all authentication providers.",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "node",
 *     "bundles": {
 *       "artists"
 *     },
 *   },
 *   renderCache = {
 *     "render": FALSE
 *   },
 *   majorVersion = 1,
 *   minorVersion = 1
 * )
 */

class Artists__1_1 extends ResourceNode {

    protected function dataProviderClassName() {
        return '\Drupal\livesource\Plugin\resource\entity\node\artists\DataProviderArtists';
    }
}
```

With the tag available create a MODULE_query_restful_artists_alter function:

```
<?php
function livesource_query_restful_artists_alter(QueryAlterableInterface $query) {
    $request = $query->alterMetaData['restful_data_provider']->getRequest()->getParsedInput();
    $request = $_REQUEST['search'];
    $tid = 8; // country music genre tag
    $query->join('field_data_field_genres', 'field_data_field_genres', 'node.nid = field_data_field_genres.entity_id');
    $or = db_or();
    if (!empty($name)) {
        $prefix = '%'. db_like($request) . '%';
        $or->condition('title', array($prefix), 'LIKE');
    }
    if (!empty($tid)) {
        $or->condition('field_data_field_genres.field_genres_tid', array($tid), "=");
    }
    $query->condition($or);
}
```

Call the resource adding a search string to the URL query and access it either through the HTTP request object or $_REQUEST super global array. Use the db_or() to had conditions to the query. [More information on dynamic queries can be found on Drupal.org.](https://www.drupal.org/node/310086) also a [relevant Stack Exchange answer](http://drupal.stackexchange.com/questions/134760/using-hook-query-tag-alter-to-add-or-queries-to-entityfieldquery)

**Comment by e0ipso** [comment]
`isValidConjunctionForFilter` only allows the `AND` conjunction for `EntityFieldQuery` (entity resources) based resources. Sadly, that's a limitation of `EntityFieldQuery` and not RESTful.

You can alter the query as @adam-s suggests.

**Comment by mjoyce91** [comment]
@adam-s I have a similar implementation, but it results in an incorrect pagination count due to results that match both criteria being included in the final count. Did you have this issue as well?
