### ISSUE TITLE
'process_callbacks' on relationship fields

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#851]
Hello,

I'm having a great time with this module!

Question:

I have a relationship between two resources that is more complex than an entityreference field. In my case it is a relationship between 'companies' and 'articles'. To find articles related to a company, I need to do some custom processing.

I'm struggling to figure out how to do this. I searched around the docs and issues and found
https://github.com/RESTful-Drupal/restful/pull/712

I have tried this on the public fields of the companies:

``` php

$public_fields['articles'] = [
      'property' => 'nid',
      'process_callbacks' => [[$this,'getArticles']],
      'class' => 'Drupal\ii_rest\Plugin\resource\node\article\v1\Articles__1_0',
      'resource' => [
        'name' => 'articles',
        'majorVersion' => 1,
        'minorVersion' => 0,
      ],
    ];

```

My getArticles($nid) returns an array of article nids. 

But it seems the getArticles() function never gets called.

Any clues on how I can do this?

**Comment by adam-s** [comment]
I don't understand how you can get an array of 'nids' returned on an 'nid' property. The reason is that it will only return one value which is the 'nid' of the company. 'property' looks up not down. If there is an entity reference then use the field name of the entity reference, for example, 'field_articles'. If you leave out the 'resource' key then it will be an array of reference 'nids' belonging to articles. If you include the 'resource' key, then the passed value is an array of '\ResouceCollectionItems' with the EntityMetadataWrapper wrapped 'article' entity on the interpreter property.

I also don't understand what is meant by 'more complex than an entityreference field because that is just a field on the company entity that contains an array of 'nids' pointing to articles.

**Comment by tripper54** [comment]
Thanks for the reply, @adam-s . 

> I don't understand how you can get an array of 'nids' returned on an 'nid' property. The reason is that it will only return one value which is the 'nid' of the company. 'property' looks up not down.

The 'nid' property will be the nid of the company node. What I was hoping to do is pass that as an argument to my process callback, getArticles(), which will return an array of article nids (or whatever I need to pass back, maybe an array of \ResourceCollectionItems as you mention).

I have used this technique to return other public fields that don't map to fields on the company node, but return a string value. For example, 

``` php
$public_fields['latest_recommendation'] = [
      'property' => 'nid',
      'process_callbacks' => [[$this,'latestRecommendation']],
    ];
```

Which calls my process callback:

``` php

public function latestRecommendation($company_nid) {
    $company_node = node_load($company_nid);
    return share_advisor_get_current_recommendation_from_company($company_node);
  }

```

This works a treat for fields that just need a string value. But in the case of articles, I need more than just a string value returned, I need the related resource, so the client can have the option of adding an 'include=articles' GET arg to also fetch the related articles in a single request.

> If there is an entity reference then use the field name of the entity reference, for example, 'field_articles'.

There is no entity reference field. That's what I meant by the relationship being more complex than an entityreferencefield. There is an answer to the question "What articles are related to a company?", but it's not answerable by looking at an entityreference field. In the case of our web site, we figure out which articles to list as related to a company with a custom function, that inspects the company node, the article node, a few 'glue' entities and some other data in custom tables. So what I need to do is be able to use that function to return the related resources instead of using an entityreference field, because there isn't one. I hope that makes sense!

> I also don't understand what is meant by 'more complex than an entityreference field because that is just a field on the company entity that contains an array of 'nids' pointing to articles.

See above. There is no entity reference field. The relationship between articles is more complex than a simple one-to-one or one-to-many relationship. Instead it needs to be calculated base on a number of conditions.

So the information I'm seeking is how do I attach related resources to a response WITHOUT using entityreference fields?

**Comment by adam-s** [comment]
I understand. Sure you can return an array from a process callback containing articles but it's not jsonapi.org spec. You can pass in an array of nids that point to articles but not from an entity reference fields. I don't know if this helps but my guess is to use ['hook_entity_property_info_alter()'](http://www.drupalcontrib.org/api/drupal/contributions!entity!entity.api.php/function/hook_entity_property_info/7) which allows computed fields.

```
<?php

/**
 * @file
 * Provides info about book nodes.
 */

/**
 * Implements hook_entity_property_info_alter() on top of book module.
 *
 * @see entity_entity_property_info_alter()
 */
function tripper54_module_entity_property_info_alter(&$info) {
  // Add meta-data about the added node properties.
  $properties = &$info['node']['bundles']['company']['properties'];

  $properties['articles'] = array(
    'label' => t("Funky list of articles"),
    'type' => 'list<node>',
    'computed' => TRUE,
    'description' => t("A funky list of articles associated with a company and I don't know how to turn it off."),
    'getter callback' => 'tripper54_module_get_properties',
  );
}

function tripper54_module_get_properties ($node, array $options, $name, $entity_type) {
  // TODO Heavy use of \EntityFieldQuery and  db_select('node', 'n')
  // TODO Find out if this needs caching and optimization

  return array( 202, 203, 404, 3030 );
}
```

```
$public_fields['latest_recommendation'] = [
      'property' => 'articles',
      'process_callbacks' => [[$this,'latestRecommendation']],
    ];
```

If I get time I'll try to implement it. ([resource](https://alex-sansom.info/content/add-computed-property-existing-entity-and-expose-it-views))

**Comment by tripper54** [comment]
Thanks, that's an interesting suggestion, I hadn't thought of altering the entity at that level.

I'll try it and see how it goes.

**Comment by tripper54** [comment]
OK, so I have implemented hook_entity_property_info_alter() and added a custom getter callback that returns an array of ariticle nids.

If I test by loading a company node with entity_metadata_wrapper, I can find the articles using 

$company_wrapper->articles->value();

So far, so good.

I altered my publicFields() on the companies resource:

``` php

$public_fields['articles'] = [
      'property' => 'articles',
      'resource' => [
        'name' => 'articles',
        'majorVersion' => 1,
        'minorVersion' => 0,
      ],
    ];

```

So now this is what I'm getting in the JSON response for GET companies/13377

```
"relationships": {
      "articles": {
        "data": {
          "type": "articles",
          "id": "Array"
        },
        "links": {
          "related": "https://xxx.vm/api/v1.0/companies?filter[articles][0]=1229538&filter[articles][1]=1041873&filter[articles][2]=1041877&filter[articles][3]=1032704&filter[articles][4]=78082&filter[articles][5]=78067&filter[articles][6]=78011&filter[articles][7]=78010&filter[articles][8]=78004&filter[articles][9]=77953",
          "self": "https://xxx.vm/api/v1.0/articles/13377/relationships/articles"
        }
      }
    },
```

If I try adding include=articles , it crashes at FormatterJsonApi.php:310 

Any ideas?

**Comment by adam-s** [comment]
I solved it! Entity property getters never return an array (an assumption)  so there isn't reason to handle cardinality. I am wondering if there will negative side effects in other places. If so, consider a module like [Computed Field](https://www.drupal.org/project/computed_field) or define a field that only returns a computed array of articles. I like the idea of using a field instead of mucking up an entity definition. There is only a small handful of places in the code where `getFieldInfo()` is called. One is to see which ResouceField class to use which is explicitly set here and the other is to test for cardinality which is also set. 

If a field is used. The class still needs to be set to use ResouceFieldEntityReference because that is only set with original entity reference field.

I extended the ResourceField class to set the cardinality and set the class definition on the public fields array.

```
        $public_fields['funky_articles'] = array(
            'property' => 'artists',
            'class' => '\Drupal\livesource\Plugin\resource\entity\node\events\ResourceFieldFunkyArticlesEntityReference',
            'resource' => array(
                'name' => 'artists',
                'majorVersion' => '1',
                'minorVersion' => '1',
            ),
        );
```

```
<?php
/**
 * Created by PhpStorm.
 * User: adam
 * Date: 2/13/16
 * Time: 12:33 PM
 */

namespace Drupal\livesource\Plugin\resource\entity\node\events;

use Drupal\restful\Plugin\resource\Field\ResourceFieldEntityReference;
use Drupal\restful\Http\RequestInterface;

class ResourceFieldFunkyArticlesEntityReference extends ResourceFieldEntityReference {
    public function __construct(array $field, RequestInterface $request) {
        parent::__construct($field, $request);
        $this->setCardinality(-1);
    }
}
```

**Comment by tripper54** [comment]
Brilliant, thanks @adam-s . Extending ResourceFieldEntityReference to set cardinality indeed makes this work!

**Comment by e0ipso** [comment]
I see that I'm late to this one. For the record I'll say that in your field definition you can have the field class to use `\Drupal\restful\Plugin\resource\Field\ResourceFieldReference`. See https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/src/Plugin/resource/Field/ResourceFieldReference.php#L12-L29

Something along the lines of:

``` php
$public_fields['computed'] = array(
  'callback' => 'myCallback',
  'class'  => '\Drupal\restful\Plugin\resource\Field\ResourceFieldReference',
);
```

There was an example of how to do this in https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/tests/modules/restful_test/src/Plugin/resource/entity_test/main/v1/Main__1_8.php

**Comment by adam-s** [comment]
@e0ipso This is good to know because this is the correct solution to the first half the problem. I have to ask. Does this still work if

```
  protected static function complexCalculation() {
    return 1;
  }
```

returns an array because in @tripper54 use case there are multiple ids in an array? It is a one to many relationship so the complex calculation returns an array like:

```
  protected static function complexCalculation() {
    return array(1, 2, 3, 4);
  }
```

(I should really learn how to use Simple Test so I can answer these questions myself)
