### ISSUE TITLE
Using A Custom Database Table

### ISSUE THREAD

**Issue by trekkadmin** [RESTful-Drupal/restful#859]
Could someone point me in the right direction of where I would start if I wanted to exposed a custom database table that was installed with a 3rd party Drupal module as a resource endpoint?

Possibly there was an example I overlooked?

**Comment by trekkadmin** [comment]
It looks like I figured it out.  I overlooked the `DbQueryTest__1_0.php` example in the tests folder.  I used this as an example and I was able to achieve exactly what I was looking for.

**Comment by e0ipso** [comment]
Good to hear that!

**Comment by trekkadmin** [comment]
Yes, thank you very much for including those examples.  They were very helpful!
