### ISSUE TITLE
Drupal\restful\Authentication\AuthenticationManager doesn't find my Authentication plugin

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#862]
Hello!

I need to use a custom authentication plugin that allows users to login using either username or email.

I have created a class IIBasicAuthentication that extends BasicAuthentication. The basic idea is that I'll call the parent authentication, then if that fails, I'll try to authenticate using the supplied username as email.

However AuthenticationManager is not picking up my plugin. Peering in my DB registry table, the class is registered OK.

However in the AuthenticationManager->getAccount() where it loops through Authentication plugins, it only runs through BasicAuthentication and CookieAuthentication.

Any ideas as to what I'm doing wrong? Here's my class:

``` php

namespace Drupal\ii_rest\Plugin\authentication;

use Drupal\restful\Plugin\authentication\BasicAuthentication;
use Drupal\restful\Http\RequestInterface;


/**
 * Class IIBasicAuthentication
 * @package Drupal\ii_rest\Plugin\authentication
 *
 * @Authentication(
 *   id = "ii_basic_auth",
 *   label = "II Basic authentication",
 *   description = "Authenticate requests based on basic auth, by email or username",
 * )
 */
class IIBasicAuthentication extends BasicAuthentication {

  /**
   * {@inheritdoc}
   *
   * @see user_login_authenticate_validate().
   */
  public function authenticate(RequestInterface $request) {
    $parent_auth = parent::authenticate($request);
    $e = 0;
    // Do custom authentication here.
  }

}

```

**Comment by tripper54** [comment]
OK, I've figured this out.

Authentication Manager loops through the listed methods as defined in the resource annotations under 'authenticationTypes' eg

``` php
/**
* @Resource(
 *   name = "access_token:2.0",
 *   resource = "access_token",
 *   label = "Access token authentication",
 *   description = "Export the access token authentication resource.",
 *   authenticationTypes = {
 *     "cookie",
 *     "basic_auth",
 *     "ii_basic_auth"
 *   },
 *   authenticationOptional = FALSE,
 *   dataProvider = {
 *     "entityType": "restful_token_auth",
 *     "bundles": {
 *       "access_token"
 *     },
 *   },
 *   formatter = "single_json",
 *   menuItem = "login-token",
 *   majorVersion = 2,
 *   minorVersion = 0
 * )
*/

```

**Comment by e0ipso** [comment]
You can also set `authenticationTypes` to TRUE to loop through all the available authentication providers.
