### ISSUE TITLE
ApiDoc Documentation of Standard Endpoints

### ISSUE THREAD

**Issue by ianlintner-wf** [RESTful-Drupal/restful#865]
I am looking to integrate my application with APIDoc http://apidocjs.com/ which can process php comments. Due to the architecture, it isn't a perfect fit, but it is workable.

I am going to document the default endpoints. I would like to share this documentation with other RESTful users.

Would you be interested in a pull request for comments that could be used by APIDoc, it could be a submodule or in the project files. 

Otherwise I am going to provide it as a separate module or a standalone github repo since it isn't exactly core functionality.

**Comment by e0ipso** [comment]
It's a really interesting idea! It kind of relates to https://github.com/RESTful-Drupal/restful/wiki/Documenting-your-API. Also, you can hit any resource item with an `OPTIONS` request and you'll get documentation out of it (although I couldn't find the wiki page on that, maybe @jeff-h knows…).

I would do this in a separate module, that later on we can include in the `RESTful-Drupal` group. I'm going to close this issue (for workflow reasons) but feel free to keep me posted here!! I'd love to see how this shapes up.

**Comment by jeff-h** [comment]
(the page in the wiki about OPTIONS discovery data is at [OPTIONS and Resource discovery](https://github.com/RESTful-Drupal/restful/wiki/OPTIONS%20requests) )
