### ISSUE TITLE
Looking for suggestions for documentation workflow / best practice

### ISSUE THREAD

**Issue by tripper54** [RESTful-Drupal/restful#869]
I wonder if anyone has a workflow for documenting their API that they are happy with.

I'd like my documentation to be as clear and easy to consume as possible. Poor documentation is a top complaint for developers working on APIs. I've sung that tune myself many times.

I started by building a doc with google docs, but the developers who are consuming the API complain that it's difficult to follow.

Now I'm importing resources into https://apiary.io/ by using PAW to generate API Blueprint code for each method on each resource.

The generated documentation is much clearer, but the process seems a little laborious.

I suspect there must be a way to use the discovery mechanism of the API to generate human readable documentation, but I'm unsure how to progress.

Can anyone offer any insight into this?

**Comment by e0ipso** [comment]
The best documentation is the one that is self-generated. You can do this with the [options requests](https://github.com/RESTful-Drupal/restful/wiki/OPTIONS-requests) out of the box with RESTful.

Other solutions are good, but they get eventually outdated. In any case, if I had to choose between Apiary or RAML, I think I prefer RAML.

**Comment by tripper54** [comment]
Thanks for the reply! 

So the flow goes something like this:
1. Consume an OPTIONS request on and endpoint, which returns info about the fields etc in JSON
2. Convert this to RAML  - somehow???
3. Use the RAML to generate human readable docs - through a 3rd party service, or via your own tools?

So for step 2, should I write an API client with a JSON->RAML converter? Or write a RAML formatter for RESTful (Accept: application/raml+yaml)? How do you approach this?

For step 3, something like this https://github.com/raml2html/raml2html ?

**Comment by e0ipso** [comment]
That sounds about right. The RAML Formatter would be cool but unnecessarily complicated.
