### ISSUE TITLE
BREAKING CHANGE: 2.x does not support login-token using a token

### ISSUE THREAD

**Issue by josephdpurcell** [RESTful-Drupal/restful#874]
Scenario: a consumer of the API has a valid access token, but does not have access to the expiry time or refresh token.

Problem: In 1.x, you could send the access token header to the login-token route to get the token, its expiry, and refresh token, see example request: https://paw.pt/beYj1TKb. Currently, you cannot.

Solution: I believe one solution would be adding "token" authentication to the login-token route.

**Comment by josephdpurcell** [comment]
Here is a patch I've made that fits the exact use case I need: https://gist.github.com/josephdpurcell/15b42d4db835d5e3c803

My use case is (a) I need to disable cookie auth so a user can login to the API and SPA as separate users, and (b) I need to allow token auth to the login token route to get the expiry and refresh token values.

Does anyone else have a similar use case? Is there a different recommended solution?

**Comment by e0ipso** [comment]
Thanks for taking the time to report, @josephdpurcell

I'm not sure I know what you mean by

> but does not have access to the expiry time

**Comment by fpalluel** [comment]
Referencing a closed issue  #863.

Is there a 'clean' way to alter resource authentication types without patching ?
Cookie authentication seems to take precedence over token auth, leading to unexpected behaviour if a user has logged in drupal the 'traditional' way before invoking a restful resource.

Thanks !

**Comment by e0ipso** [comment]
See the resolution in #863.
