### ISSUE TITLE
getting info on taxonomy_vocabulary 

### ISSUE THREAD

**Issue by drogers98** [RESTful-Drupal/restful#883]
Howdy all, running into some issues in trying to make an endpoint for Vocabularies. Not sure if this is possible, but seems like it should be since it is defined as an entity (?), and I am receiving at least one piece of info back correctly (the count). I've been unable to find any other issues or documentation on setting up an endpoint specifically for taxonomy_vocabulary. Defining the following:

``` php
namespace Drupal\pack_search\Plugin\resource\entity\taxonomy;

use Drupal\restful\Plugin\resource\ResourceEntity;

/**
 * Class Taxonomies__1_0
 * @package Drupal\pack_search\Plugin\resource\entity\taxonomy
 *
 * @Resource(
 *   name = "taxonomies:1.0",
 *   resource = "taxonomies",
 *   label = "Taxonomies",
 *   description = "Taxonomies",
 *   authenticationTypes = TRUE,
 *   authenticationOptional = TRUE,
 *   dataProvider = {
 *     "entityType": "taxonomy_vocabulary",
 *   },
 *   majorVersion = 1,
 *   minorVersion = 0
 * )
 */
class Taxonomies__1_0 extends ResourceEntity {

  public function publicFields() {

    $public_fields = parent::publicFields();

    // Description field test
    $public_fields["description"] = array(
      "property" => "description",
    );
    return $public_fields;
  }
}
```

returns, the following, no data[] at all, but the count is correct. I can also confirm that adding taxonomies/etc adjusts the count as desired/one would imagine.

``` json
{
  "data": [],
  "count": 9,
  "self": {
    "title": "Self",
    "href": "http://tpackss.dev/api/v1.0/taxonomies"
  },
  "next": {
    "title": "Next",
    "href": "http://tpackss.dev/api/v1.0/taxonomies?page=2"
  }
}
```

Any help appreciated.

**Comment by e0ipso** [comment]
@drogers98 did you check the provided examples?

This seems that should be very relevant: https://github.com/RESTful-Drupal/restful/blob/7.x-2.x/modules/restful_example/src/Plugin/resource/Tags__1_0.php

**Comment by e0ipso** [comment]
Also, it seems that you are referencing the wrong field for the `'property'`.

**Comment by drogers98** [comment]
@e0ipso Thanks for the reply,

I did indeed check that example, and do in fact have several successful endpoints already set up for the taxonomy_term entityType, and subsequent bundles/etc. In that example, and to my limited knowledge, the taxonomy_term entityType will always return terms, when **what I need is a list of the actual Vocabularies (not terms), and subsequent fields on them**. I had assumed the correct way to do this would be to query the taxonomy_vocabulary entityType, but open to suggestions for sure, and apologies if I'm missing something basic here.

For the description field, I was trying to reference the field in line 109 of entity/modules/taxonomy.info.inc (entity module), where fields for taxonomy_vocabulary are defined. Perhaps I'm misunderstanding how I should be accessing that.

Thanks again all for a great module, and any other help narrowing this down, if possible.

Cheers,

Dan

**Comment by nickrigby** [comment]
Hi @e0ipso.

In the example from @drogers98, he is using the entityType of "taxonomy_vocabulary", whereas the example you pointed to uses the "taxonomy_term".

It seems that the taxonomy_term entity type is concerned with returning terms for a specific taxonomy, whereas taxonomy_vocabulary appears to be concerned with bringing back specific fields that are attached to a taxonomy. However, it doesn't seem to bring back any data. Can you take a look at the example code from @drogers98 and see if there is something missing from the resource configuration?

To clarify, we are trying to get a specific field that is attached to a taxonomy, rather than only the terms for that taxonomy.

Many thanks for your help!

**Comment by e0ipso** [comment]
I'm not sure what you mean by _we are trying to get a specific field that is attached to a taxonomy_. Is that the contents of the field in a taxonomy term?

**Comment by e0ipso** [comment]
@drogers98 in `taxonomy.module` you will see that:

``` php
  $return['taxonomy_vocabulary'] = array(
    'label' => t('Taxonomy vocabulary'),
    'controller class' => 'TaxonomyVocabularyController',
    'base table' => 'taxonomy_vocabulary',
    'entity keys' => array(
      'id' => 'vid',
      'label' => 'name',
    ),
    'fieldable' => FALSE,
  );
```

Is a regular entity with 2 properties `vid` and `name`. The entity is not fieldable. Did you try using any of those properties in your public fields? See how `taxonomy_field_extra_fields` only adds fields to the terms.

**Comment by georgibakken** [comment]
@drogers98: Have you had any success in getting the Vocabularies? 
I'm in a similar situation

**Comment by drogers98** [comment]
@georgibakken, I did manage to get the initial posted code working, but it only worked for logged in (admin) users. In my case, it turns out above code would indeed return list of vocabularies and descriptions, but again, only through the browser with a cookie, postman return the empty data[]. I ended up solving my particular problem a different way, but hope this helps. @e0ipso is totally right that they are not fieldable entities, in my case I was just looking for the description. Good Luck, and if you do find a workaround, please post back!
