### ISSUE TITLE
8x usability

### ISSUE THREAD

**Issue by rroblik** [RESTful-Drupal/restful#887]
Hi

I'm very glad to see the 8x branch here ! It was a long waiting time but for the best Rest Drupal plugin... It's a needed time !

My question is quite simple : I have to build a new api from ground. Should I start it on Drupal 7 + Restful 7x or the 8x version is quite usable (with Drupal 8) ?

Thanks for comments.

**Comment by e0ipso** [comment]
Unfortunately 8.x-3.x is very far from being usable.
