### ISSUE TITLE
Make authenticationOptional FALSE for write methods

### ISSUE THREAD

**Issue by xuxucode** [RESTful-Drupal/restful#890]
In most cases `authenticationOptional = TRUE` is suitable for read methods (GET, HEAD, etc.), but **NOT** for write methods (POST, PATCH, etc.). 

For instance, set `authenticationOptional = TRUE` to Articles__1_0 resource, any user can `GET` articles, but only the authenticated user can `POST` a new article, how to do that?

This happened on my client when I post a new article, as the access_token has expired,  got a `ForbiddenException`,  instead I want an `UnauthorizedException`.

I handle this using below code for every resource, am I missing something or is there a better way?

``` php
class Articles__1_0 extends ResourceNode implements ResourceInterface {

  /**
   * {@inheritdoc}
   *
   * @throws UnauthorizedException
   *   If the user is not authenticated for write methods.
   */
  public function process() {
    if (Request::isWriteMethod($this->getRequest()->getMethod())) {
      if ($this->getAccount()->uid == 0) {
        throw new UnauthorizedException('Bad credentials. Credentials not provided or have expired.');
      }
    }
    return parent::process();
  }
}
```

**Comment by e0ipso** [comment]
It would seem better to alter the access method instead.

(didn't check the code, coding from memory).

``` php
public function access() {
  if ($this->getRequest()->getMethod() == RequestInterface::METHOD_GET) {
    return TRUE;
  }
  return parent::access();
}
```

**Comment by e0ipso** [comment]
Please let me know if that helped you, and the actual code snippet for the posterity :-)

**Comment by xuxucode** [comment]
Thanks :)  I tried your code, it issued a `403 Forbidden. You do not have access to create a new resource`.

What I exactly want is to get an `UnauthorizedException` instead of the `ForbiddenException` when a user that has a expired access token `POST` a new article.

**Comment by xuxucode** [comment]
maybe

``` php
public function access() {
  if (Request::isWriteMethod($this->getRequest()->getMethod())) {
    if ($this->getAccount()->uid == 0) {
      throw new UnauthorizedException('Bad credentials.');
    }
  }
  return parent::access();
}
```

any suggesttion?

**Comment by xuxucode** [comment]
Thanks.
