### ISSUE TITLE
Null derivatives results in invalid foreach()

### ISSUE THREAD

**Issue by krisgraham** [RESTful-Drupal/restful#900]
Using 8.x-3.x

Getting this warning:
`Invalid argument supplied for foreach() in                                                                            [warning]
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator-&gt;getDerivatives() (line 101 of
core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php).`

It looks like getDerivativeDefinitions() is returning null when RESTful is first enabled, and getDerivatives() expects something if a deriver is returned from getDeriver for the plugin (restful_entity). Any advice on the best way to fix this? Maybe don't return a $deriver if there are no definitions for the plugin in RESTful or add better handling of this in core?

**Comment by e0ipso** [comment]
Hello @krisgraham.

At the moment the 8.x-3.x branch is not very useful, since I'm finding the time to work on it. I'll rename the branch so this confusion doesn't keep happening.

Sorry for the inconveniences.
