### ISSUE TITLE
Invalid URL path when requesting /api/session/token

### ISSUE THREAD

**Issue by rhclayto** [RESTful-Drupal/restful#905]
Hi,

I cannot get the CSRF token functionality to work. When doing a GET request to https://example.com/api/session/token , I receive:

``` json
{
  "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5",
  "title": "Invalid URL path.",
  "status": 404,
  "detail": "Not Found"
}
```

I have two custom resource plug-ins defined, other than that everything is stock RESTful (cloned from Github not drupal.org). I had the Services module installed at one point but I have uninstalled it & the problem persists. I have run `drush rr` & `drush cc all` (& `drush cc menu` for good measure), multiple times. I have tried logging in & out of Drupal, & running the drush commands while logged in & logged out in every conceivable permutation. All with no change in the result when visitng the CSRF session token URL.

The mystery to me is that all yesterday I was working on the endpoints using a token I obtained from /api/session/token. Yet when I started again this morning I could not generate another token. The only thing that has changed between successfully generating the token & today's failure is the two resource plugins I have been working on. Could my custom resource plug-ins somehow be interfering with the token plugin? I have not made any changes to what came with RESTful itself, or to anything else at all on the system (FreeBSD 10.2, Apache 2.4, PHP 5.6.20...).

Any ideas? I'm stuck.

PS: Disabling the custom resource plugins & running the drush commands doesn't help. I just tried it.

**Comment by rhclayto** [comment]
Well, I found the problem. I have absolutely NO idea how this might have happened, but on a hunch I looked in the menu_router table in the database & found that the route was recorded as `api//session/token`. Two slashes. Again, I am at a loss to explain how that might have happened, but changing it manually solved the error. So I'm closing this.

**Comment by e0ipso** [comment]
Thanks for taking the time to post back. That will help other people in the future. Let me know if that keeps happening in the future.

**Comment by OnGitHubSchatz** [comment]
This is occurring for me infrequently on some staging environments.
Clearing cache with above methods `drush rr & drush cc all (& drush cc menu)` are not addressing the issue.

Related to https://github.com/RESTful-Drupal/restful/issues/1067 I think with my registry.
