### ISSUE TITLE
Copy file_save_upload() to get better error details

### ISSUE THREAD

**Issue by amitaibu** [RESTful-Drupal/restful#91]
https://github.com/Gizra/restful/blob/7b8502ae74f9ab841bcf17ce8ffeed4873c1315b/plugins/restful/file/files_upload/1.0/RestfulFilesUpload.class.php#L51

`file_save_upload()` isn't API friendly. The errors are sent via `drupal_set_message()`.
We could copy file_save_upload() and run the validations ourself, so when we hit a validation error we'll have better error messages.

**Comment by e0ipso** [comment]
+1

I also feel that there is a lot of cruft related to configuration that we don't need, so we could be simplifying it as well.

**Comment by amitaibu** [comment]
>  a lot of cruft related to configuration that we don't need

You mean the variables to get the file-upload feature working? If so, It's for security reasons.

**Comment by amitaibu** [comment]
Assigned to @snirs90. Happy contribution hour :)
