### ISSUE TITLE
Sub-resources or hookMenu example

### ISSUE THREAD

**Issue by raystuart** [RESTful-Drupal/restful#914]
First, thanks for an awesome module. I really enjoy using RESTful.

I'd like to return a set of resources that are "subthings" of a "thing" resource. For example, the subthings might be entity refrences, or they might be taxonomy terms, or some other resource connected in some way to the "thing" resource. And the main thing is that I would like to be able to page through those subthing resources using the normal RESTful paging query parameters.

I can imagine a number of ways to do this with RESTful, but the way I wanted to approach it is by having a plugin that returns subthing resources from a url like `thing/<thingid>/subthings`. Would this be a use for setting up a custom hook_menu item and setting hookMenu to FALSE?

Is there any other way to handle this via RESTful that I am missing? Are there any hookMenu examples out there, by chance?

Thanks!

**Comment by e0ipso** [comment]
> Would this be a use for setting up a custom hook_menu item and setting hookMenu to FALSE?

Yes.

> Are there any hookMenu examples out there, by chance?

There are several in RESTful "core". You can check the login resource, the file upload, the csrf, the authentication token, … all of those declare static URL templates. Your case will be a bit different though.

I'm closing this for organization purposes, but feel free to keep commenting or requesting to re-open the issue.

Cheers!

**Comment by raystuart** [comment]
Thanks for the reply!

I had seen the use of menuItem for resources like authentication token, which makes sense to me

```
modules/restful_token_auth/src/Plugin/resource/AccessToken__1_0.php: *   menuItem = "login-token",
```

but I hadn't seen any examples for hookMenu set to FALSE

```
src/Annotation/Resource.php:  public $hookMenu = TRUE;
```

I'll be looking into this today, and I'll follow along with what is in `restful_menu()`.

Thanks!
