### ISSUE TITLE
2.x IN Operator filter

### ISSUE THREAD

**Issue by GaxZE** [RESTful-Drupal/restful#921]
Hi,

Just unable to understand when using the "IN" operator for filtering why this isn't working:

`api/urlalias?filter[language][operator]="IN"&filter[language][value]=ar,en`

I have managed to get:
`api/urlalias?filter[language][value][0]=ar&filter[language][value][1]=en&filter[language][operator][0]="IN"&filter[language][operator][1]="IN"`

to work. Seems unnecessary to have the operator twice. If I remove the 2nd operator it breaks.

**Comment by e0ipso** [comment]
I see that you are enclosing the `IN` operator with extra quotes (`"IN"`). That may break things.

Please check https://www.youtube.com/watch?v=O60asFAnI7A&index=12&list=PLZOQ_ZMpYrZv8_c7jd_CkO_93-DnyVFY5 for more information about how to use filters.

**Comment by GaxZE** [comment]
@e0ipso Many thanks, totally forgot about the videos.
