### ISSUE TITLE
can't post multipart/form-data content type to my articles node in rest

### ISSUE THREAD

**Issue by mohn93** [RESTful-Drupal/restful#931]
i want to post new article with the image to my articles resource , when i try to submit a form data with `content-type=multipart/form-data` to the resful service on the articles resource it returns the following:

`{
  "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.4",
  "title": "Formatter plugin class was not found.",
  "status": 503,
  "detail": "Service Unavailable",
  "instance": "http://localhost/drupal7/help/restful/problem-instances-bad-request"
}`

**Comment by e0ipso** [comment]
@mohn93 I see you closed this one. Can you share what the problem was? That may help others in the future.

**Comment by mohn93** [comment]
i figured that the files can't be uploaded with other params in the http protocol  ,so i decided that i upload the file first and get an id for it , and just place the id of the file in the image property when i post the article ^^
