### ISSUE TITLE
Geographic Coordinate Radius Filters and Sorting

### ISSUE THREAD

**Issue by mjoyce91** [RESTful-Drupal/restful#948]
Any plans to add filters that would allow for filtering and sorting by geographic coordinates (latitude, longitude)?

Something like:

`...?filter[coords][value]=[39.1,-79.2]&filter[coords][operator]=RADIUS&filter[coords][radius]=500&sort=coords`

Where would be a good place to start if I wanted to build this on my own?

**Comment by e0ipso** [comment]
Unfortunately there are no plans for new features. I'm not sure how I'd go about to implement this, but you should have all the tools to do it in a separate module.

If you do that, please contribute that module so others can benefit from this.

**Comment by mjoyce91** [comment]
I was able to add this functionality by accessing the `GET` parameters and calling a `hook alter`. Now I can call `...?lat=40&lng=-78&radius=100` and return my results within the search radius, sorted nearest to farthest. I use a callback to return the distance within the object, ie: `{...,distance:36,...}`.

I may post the code later once I've cleaned it up a bit, but if any one is interested feel free to reach out and I can help you get started.

**Comment by pbruneau** [comment]
Hi, I'm also interested in custom operators: and it seems you have found a way. Could you please share further of your progress? That would be great :)

**Comment by mjoyce91** [comment]
@pbruneau - yes, I found a way. I'll need to dig into the code a bit before providing you an adequate response though. I could provide some samples this weekend.

**Comment by pbruneau** [comment]
Alright, would be awesome :) thanks in advance!
