### ISSUE TITLE
AccessToken : "Unprocessable Entity"

### ISSUE THREAD

**Issue by cedatif** [RESTful-Drupal/restful#951]
Hi all,

I'm trying to implement login in my custom restful module and don't understand why it doesn't work :(

`{"type":"http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html","title":"The property refresh_token_reference could not be found in restful_token_auth:access_token.","status":422,"detail":"Unprocessable Entity; Validation errors."}`

I use this: https://github.com/RESTful-Drupal/restful/issues/863#issuecomment-200254487

my code : 
```php<?php
/**
- @file
- Contains Drupal\macg_restful\Plugin\resource\AccessToken__1_1.
  */

namespace Drupal\macg_restful\Plugin\resource;

use Drupal\restful\Plugin\resource\ResourceInterface;
use Drupal\restful_token_auth\Plugin\resource\AccessToken__1_0;

/**
- Class AccessToken__1_1
- @package Drupal\macg_restful\Plugin\resource
  *
- @Resource(
-   name = "access_token:1.1",
-   resource = "access_token",
-   label = "Access token authentication",
-   description = "Export the access token authentication resource.",
-   authenticationTypes = {
-     "basic_auth"
-   },
-   authenticationOptional = FALSE,
-   dataProvider = {
-     "entityType": "restful_token_auth",
-     "bundles": {
-       "access_token"
-     },
-   },
-   formatter = "single_json",
-   menuItem = "login-token",
-   majorVersion = 1,
-   minorVersion = 1
- )
  */
  class AccessToken__1_1 extends AccessToken__1_0 implements ResourceInterface {}
```

Any help would be greatly appreciated.
Thanks !

**Comment by jeff-h** [comment]
Could you place the request you're using into a comment here so we can see that? (whatever you're using to create the request should be fine e.g. jQuery, CURL or whatever)

Also, could you edit your question and convert your single back-ticks to triple-back-ticks with a language identifier? This will tell GitHub to format your multi-line PHP code block much better :)

<code>&#96;&#96;&#96;php</code>
<?php

$Your_code_here;
<code>&#96;&#96;&#96;</code>

**Comment by cedatif** [comment]
Hi,

I use an API tool : Paw (paw.cloud) but in CURL, same error, it should be this : 

``` shell
curl -X "GET" "https://www.example.com/api/login-token" \ -u login:pass
```

**Comment by jeff-h** [comment]
Strange. I also use Paw and my login-token request generates the exact same cURL code as you pasted above.

I don't honestly even know what the `refresh_token_reference` is for. I globally searched the RESTful code for it and turns out it's a Drupal field. Do you have `field_data_refresh_token_reference` in your Drupal database? You do have the RESTful token authentication module turned on, right?

Sorry I'm not of much use. I suspect you have probably already done so, but all I can think is to take it all back to the simplest possible scenario. Turn off your module (or remove your code temporarily and `drush rr`), and ensure the out-of-the-box v.1.0 login-token is working for you?

**Comment by cedatif** [comment]
Hi, 
Thank you so much for helping me.

So, I don't have any `field_data_refresh_token_reference`in my database ..
Yes, the auth module is turned on.

Yes I already tuned off my module (with a `drush rr & cc all`) and it doesn't work either :(

I think is another module that is guilty, i'm going to investigate : with a clean Drupal install, it works.

**Comment by cedatif** [comment]
Hi,

I've reinstalled the module after a complete clean and it seems to be ok !
I also remove remove unused module which depend of entity module (term_merge and rules).

**Comment by jeff-h** [comment]
All very strange. Glad you got it working! Sounds like the token auth module never installed itself properly the first time around, though how that could happen I'm unsure.
