### ISSUE TITLE
Call to a member function createInstance() on null Error

### ISSUE THREAD

**Issue by EmmanVazz** [RESTful-Drupal/restful#952]
I upgraded to Drupal 7.51 recently and also to 7.x-2.13. Now I started getting this error out of nowhere when I drush cc all or make request. I know it is coming from [this](https://github.com/RESTful-Drupal/restful/blob/b5f717945081be3f1aa22968f140a3b6d056fea1/src/Plugin/ResourcePluginManager.php#L65) but idk why it just started. Anyone else experience this issue?

```
WD php: Error: Call to a member function createInstance() on null in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 73 of                                                                                       [error]
/var/www/html/sites/all/modules/service_container/lib/Drupal/Component/Plugin/PluginManagerBase.php).
Error: Call to a member function createInstance() on null in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 73 of /var/www/html/sites/all/modules/service_container/lib/Drupal/Component/Plugin/PluginManagerBase.php)
```

**Comment by jeff-h** [comment]
Have you also tried running `Drush rr`? This sounds more like a PHP OO issue rather than a RESTful-specific issue.

**Comment by EmmanVazz** [comment]
Let me try that.

**Comment by EmmanVazz** [comment]
I get this when I run drush rr with RESTful enabled. 

```
The registry has been rebuilt via registry_rebuild (A).                                                                                                                                                                            [success]

The registry has been rebuilt via registry_rebuild (A2).                                                                                                                                                                           [success]
WD php: Error: Call to a member function createInstance() on null in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 73 of                                                                                       [error]
/var/www/html/sites/all/modules/service_container/lib/Drupal/Component/Plugin/PluginManagerBase.php).
Cannot modify header information - headers already sent by (output started at /var/www/html/sites/all/modules/menu_thumbnails/menu_thumbnails.module:130) bootstrap.inc:1471                                                       [warning]
Error: Call to a member function createInstance() on null in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 73 of /var/www/html/sites/all/modules/service_container/lib/Drupal/Component/Plugin/PluginManagerBase.php).
Drush command terminated abnormally due to an unrecoverable error. 
```

When it is disabled it doesn't give that error and runs properly.

**Comment by EmmanVazz** [comment]
I tried that and get this error from drush rr when RESTful is enabled.

```
The registry has been rebuilt via registry_rebuild (A).                                                                                                                                                                            [success]
The registry has been rebuilt via registry_rebuild (A2).                                                                                                                                                                           [success]
WD php: Error: Call to a member function createInstance() on null in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 73 of                                                                                       [error]
/var/www/html/sites/all/modules/service_container/lib/Drupal/Component/Plugin/PluginManagerBase.php).
Error: Call to a member function createInstance() on null in Drupal\Component\Plugin\PluginManagerBase->createInstance() (line 73 of /var/www/html/sites/all/modules/service_container/lib/Drupal/Component/Plugin/PluginManagerBase.php).
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                 [error]
```

 If I disable RESTful drush rr completes properly.

**Comment by jeff-h** [comment]
Are you able to xdebug this? I added the following into the `ResourcePluginManager::createInstance` method:

``` php
    $test = get_parent_class();
```

i.e. 

``` php
  public function createInstance($plugin_id, array $configuration = array()) {
    xdebug_break();
    $test = get_parent_class();

    /* @var ResourceInterface $resource */
    $resource = parent::createInstance($plugin_id, $configuration);
    $resource->setRequest($this->request);
    return $resource;
  }
```

The value of `$test` for me is `Drupal\Core\Plugin\DefaultPluginManager`. Interested to know if yours is the same.

**Comment by EmmanVazz** [comment]
yeap I get Drupal\Core\Plugin\DefaultPluginManager

**Comment by jeff-h** [comment]
I'm running out of ideas :( The `Call to a member function on null` error seems pretty unpredictable in its cause, and it's not one I've had before. How can the `parent` be null when it obviously exists, since its child is what's throwing this error?

**Comment by EmmanVazz** [comment]
Might it be that it is somehow going to service_container's implementation versus the core one?

**Comment by EmmanVazz** [comment]
I got it, it is with the service_container not RESTful.

It was doing `$this->factory->createInstance($plugin_id, $configuration);` instead of `$this->getFactory()->createInstance($plugin_id, $configuration);` which is what 8.3 does for [createInstance](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Plugin%21PluginManagerBase.php/8.2.x). 

I will make an issue on their project and will close this. Thanks for the help :).

**Comment by jeff-h** [comment]
Ohh, sorry I completely overlooked that you're also using the service_container module, and that that module also defines a `PluginManagerBase` class with a `createInstance` method. Not that that should implicitly be any kind of problem.

However, I am beginning to wonder whether the error actually has anything to do with RESTful at all? Your error mentioned above doesn't reference RESTful at all.

I downloaded service_container and it has nothing on line 73, so I'm wondering if you might be running an old version of that module. You never know your luck, maybe the current version will fix everything :D

**Comment by jeff-h** [comment]
Ha, lol. You beat me to it :)

**Comment by drupol** [comment]
Hi all,

I'm co-maintainer of Service Container and I'm willing to help. It's good to see people using the module !
Let me know if you have found a solution to this problem.

The issue on drupal.org: https://www.drupal.org/node/2824774 doesn't help me that much.
AFAIK, adding a method getFactory() won't help. Indeed, that method just returns a factory, nothing else. I'm wondering why using a method instead of a variable helped you getting it working btw.

Thanks in advance!

**Comment by EmmanVazz** [comment]
Hello. The issue for me was that $this->factory was resolving to null and then you call $this->factory->createInstance($plugin_id, $configuration) on line 71 so that generates an exception. Yeah if I try switching it back, I start getting the errors again. I see that this function just returns $this->factory in the [dev version](https://github.com/LionsAd/service_container/blob/77c4eb1836ec2c2b18f710a5c7f2f0795fea4348/lib/Drupal/Component/Plugin/PluginManagerBase.php#L55)  of this module. However it is not there in the release version so it is not on my instance. Idk where getFactory is getting resolved for the release version, maybe that can help see why this solved my issue.
