### ISSUE TITLE
Add an HMAC authentication API provider

### ISSUE THREAD

**Issue by cpliakas** [RESTful-Drupal/restful#96]
This might be in the realm of a contributed add-on, but it would be great to implement an HMAC authentication provider to give a more secure option than HTTP basic authentication or session-based authentication. Acquia recently released an open-source library to facilitate implement such a system at https://github.com/acquia/hmac-request.

Thanks in advance for your consideration,
Chris

**Comment by amitaibu** [comment]
@cpliakas maybe it's better creating a contrib module for this? Are you planning to work on this?

**Comment by cpliakas** [comment]
@amitaibu, yes I have an intern working on this as a contributed module. Will close the issue and post a link to the repository / module when it is ready.

Thanks!
Chris
