### ISSUE TITLE
Cached response not used when User-Agent header is different

### ISSUE THREAD

**Issue by mjoyce91** [RESTful-Drupal/restful#965]
After performing some tests in Postman, it appears that Restful looks at the User-Agent header when deciding whether or not to return a cached response. This is inefficient, as my content does not differ based on the User-Agent. Is there any way to ignore this header?

**Comment by e0ipso** [comment]
How did you arrive to this conclusion? Can you please send a link to the code where this is happening?

**Comment by mjoyce91** [comment]
So, I went back and determined it's actually a cookie being added that does this. I was trying to figure out why cached results were only being loaded in Chrome, but not Safari and Opera - it's because Chrome was the only browser that I was logged in to Drupal from. Because my headless application lives on the same domain as my Drupal instance, cookies were automatically getting added to my requests - and this makes sense that they would not use the cached values, as in the cache config it is stated:

> CAUTION: If your resources are using authentication providers other than cookie, you will want to turn this off. Otherwise you may get cached anonymous values for your authenticated GET requests.

Will close.
