### ISSUE TITLE
Handling non-standard fields in publicFields

### ISSUE THREAD

**Issue by pbruneau** [RESTful-Drupal/restful#976]
I'm trying to expose a non-standard field (of type "Partial date and time range"), that goes by the name `field_timespec_interval` in the backend. In my `publicFields` method I have:

    $public_fields['timespec_interval'] = array(
      'property' => 'field_timespec_interval',
    );

But when attempting to hit the respective route I'm getting an error 422 in the JSON with title: `The property field_timespec_interval could not be found in node:timespec.`, despite it being correctly defined, and more standard field types such as text and entity references showing up nicely in the exposed API.

Following https://github.com/RESTful-Drupal/restful/wiki/2.3.-Defining-a-custom-field-class-(2.x), I also tried to define a handler class and added:

    'class' => '\Drupal\locale_restful\Plugin\resource\fields\ResourceFieldEntityInterval'

in the array specification - no change in the outcome. I also tried to remove the `property` field (leaving only `class`, but then I get:

    Fatal error: Cannot use object of type stdClass as array in /var/www/sites/all/modules/restful/src/Plugin/formatter/FormatterJsonApi.php on line 321

So eventually, I'm wondering how to handle fields that end up unrecognized as `property` - this might be a noob question and sorry by advance for it, but any direction would be valuable! Thanks

**Comment by e0ipso** [comment]
```
$public_fields['timespec_interval'] = array(
  'property' => 'field_timespec_interval',
);
```

Is the way to go. Make sure that you don't have any typos in it. Also, depending on the columns of the field you may want to use the `'sub_property'` or `'column'` settings in the public field config.

**Comment by pbruneau** [comment]
Whenever `property` is set (with no typo, wouldn't post here if I hadn't checked like 20 times before) the same error is obtained, whatever additional keys such as `sub_property` or `column` are also present.

I suspect something is wrong with the `partial date and time` node def - since then I've opted for my own custom node def, with success.
