### ISSUE TITLE
POSTing a file with the file-upload route

### ISSUE THREAD

**Issue by pbruneau** [RESTful-Drupal/restful#994]
Hi all,

This is going to sound like a trivial request, but where could I find detailed example of a file-upload request (with all required headers and body format, e.g. using postman), assuming token auth is activated?

For example, here is one of my (many) unsuccessful trials:
![image](https://cloud.githubusercontent.com/assets/4252621/26206016/e14f835c-3be3-11e7-92d4-3dc9b0fe58b0.png)

Besides, I manage to authenticate using token-auth, define endpoints with or without auth, access and post new content, but I can't figure out for this file-upload...

**Comment by pbruneau** [comment]
OK, I figured it out,
here is the proper settings in postman for version 7.x-2.16:
![image](https://cloud.githubusercontent.com/assets/4252621/26241776/361892be-3c86-11e7-96d4-e48dd4c059f5.png)
In brief, I just had to forget about Content-Type and Accept headers.

**Comment by e0ipso** [comment]
Thanks for closing the loop on this!
