### ISSUE TITLE
Customize output to remove square brackets

### ISSUE THREAD

**Issue by kdomenick** [RESTful-Drupal/restful#998]
I'm using the 7x.2x branch with the json_api formatter.  Everything is working great.  But my API is for one particular consumer, and they have some odd requirements.

When a field contains multiple values, it outputs them wrapped in square brackets.  I believe this designates an array.  Is it possible to customize the output to remove the brackets?  For example, what I currently have is this:
`{
"data": {
"type": "summit_providers",
"id": "10316",
"attributes": {
"id": "10316",
"name": "Dr. Smith, MD",
"standard_specialties": [
"Cardiovascular Disease",
"Bariatric Medicine",
"Anesthesiology"
],
"school": "The Best School of Medicine",` ...

What I want to have is this:
`{
"data": {
"type": "summit_providers",
"id": "10316",
"attributes": {
"id": "10316",
"name": "Dr. Smith, MD",
"standard_specialties": 
"Cardiovascular Disease",
"Bariatric Medicine",
"Anesthesiology",
"school": "The Best School of Medicine",` ...

**Comment by kdomenick** [comment]
Attached are my plugins for generating the JSON for my summit_providers content type and standard specialties (taxonomy terms).  
[Summit_Providers__1_0.php.txt](https://github.com/RESTful-Drupal/restful/files/1152775/Summit_Providers__1_0.php.txt)
[Standard_Specialties__1_0.php.txt](https://github.com/RESTful-Drupal/restful/files/1152776/Standard_Specialties__1_0.php.txt)

**Comment by mrconnerton** [comment]
That would produce invalid json. Those brackets are required so you know that its an array of values. What possible reason could they have for not supporting json arrays?

**Comment by kdomenick** [comment]
Thanks for your reply!

I agree 100% - without the brackets, not valid.  But that is what the consumer initially asked for.   I've continued to work with them, and they have been able to modify their end to handle the brackets.  They still have some other odd requirements I'm trying to work through, like lumping address fields into one large string, etc.  They claimed to support REST, but it seems like what they support is actually a limited implementation of REST/JSON.

**Comment by mjoyce91** [comment]
It's been awhile since I've used RESTful, but could a [process callback](https://github.com/RESTful-Drupal/restful/wiki/Using-process-callbacks-to-modify-field-data) be used to perform this? Used with the [implode function](https://www.w3schools.com/php/func_string_implode.asp).

It wouldn't be exactly as you've shown, since that's invalid JSON. But it could become some thing like `"Cardiovascular Disease, Bariatric Medicine, Anesthesiology, ..."` or `"'Cardiovascular Disease', 'Bariatric Medicine', 'Anesthesiology', ..."`.

**Comment by kdomenick** [comment]
That's a good idea.  The implode function may also help with the address field issue I'm having with this consumer.  Thank you!
